Repository dotnet/msbuild, pull requests merged in 2020-09, with the labels that each got.

#5625 Fix cpu core count detection
  src/MSBuild/XMake.cs
  src/Shared/NativeMethodsShared.cs
Labels: changewave16.8

#5734 Correctly interpret slashes Fixes #5715
  src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
  src/Build/Construction/Solution/SolutionFile.cs
Labels: Solution (.sln)

#5744 Reduce ImmutableDictionary.Comparers allocations
  src/Build.UnitTests/TestData/ProjectInstanceTestObjects.cs
  src/Build/Collections/CopyOnWritePropertyDictionary.cs
  src/Build/Construction/ProjectTaskElement.cs
  src/Build/Instance/ProjectTaskInstance.cs
  src/Shared/CopyOnWriteDictionary.cs
  src/Shared/UnitTests/CopyOnWriteDictionary_Tests.cs
  src/Tasks/Microsoft.Build.Tasks.csproj
  src/Utilities/TaskItem.cs
Labels: Performance-Scenario-General, performance
