Repository dotnet/msbuild, pull requests merged in 2020-05, with the labels that each got.

#5268 Allow disabling logging of task parameters and item metadata
  ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
  src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs
  src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupLoggingHelper.cs
  src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
  src/Framework/TaskPropertyInfo.cs
  src/Tasks/Microsoft.Common.props
Labels: Area: Logging, Performance-Scenario-Build

#5337 Enable MSBuild assemblies for client scenarios
  eng/Versions.props
  src/Package/MSBuild.VSSetup/MSBuild.clientenabledpkg
  src/Package/MSBuild.VSSetup/files.swr
Labels: Partner request

#5322 Fix ProjectRootElement.SdkReference
  src/Build.UnitTests/Construction/ProjectImportElement_Tests.cs
  src/Build.UnitTests/Evaluation/ProjectSdkImplicitImport_Tests.cs
  src/Build/Construction/ProjectImportElement.cs
  src/Build/Evaluation/Evaluator.cs
  src/Framework/Sdk/SdkReference.cs
Labels: merge-when-branch-open

#5329 Fix Comment at target ResolveComReferences
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#5339 Avoid errors on empty glob
  src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
  src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs
Labels: merge-when-branch-open

#5340 Only log tasks that fire
  src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
Labels: merge-when-branch-open

#5342 Add String.IndexOf to well known functions
  src/Build/Evaluation/Expander.cs
Labels: merge-when-branch-open

#5350 Make Remove-all-items O(1)
  src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs
  src/Build/Evaluation/LazyItemEvaluator.RemoveOperation.cs
  src/Build/Evaluation/LazyItemEvaluator.UpdateOperation.cs
Labels: merge-when-branch-open

#5369 Disable hanging tests
  src/MSBuild.UnitTests/XMake_Tests.cs
Labels: Disabled-Tests, testing
