Repository dotnet/msbuild, pull requests merged in 2020-10, with the labels that each got.

#5763 Fix SignFile task to be .NET Core aware
  ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
  ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
  src/Tasks/ManifestUtil/SecurityUtil.cs
  src/Tasks/Microsoft.Common.CurrentVersion.targets
  src/Tasks/SignFile.cs
Labels: Servicing-approved

#5764 Msbuilddisablenodereuse live check
  src/Build/BackEnd/BuildManager/BuildParameters.cs
  src/MSBuild/XMake.cs
  src/Shared/Traits.cs
Labels: Servicing-approved

#5741 Motivation docs for graph
  documentation/specs/static-graph.md
Labels: Documentation, Static Graph

#5795 Add files missing in ClickOnce SingleFile bundle.
  src/Tasks/GenerateLauncher.cs
  src/Tasks/ManifestUtil/Constants.cs
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: Servicing-approved

#5772 Fix for SCD ClickOnce publish of .NET Core App
  ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
  ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
  src/Tasks/Microsoft.Common.CurrentVersion.targets
  src/Tasks/ResolveManifestFiles.cs
Labels: Servicing-approved

#5783 Improve reliability of node handshake in 16.7 to match 16.8 for version information
  src/Shared/CommunicationsUtilities.cs
Labels: Servicing-approved, Servicing-consider

#5827 Add xunit timeout to hanging CancelledBuild test
  src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
Labels: Area: Our Own Build, merge-when-branch-open

#5818 Create instructions on how to test private bits
  documentation/Deploy-MSBuild.md
  documentation/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild.md
  documentation/wiki/Building-Testing-and-Debugging-on-Full-Framework-MSBuild.md
Labels: merge-when-branch-open

#5826 Update 16.7 error message when trying to use net5.0
  eng/Versions.props
  src/Tasks/GetReferenceAssemblyPaths.cs
  src/Tasks/Resources/Strings.resx
  src/Tasks/Resources/xlf/Strings.cs.xlf
  src/Tasks/Resources/xlf/Strings.de.xlf
  src/Tasks/Resources/xlf/Strings.en.xlf
  src/Tasks/Resources/xlf/Strings.es.xlf
  src/Tasks/Resources/xlf/Strings.fr.xlf
  src/Tasks/Resources/xlf/Strings.it.xlf
  src/Tasks/Resources/xlf/Strings.ja.xlf
  src/Tasks/Resources/xlf/Strings.ko.xlf
  src/Tasks/Resources/xlf/Strings.pl.xlf
  src/Tasks/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Resources/xlf/Strings.ru.xlf
  src/Tasks/Resources/xlf/Strings.tr.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Labels: Servicing-consider

#5839 Fix ClickOnce signing bug where built assembly and final exe are not signed
  eng/Versions.props
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: Servicing-approved

#5831 Try to avoid Mono intermittent TimeoutFailsEvenWhenExitCodeIsIgnored failure
  src/Tasks.UnitTests/Exec_Tests.cs
Labels: Area: Our Own Build
