Repository dotnet/msbuild, pull requests merged in 2021-12, with the labels that each got.

#7102 Prevent null reference exception with null Platform when using AL task
  src/Tasks/Al.cs
Labels: merge-when-branch-open

#7098 Minor refactor around project cache logging
  src/Build/BackEnd/Components/ProjectCache/PluginLoggerBase.cs
  src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs
  src/Build/PublicAPI/net/PublicAPI.Shipped.txt
  src/Build/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Build/PublicAPI/netstandard/PublicAPI.Shipped.txt
  src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt
Labels: merge-when-branch-open

#7103 Minor cleanup of ProjectLoggingContext
  src/Build.UnitTests/BackEnd/TargetBuilder_Tests.cs
  src/Build.UnitTests/BackEnd/TargetEntry_Tests.cs
  src/Build/BackEnd/Components/Logging/NodeLoggingContext.cs
  src/Build/BackEnd/Components/Logging/ProjectLoggingContext.cs
  src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
Labels: merge-when-branch-open

#7085 Remove locking and indirection from CopyOnWritePropertyDictionary
  src/Build.UnitTests/Collections/CopyOnWritePropertyDictionary_Tests.cs
  src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
  src/Build/Collections/CopyOnWritePropertyDictionary.cs
  src/Build/Instance/ProjectItemInstance.cs
Labels: merge-when-branch-open

#7068 Log explicit failure for LC on Core
  src/Tasks/LC.cs
  src/Tasks/Microsoft.Build.Tasks.csproj
  src/Tasks/PublicAPI/netstandard/PublicAPI.Unshipped.txt
Labels: .NET Core, Area: Tasks, merge-when-branch-open

#7118 Don't reference PublicApiAnalyzers in sourcebuild
  src/Directory.Build.targets
Labels: Area: Our Own Build

#7109 Associate Project Cache log messages with the project execution
  src/Build.UnitTests/BackEnd/LoggingServicesLogMethod_Tests.cs
  src/Build.UnitTests/BackEnd/MockLoggingService.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Components/Logging/ILoggingService.cs
  src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs
  src/Build/BackEnd/Components/Logging/ProjectLoggingContext.cs
  src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs
  src/Build/BackEnd/Shared/BuildRequest.cs
Labels: merge-when-branch-open

#7111 Use Enumerable.Empty<> over Array.Empty<>
  src/Build/BackEnd/Components/Logging/ProjectLoggingContext.cs
  src/Build/Instance/ProjectItemInstance.cs
  src/Shared/LogMessagePacketBase.cs
  src/Shared/TaskParameter.cs
  src/Utilities/TaskItem.cs
Labels: performance, merge-when-branch-open

#7127 Delete Mono build job
  .vsts-dotnet-ci.yml
Labels: merge-when-branch-open

#7055 Avoid temporary list allocations and specify list capacities in TaskItem
  src/Build.UnitTests/Instance/TaskItem_Tests.cs
  src/Build/Instance/ProjectItemInstance.cs
  src/Utilities.UnitTests/TaskItem_Tests.cs
  src/Utilities/TaskItem.cs
Labels: performance, merge-when-branch-open

#7117 Eliminate IDeepCloneable<T>
  src/Build.UnitTests/BackEnd/ConfigurationMetadata_Tests.cs
  src/Build.UnitTests/Collections/CopyOnReadEnumerable_Tests.cs
  src/Build/BackEnd/Components/Logging/ProjectLoggingContext.cs
  src/Build/Collections/CopyOnReadEnumerable.cs
  src/Build/Collections/IDeepCloneable.cs
  src/Build/Collections/ItemDictionary.cs
  src/Build/Collections/PropertyDictionary.cs
  src/Build/Instance/ProjectItemInstance.cs
  src/Build/Instance/ProjectMetadataInstance.cs
  src/Build/Instance/ProjectPropertyInstance.cs
  src/Build/Microsoft.Build.csproj
Labels: performance, merge-when-branch-open

#7128 Remove SourceLink.Create.CommandLine
  eng/dependabot/Packages.props
  src/MSBuildTaskHost/MSBuildTaskHost.csproj
Labels: Area: Our Own Build, merge-when-branch-open

#7084 Enable solution filtering with -graph option
  src/Build.OM.UnitTests/Construction/SolutionFile_Tests.cs
  src/Build.UnitTests/Construction/SolutionFile_Tests.cs
  src/Build.UnitTests/Construction/SolutionFilter_Tests.cs
  src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
  src/Build/Graph/GraphBuilder.cs
Labels: merge-when-branch-open

#7140 Fix bug in CacheSerialization.SerializeCaches
  src/Build/BackEnd/BuildManager/CacheSerialization.cs
  src/Tasks/GenerateResource.cs
Labels: merge-when-branch-open

#7143 Add GeneratePathProperty to xsd
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Labels: merge-when-branch-open

#7139 Add more SdkResolverService events and allow SdkResolvers to log events
  documentation/specs/event-source.md
  src/Build/BackEnd/Components/SdkResolution/CachingSdkResolverService.cs
  src/Build/BackEnd/Components/SdkResolution/OutOfProcNodeSdkResolverService.cs
  src/Framework/MSBuildEventSource.cs
  src/Framework/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Framework/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Framework/Sdk/SdkLogger.cs
Labels: merge-when-branch-open

#7150 Stop disabling compiler server in bootstrapped/CI build
  eng/cibuild_bootstrapped_msbuild.ps1
Labels: Area: Our Own Build, merge-when-branch-open

#7135 Fix possible race condition in ProjectRootElementCache.Get
  src/Build/Evaluation/Evaluator.cs
  src/Build/Evaluation/ProjectRootElementCache.cs
  src/Build/Evaluation/ProjectRootElementCacheBase.cs
  src/Build/Evaluation/SimpleProjectRootElementCache.cs
Labels: merge-when-branch-open

#7053 Fix stackoverflowexception
  src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
  src/Build/Graph/GraphBuilder.cs
Labels: merge-when-branch-open

#7155 Update up-to-date check items/properties in XSD
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Labels: merge-when-branch-open
