Repository dotnet/msbuild, pull requests merged in 2021-11, with the labels that each got.

#6998 Check if Documentis null before creating elementlocation object
  src/Build/ElementLocation/XmlAttributeWithLocation.cs
  src/Build/ElementLocation/XmlElementWithLocation.cs
Labels: merge-when-branch-open

#6983 Minor allocation optimizations / cleanup
  src/Build/BackEnd/Components/SdkResolution/CachingSdkResolverService.cs
  src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs
  src/Build/Utilities/EngineFileUtilities.cs
  src/Shared/FileUtilities.cs
  src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
Labels: merge-when-branch-open

#6996 Update Microsoft.Build.CommonTypes.xsd for `AnalysisLevel` and `AnalysisMode` values
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Labels: merge-when-branch-open

#6986 Remove pinned .NET Framework ref assembly package: let SDK provide it
  eng/Packages.props
Labels: merge-when-branch-open

#6995 Simplify property/item type requirements Fixes #6985
  src/Build/Evaluation/LazyItemEvaluator.RemoveOperation.cs
Labels: merge-when-branch-open

#7007 Stop loading Microsoft.DevDiv files as read-only
  src/Build/ElementLocation/XmlDocumentWithLocation.cs
Labels: merge-when-branch-open

#6999 Simplify verify throw and remove unnecessary usings
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Components/Logging/BuildEventArgTransportSink.cs
  src/Build/BackEnd/Components/Logging/EventSourceSink.cs
  src/Build/BackEnd/Components/Logging/LoggingService.cs
  src/Build/BackEnd/Components/RequestBuilder/BatchingEngine.cs
  src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs
  src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
  src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
  src/Build/Construction/Solution/ProjectInSolution.cs
  src/Build/Construction/Solution/SolutionProjectGenerator.cs
  src/Build/Definition/Toolset.cs
  src/Build/Errors/InternalLoggerException.cs
  src/Build/Evaluation/Conditionals/AndExpressionNode.cs
  src/Build/Evaluation/Conditionals/FunctionCallExpressionNode.cs
  src/Build/Evaluation/Conditionals/GenericExpressionNode.cs
  src/Build/Evaluation/Conditionals/NotExpressionNode.cs
  src/Build/Evaluation/Conditionals/NumericComparisonExpressionNode.cs
  src/Build/Evaluation/Conditionals/OperatorExpressionNode.cs
  src/Build/Evaluation/Conditionals/OrExpressionNode.cs
  src/Build/Evaluation/Conditionals/Parser.cs
  src/Build/Evaluation/ProjectParser.cs
  src/Build/Instance/TaskFactories/AssemblyTaskFactory.cs
  src/Build/Logging/BaseConsoleLogger.cs
  src/Build/Logging/DistributedLoggers/DistributedFileLogger.cs
  src/Build/Logging/NullCentralLogger.cs
  src/Build/Logging/SerialConsoleLogger.cs
  src/MSBuild/XMake.cs
  src/Shared/ConversionUtilities.cs
  src/Shared/ErrorUtilities.cs
  src/Shared/FileMatcher.cs
  src/Shared/Modifiers.cs
  src/Shared/ProjectErrorUtilities.cs
  src/Shared/ProjectFileErrorUtilities.cs
  src/Shared/TaskLoggingHelper.cs
  src/Tasks/AppConfig/BindingRedirect.cs
  src/Tasks/AppConfig/DependentAssembly.cs
  src/Tasks/AssemblyFolder.cs
  src/Tasks/Copy.cs
  src/Tasks/GenerateResource.cs
  src/Tasks/ResolveComReference.cs
  src/Tasks/XamlTaskFactory/CommandLineGenerator.cs
  src/Utilities/ToolTask.cs
  src/Utilities/TrackedDependencies/FileTracker.cs
Labels: merge-when-branch-open

#7013 CurrentHost was not properly set when DisableInProcNode = false
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
Labels: merge-when-branch-open

#7012 Use cached StringBuilder in CreateManifestResourceName
  src/Tasks/CreateCSharpManifestResourceName.cs
  src/Tasks/CreateVisualBasicManifestResourceName.cs
Labels: performance, merge-when-branch-open

#7009 Preventing warning in bootstrapper package self contained scenario
  src/Tasks/BootstrapperUtil/BootstrapperBuilder.cs
Labels: merge-when-branch-open

#7004 Attempt to prevent node explosions with parallel node creation
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs
Labels: merge-when-branch-open

#7030 Remove reference to .NET Core 2.1
  global.json
Labels: merge-when-branch-open

#6971 MSBuild 17.0 release notes
  documentation/Changelog.md
Labels: merge-when-branch-open

#6994 Enable TaskHostFactory for .NET (Core) MSBuild
  documentation/Built-in-Propeties.md
  src/Build.UnitTests/BackEnd/AssemblyTaskFactory_Tests.cs
  src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
  src/Build.UnitTests/BackEnd/TaskHostFactory_Tests.cs
  src/Build.UnitTests/EscapingInProjects_Tests.cs
  src/Build/BackEnd/Components/Communications/NodeEndpointOutOfProc.cs
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs
  src/Build/BackEnd/Node/OutOfProcNode.cs
  src/Build/Definition/Toolset.cs
  src/Build/Instance/TaskFactories/AssemblyTaskFactory.cs
  src/Directory.BeforeCommon.targets
  src/MSBuild/MSBuild.csproj
  src/MSBuild/NodeEndpointOutOfProcTaskHost.cs
  src/MSBuild/OutOfProcTaskHostNode.cs
  src/MSBuildTaskHost/MSBuildTaskHost.csproj
  src/Shared/CommunicationsUtilities.cs
  src/Shared/NamedPipeUtil.cs
  src/Shared/NodeEndpointOutOfProcBase.cs
  src/Shared/UnitTests/XmakeAttributes_Tests.cs
  src/Shared/XMakeAttributes.cs
  src/Tasks/Microsoft.Common.tasks
Labels: .NET Core, Area: Engine, merge-when-branch-open

#7036 Add VS Code tasks.json
  .vscode/tasks.json
Labels: merge-when-branch-open

#7024 Add enumeration values for CopyToOutputDirectory in XSD
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Labels: merge-when-branch-open

#7040 Improve globbing performance
  ref/Microsoft.Build/net/Microsoft.Build.cs
  ref/Microsoft.Build/netstandard/Microsoft.Build.cs
  src/Build.OM.UnitTests/Definition/Project_Tests.cs
  src/Build.UnitTests/Globbing/CompositeGlob_Tests.cs
  src/Build.UnitTests/Globbing/MSBuildGlobWithGaps_Tests.cs
  src/Build.UnitTests/Globbing/MSBuildGlob_Tests.cs
  src/Build/BackEnd/Shared/BuildRequestConfiguration.cs
  src/Build/Definition/Project.cs
  src/Build/Evaluation/ItemSpec.cs
  src/Build/Globbing/CompositeGlob.cs
  src/Build/Globbing/IMSBuildGlob.cs
  src/Build/Globbing/MSBuildGlob.cs
  src/Build/Globbing/MSBuildGlobWithGaps.cs
  src/Build/Globbing/Visitor/GlobVisitor.cs
Labels: performance, merge-when-branch-open

#7039 Update mac version for CI
  .vsts-dotnet-ci.yml
Labels: merge-when-branch-open

#6895 RAR: Log full path of bad-image failures
  src/Tasks/AssemblyDependency/Resolver.cs
  src/Tasks/Resources/Strings.resx
  src/Tasks/Resources/xlf/Strings.cs.xlf
  src/Tasks/Resources/xlf/Strings.de.xlf
  src/Tasks/Resources/xlf/Strings.es.xlf
  src/Tasks/Resources/xlf/Strings.fr.xlf
  src/Tasks/Resources/xlf/Strings.it.xlf
  src/Tasks/Resources/xlf/Strings.ja.xlf
  src/Tasks/Resources/xlf/Strings.ko.xlf
  src/Tasks/Resources/xlf/Strings.pl.xlf
  src/Tasks/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Resources/xlf/Strings.ru.xlf
  src/Tasks/Resources/xlf/Strings.tr.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open

#7018 Switch to PublicApiAnalyzers
  .editorconfig
  documentation/release.md
  eng/Packages.props
  eng/Version.Details.xml
  eng/Versions.props
  ref/ExcludeAPIList.txt
  ref/ExcludeAttributeList.txt
  ref/LicenseHeader.txt
  ref/Microsoft.Build.Conversion.Core/net/Microsoft.Build.Conversion.Core.cs
  ref/Microsoft.Build.Engine/net/Microsoft.Build.Engine.cs
  ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
  ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
  ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs
  ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs
  ref/Microsoft.Build/net/Microsoft.Build.cs
  ref/Microsoft.Build/netstandard/Microsoft.Build.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/PublicAPI/net/PublicAPI.Shipped.txt
  src/Build/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Build/PublicAPI/netstandard/PublicAPI.Shipped.txt
  src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Deprecated/Conversion/PublicAPI/net/PublicAPI.Shipped.txt
  src/Deprecated/Conversion/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Deprecated/Engine/PublicAPI/net/PublicAPI.Shipped.txt
  src/Deprecated/Engine/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Directory.Build.props
  src/Directory.Build.targets
  src/Framework/PublicAPI/net/PublicAPI.Shipped.txt
  src/Framework/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Framework/PublicAPI/netstandard/PublicAPI.Shipped.txt
  src/Framework/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/StringTools/InternableString.cs
  src/StringTools/PublicAPI/net/PublicAPI.Shipped.txt
  src/StringTools/PublicAPI/net/PublicAPI.Unshipped.txt
  src/StringTools/PublicAPI/net35/PublicAPI.Shipped.txt
  src/StringTools/PublicAPI/net35/PublicAPI.Unshipped.txt
  src/StringTools/PublicAPI/netstandard/PublicAPI.Shipped.txt
  src/StringTools/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/StringTools/StringTools.csproj
  src/StringTools/WeakStringCache.Locking.cs
  src/Tasks/PublicAPI/net/PublicAPI.Shipped.txt
  src/Tasks/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Tasks/PublicAPI/netstandard/PublicAPI.Shipped.txt
  src/Tasks/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Utilities/PublicAPI/net/PublicAPI.Shipped.txt
  src/Utilities/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Utilities/PublicAPI/netstandard/PublicAPI.Shipped.txt
  src/Utilities/PublicAPI/netstandard/PublicAPI.Unshipped.txt
Labels: Area: Our Own Build, merge-when-branch-open

#7038 Code cleanup: Remove references to FxCop
  src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj
  src/Build.UnitTests/BackEnd/TaskHost_Tests.cs
  src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
  src/Build/BackEnd/Components/Logging/EventSourceSink.cs
  src/Build/Construction/ProjectRootElement.cs
  src/Build/FxCopExclusions/Microsoft.Build.Suppressions.cs
  src/Build/Logging/FileLogger.cs
  src/Build/Microsoft.Build.csproj
  src/Deprecated/Conversion.UnitTests/XMakeConversionUnitTests.csproj
  src/Deprecated/Conversion/FxCopExclusions/Microsoft.Build.Conversion.Suppressions.cs
  src/Deprecated/Conversion/Microsoft.Build.Conversion.csproj
  src/Deprecated/Engine/Engine/BuildTask.cs
  src/Deprecated/Engine/Engine/EventSource.cs
  src/Deprecated/Engine/FxCopExclusions/Microsoft.Build.Engine.Suppressions.cs
  src/Deprecated/Engine/Logging/FileLogger.cs
  src/Deprecated/Engine/Microsoft.Build.Engine.csproj
  src/Deprecated/Engine/Properties/BuildProperty.cs
  src/Framework/FxCopExclusions/Microsoft.Build.Framework.Suppressions.cs
  src/MSBuild.UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj
  src/MSBuild/FxCopExclusions/MsBuild.Suppressions.cs
  src/MSBuild/MSBuild.csproj
  src/Shared/FxCopExclusions/Microsoft.Build.Shared.Suppressions.cs
  src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
  src/Tasks/FxCopExclusions/Microsoft.Build.Tasks.Suppressions.cs
  src/Tasks/GenerateResource.cs
  src/Tasks/Microsoft.Build.Tasks.csproj
  src/Utilities.UnitTests/Microsoft.Build.Utilities.UnitTests.csproj
  src/Utilities/FxCopExclusions/Microsoft.Build.Utilities.Suppressions.cs
  src/Utilities/Microsoft.Build.Utilities.csproj
  src/Utilities/ToolTask.cs
Labels: merge-when-branch-open

#7045 Ship System.ValueTuple.dll to VS
  src/Package/MSBuild.VSSetup/files.swr
Labels: merge-when-branch-open

#7059 Disable RestoreUseStaticGraphEvaluation for source-build
  eng/Build.props
Labels: merge-when-branch-open

#7003 Document MSBuildDebugEngine and other debugging doc improvements
  documentation/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild.md
  documentation/wiki/Building-Testing-and-Debugging-on-Full-Framework-MSBuild.md
  documentation/wiki/Building-Testing-and-Debugging-on-Mono-MSBuild.md
Labels: merge-when-branch-open

#7026 Optimize diag level for file logger and console logger
  src/Build.UnitTests/ConsoleLogger_Tests.cs
  src/Build.UnitTests/ConsoleOutputAlignerTests.cs
  src/Build/Logging/ParallelLogger/ConsoleOutputAligner.cs
  src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs
  src/Build/Microsoft.Build.csproj
Labels: performance, Performance-Scenario-Build, Area: Logging, merge-when-branch-open

#7042 Loosen version comparisons in loading assemblies
  src/Shared/CoreCLRAssemblyLoader.cs
  src/Shared/MSBuildLoadContext.cs
Labels: merge-when-branch-open

#7052 Remove closure allocation in CompositeGlob.IsMatch
  src/Build/Globbing/CompositeGlob.cs
  src/Build/Microsoft.Build.csproj
  src/Build/Utilities/ImmutableCollectionsExtensions.cs
Labels: merge-when-branch-open

#7048 Get Microsoft SDK paths from 32-bit registry
  src/MSBuild/app.amd64.config
  src/MSBuild/app.config
Labels: merge-when-branch-open

#7010 Remove locker object from LazyFormattedBuildEventArgs
  src/Framework/BuildEventArgs.cs
  src/Framework/LazyFormattedBuildEventArgs.cs
  src/Framework/ProjectFinishedEventArgs.cs
  src/Framework/ProjectStartedEventArgs.cs
  src/Framework/PropertyReassignmentEventArgs.cs
  src/Framework/PublicAPI/net/PublicAPI.Shipped.txt
  src/Framework/PublicAPI/netstandard/PublicAPI.Shipped.txt
  src/Framework/TargetFinishedEventArgs.cs
  src/Framework/TargetSkippedEventArgs.cs
  src/Framework/TargetStartedEventArgs.cs
  src/Framework/TaskFinishedEventArgs.cs
  src/Framework/TaskStartedEventArgs.cs
Labels: performance, merge-when-branch-open

#7046 Introduce Dependabot
  .github/dependabot.yml
  eng/Packages.props
  eng/Version.Details.xml
  eng/Versions.props
  eng/dependabot/Packages.props
  eng/dependabot/dependabot.csproj
Labels: merge-when-branch-open

#7008 Permit individually settable search paths
  documentation/wiki/ResolveAssemblyReference.md
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#7077 Update System.Text.Encodings.Web binding redirect
  src/MSBuild/app.amd64.config
  src/MSBuild/app.config
Labels: Partner request

#7082 Fixing bug detected by DDRIT
  src/Shared/BuildEnvironmentHelper.cs
Labels: merge-when-branch-open

#6812 Static graph doc clarifications
  documentation/specs/static-graph.md
Labels: merge-when-branch-open

#6974 Optimized immutable files up to date checks
  src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
  src/Build/Definition/ToolsetReader.cs
  src/Framework.UnitTests/FileClassifier_Tests.cs
  src/Framework/FileClassifier.cs
  src/Framework/ImmutableFilesTimestampCache.cs
  src/Framework/NativeMethods.cs
  src/Framework/Traits.cs
Labels: merge-when-branch-open

#7051 Al.exe finds the correct tool based on platform
  src/Tasks/Al.cs
  src/Tasks/Microsoft.Common.CurrentVersion.targets
  src/Tasks/SdkToolsPathUtility.cs
Labels: merge-when-branch-open, review-by-commit

#7056 Evaluator allocation optimization
  src/Build/Evaluation/Evaluator.cs
Labels: performance, merge-when-branch-open

#7080 Remove unused 'capacity' parameter for COW dictionaries
  src/Build/Collections/CopyOnWritePropertyDictionary.cs
  src/Build/Construction/ProjectTaskElement.cs
  src/Build/Instance/ProjectInstance.cs
  src/Build/Instance/ProjectItemDefinitionInstance.cs
  src/Build/Instance/ProjectItemInstance.cs
  src/Build/Instance/ProjectTaskInstance.cs
  src/Shared/CopyOnWriteDictionary.cs
Labels: merge-when-branch-open

#7087 Fixed test that is dependent on current regional settings
  src/Build.UnitTests/Evaluation/Expander_Tests.cs
Labels: merge-when-branch-open

#7089 Add NoWarn to .xsd
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Labels: merge-when-branch-open

#7054 Replace O(N^2) with O(N)
  src/Deprecated/Engine/Caching/BuildItemCacheEntry.cs
Labels: performance, merge-when-branch-open

#6839 Fix #6750 `SdkResultItem` equality
  src/Build.UnitTests/BackEnd/SdkResultItemComparison_Tests.cs
  src/Framework/Sdk/SdkResultItem.cs
Labels: merge-when-branch-open

#7075 Move reference assemblies into obj (again)
  documentation/wiki/ChangeWaves.md
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open
