Repository dotnet/msbuild, pull requests merged in 2021-03, with the labels that each got.

#6110 Fix cache exception handling
  src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Shared/UnitTests/ObjectModelHelpers.cs
Labels: merge-when-branch-open

#6128 Optimize property expansion
  src/Build/Evaluation/Expander.cs
  src/Shared/ErrorUtilities.cs
  src/Shared/FileUtilities.cs
  src/StringTools/SpanBasedStringBuilder.cs
Labels: merge-when-branch-open

#6151 Optimize glob evaluation
  src/Build.UnitTests/Definition/ProjectEvaluationContext_Tests.cs
  src/Build/Evaluation/Context/EvaluationContext.cs
  src/Build/Globbing/MSBuildGlob.cs
  src/Build/Utilities/FileSpecMatchTester.cs
  src/Shared/FileMatcher.cs
  src/Shared/UnitTests/FileMatcher_Tests.cs
  src/Tasks/Unzip.cs
Labels: merge-when-branch-open

#6214 jnm2.ReferenceAssemblies.net35 should be a private dependency
  src/MSBuildTaskHost/MSBuildTaskHost.csproj
  src/StringTools/StringTools.csproj
Labels: merge-when-branch-open

#6171 Permit direct access to a SolutionFilterName property Fixes #6162
  src/Build/Construction/Solution/SolutionFile.cs
  src/Build/Construction/Solution/SolutionProjectGenerator.cs
  src/Deprecated/Engine/Solution/SolutionWrapperProject.cs
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#6188 Permit specifying that we should use utf-8 in ToolTask
  ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
  ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
  ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs
  ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs
  src/Tasks/Exec.cs
  src/Utilities/ToolTask.cs
Labels: Localization, Partner request, merge-when-branch-open

#6169 add live.msbuildlog.com to binary log doc
  documentation/wiki/Providing-Binary-Logs.md
Labels: Documentation, merge-when-branch-open

#6155 Introduce TaskParameterEventArgs
  ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
  src/Build.UnitTests/BackEnd/EventSourceSink_Tests.cs
  src/Build.UnitTests/BackEnd/NodePackets_Tests.cs
  src/Build.UnitTests/BinaryLogger_Tests.cs
  src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
  src/Build.UnitTests/ConfigureableForwardingLogger_Tests.cs
  src/Build/BackEnd/Components/Logging/LoggingService.cs
  src/Build/BackEnd/Components/Logging/TargetLoggingContext.cs
  src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs
  src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupLoggingHelper.cs
  src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
  src/Build/Collections/ArrayDictionary.cs
  src/Build/Instance/ProjectItemInstance.cs
  src/Build/Logging/BinaryLogger/BinaryLogRecordKind.cs
  src/Build/Logging/BinaryLogger/BinaryLogReplayEventSource.cs
  src/Build/Logging/BinaryLogger/BinaryLogger.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
  src/Build/Microsoft.Build.csproj
  src/Framework/BuildEventArgs.cs
  src/Framework/IMetadataContainer.cs
  src/Framework/ITaskItemExtensions.cs
  src/Framework/Microsoft.Build.Framework.csproj
  src/Framework/TaskItemData.cs
  src/Framework/TaskParameterEventArgs.cs
  src/MSBuildTaskHost/MSBuildTaskHost.csproj
  src/Shared/BinaryReaderExtensions.cs
  src/Shared/BinaryWriterExtensions.cs
  src/Shared/LogMessagePacketBase.cs
  src/Shared/TaskParameter.cs
  src/Utilities/TaskItem.cs
Labels: Area: Logging, Performance-Scenario-Build, merge-when-branch-open, performance

#6159 Fixup whitespace and new lines in Common props, targets and tasks
  src/Tasks/Microsoft.CSharp.CrossTargeting.targets
  src/Tasks/Microsoft.CSharp.CurrentVersion.targets
  src/Tasks/Microsoft.CSharp.targets
  src/Tasks/Microsoft.Common.CrossTargeting.targets
  src/Tasks/Microsoft.Common.CurrentVersion.targets
  src/Tasks/Microsoft.Common.overridetasks
  src/Tasks/Microsoft.Common.props
  src/Tasks/Microsoft.Common.targets
  src/Tasks/Microsoft.Common.tasks
  src/Tasks/Microsoft.Data.Entity.targets
  src/Tasks/Microsoft.Managed.Before.targets
  src/Tasks/Microsoft.NET.props
  src/Tasks/Microsoft.NETFramework.CurrentVersion.props
  src/Tasks/Microsoft.NETFramework.CurrentVersion.targets
  src/Tasks/Microsoft.NETFramework.props
  src/Tasks/Microsoft.NETFramework.targets
  src/Tasks/Microsoft.ServiceModel.targets
  src/Tasks/Microsoft.VisualBasic.CrossTargeting.targets
  src/Tasks/Microsoft.VisualBasic.CurrentVersion.targets
  src/Tasks/Microsoft.VisualBasic.targets
  src/Tasks/Microsoft.WinFx.targets
  src/Tasks/Microsoft.WorkflowBuildExtensions.targets
  src/Tasks/Microsoft.Xaml.targets
  src/Tasks/Workflow.VisualBasic.targets
  src/Tasks/Workflow.targets
Labels: merge-when-branch-open

#6201 Make CacheResult members public
  ref/Microsoft.Build/net/Microsoft.Build.cs
  ref/Microsoft.Build/netstandard/Microsoft.Build.cs
  src/Build/BackEnd/Components/ProjectCache/CacheResult.cs
  src/Build/BackEnd/Components/ProjectCache/ProjectCachePluginBase.cs
Labels: merge-when-branch-open

#6234 Pass SolutionFilterName as a property
  src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
  src/Build/Construction/Solution/SolutionProjectGenerator.cs
Labels: bug, merge-when-branch-open, regression

#6204 Fixes for big-endian systems
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
  src/Shared/MSBuildNameIgnoreCaseComparer.cs
Labels: merge-when-branch-open

#6158 Remove unused files from the repo
  CompatBaseline.txt
  RunApiPort.bat
  netci.groovy
  runApiCompat.bat
  src/Tasks.UnitTests2/AssemblyIdentityTest.cs
  src/Tasks.UnitTests2/AuthoringTests.txt
  src/Tasks.UnitTests2/Properties/AssemblyInfo.cs
  src/Tasks.UnitTests2/UtilTest.cs
  src/Tasks.UnitTests2/XMakeTasksUnitTests.csproj
  src/Tasks/DefaultTasks.bat
Labels: merge-when-branch-open

#6205 General "switch" description in help message - update for "--" indicator
  src/MSBuild/Resources/Strings.resx
  src/MSBuild/Resources/xlf/Strings.cs.xlf
  src/MSBuild/Resources/xlf/Strings.de.xlf
  src/MSBuild/Resources/xlf/Strings.en.xlf
  src/MSBuild/Resources/xlf/Strings.es.xlf
  src/MSBuild/Resources/xlf/Strings.fr.xlf
  src/MSBuild/Resources/xlf/Strings.it.xlf
  src/MSBuild/Resources/xlf/Strings.ja.xlf
  src/MSBuild/Resources/xlf/Strings.ko.xlf
  src/MSBuild/Resources/xlf/Strings.pl.xlf
  src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
  src/MSBuild/Resources/xlf/Strings.ru.xlf
  src/MSBuild/Resources/xlf/Strings.tr.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open

#6227 Optimize EngineFileUtilities.GetFileList
  src/Build/Evaluation/ItemSpec.cs
  src/Build/Utilities/EngineFileUtilities.cs
  src/Shared/EscapingUtilities.cs
  src/Shared/UnitTests/EscapingUtilities_Tests.cs
Labels: merge-when-branch-open

#6220 Toolset configuration net5.0
  eng/Packages.props
  src/Build.UnitTests/Definition/ToolsetConfigurationReader_Tests.cs
  src/Build.UnitTests/Definition/ToolsetReader_Tests.cs
  src/Build.UnitTests/Evaluation/ImportFromMSBuildExtensionsPath_Tests.cs
  src/Build.UnitTests/Evaluation/ToolsetConfigurationNet5_Tests.cs
  src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
  src/Build/Definition/ProjectCollection.cs
  src/Build/Definition/ToolsetConfigurationReader.cs
  src/Build/Definition/ToolsetReader.cs
  src/Build/Definition/ToolsetRegistryReader.cs
  src/Build/Microsoft.Build.csproj
  src/Build/Utilities/RegistryKeyWrapper.cs
  src/MSBuild/MSBuild.csproj
  src/MSBuild/XMake.cs
  src/Shared/FrameworkLocationHelper.cs
  src/Shared/ToolsetElement.cs
  src/Tasks.UnitTests/Copy_Tests.cs
  src/Utilities/Microsoft.Build.Utilities.csproj
Labels: merge-when-branch-open

#6207 Pass x64 architecture to al.exe when targeting x64
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#6238 Handle unsupported paths in ProjectInSolution.AbsolutePath
  src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
  src/Build/Construction/Solution/ProjectInSolution.cs
Labels: merge-when-branch-open, regression

#6243 Fix rar cache incompatibility warning message (#6242)
  src/Tasks.UnitTests/ResourceHandling/GenerateResourceOutOfProc_Tests.cs
  src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs
  src/Tasks/Microsoft.Common.CurrentVersion.targets
  src/Tasks/StateFileBase.cs
  src/Tasks/SystemState.cs
Labels: merge-when-branch-open

#6246 Remove inheritdoc
  src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs
Labels: merge-when-branch-open

#6222 Ignore invalid import when expression empty
  src/Build.OM.UnitTests/Definition/Project_Tests.cs
  src/Build/Evaluation/Evaluator.cs
  src/Build/Resources/Strings.resx
  src/Build/Resources/xlf/Strings.cs.xlf
  src/Build/Resources/xlf/Strings.de.xlf
  src/Build/Resources/xlf/Strings.en.xlf
  src/Build/Resources/xlf/Strings.es.xlf
  src/Build/Resources/xlf/Strings.fr.xlf
  src/Build/Resources/xlf/Strings.it.xlf
  src/Build/Resources/xlf/Strings.ja.xlf
  src/Build/Resources/xlf/Strings.ko.xlf
  src/Build/Resources/xlf/Strings.pl.xlf
  src/Build/Resources/xlf/Strings.pt-BR.xlf
  src/Build/Resources/xlf/Strings.ru.xlf
  src/Build/Resources/xlf/Strings.tr.xlf
  src/Build/Resources/xlf/Strings.zh-Hans.xlf
  src/Build/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open

#6174 Tasks `Log.HasLoggedError` now respects `MSBuildWarningsAsErrors`
  ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs
  ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs
  src/Build.UnitTests/BackEnd/CustomLogAndReturnTask.cs
  src/Build.UnitTests/BackEnd/MockLoggingService.cs
  src/Build.UnitTests/BackEnd/TaskHostConfiguration_Tests.cs
  src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs
  src/Build/BackEnd/Components/Logging/ILoggingService.cs
  src/Build/BackEnd/Components/Logging/LoggingService.cs
  src/Build/BackEnd/Components/Logging/TaskLoggingContext.cs
  src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs
  src/Build/Instance/TaskFactories/TaskHostTask.cs
  src/Framework/IBuildEngine8.cs
  src/MSBuild/OutOfProcTaskHostNode.cs
  src/Shared/BinaryTranslator.cs
  src/Shared/ITranslator.cs
  src/Shared/TaskHostConfiguration.cs
  src/Shared/TaskLoggingHelper.cs
  src/Utilities/Task.cs
Labels: merge-when-branch-open

#6245 Revert broken code cleanup
  src/Tasks.UnitTests/OutputPathTests.cs
  src/Tasks/Microsoft.Common.CrossTargeting.targets
  src/Tasks/Microsoft.Common.CurrentVersion.targets
  src/Tasks/Microsoft.Common.props
  src/Tasks/Microsoft.Common.targets
Labels: merge-when-branch-open

#6240 Provide more information with BadImageReferenceException
  src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
Labels: merge-when-branch-open

#6107 Pre cache
  src/Tasks.UnitTests/RARPrecomputedCache_Tests.cs
  src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
  src/Tasks/Microsoft.Common.CurrentVersion.targets
  src/Tasks/Resources/Strings.resx
  src/Tasks/Resources/xlf/Strings.cs.xlf
  src/Tasks/Resources/xlf/Strings.de.xlf
  src/Tasks/Resources/xlf/Strings.en.xlf
  src/Tasks/Resources/xlf/Strings.es.xlf
  src/Tasks/Resources/xlf/Strings.fr.xlf
  src/Tasks/Resources/xlf/Strings.it.xlf
  src/Tasks/Resources/xlf/Strings.ja.xlf
  src/Tasks/Resources/xlf/Strings.ko.xlf
  src/Tasks/Resources/xlf/Strings.pl.xlf
  src/Tasks/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Resources/xlf/Strings.ru.xlf
  src/Tasks/Resources/xlf/Strings.tr.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/SystemState.cs
Labels: merge-when-branch-open

#6273 Handle unsupported paths in ProjectInSolution.AbsolutePath (#6238)
  src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
  src/Build/Construction/Solution/ProjectInSolution.cs
Labels: Servicing-approved

#6278 Support runtime-specific SDK resolver test hook
  src/Build/BackEnd/Components/SdkResolution/SdkResolverLoader.cs
Labels: merge-when-branch-open

#6173 Basic doc on msbuild and the gac
  documentation/wiki/UnGAC.md
Labels: Documentation

#6293 Remove unused GetAllGlobs override in ProjectLink
  ref/Microsoft.Build/net/Microsoft.Build.cs
  ref/Microsoft.Build/netstandard/Microsoft.Build.cs
  src/Build.OM.UnitTests/ObjectModelRemoting/RemoteProjectsProviderMock/EvaluationLinkMocks/MockProjectLink.cs
  src/Build/Definition/Project.cs
  src/Build/ObjectModelRemoting/DefinitionObjectsLinks/ProjectLink.cs
Labels: exp-branch

#5859 Introduce cross-process resource management for tasks
  documentation/specs/resource-management.md
  ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs
  ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs
  src/Build.UnitTests/BackEnd/BuildRequestEngine_Tests.cs
  src/Build.UnitTests/BackEnd/TargetBuilder_Tests.cs
  src/Build.UnitTests/BackEnd/TargetEntry_Tests.cs
  src/Build.UnitTests/BackEnd/TaskBuilder_Tests.cs
  src/Build.UnitTests/BackEnd/TaskHost_Tests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs
  src/Build/BackEnd/Components/BuildRequestEngine/IBuildRequestEngine.cs
  src/Build/BackEnd/Components/RequestBuilder/IRequestBuilder.cs
  src/Build/BackEnd/Components/RequestBuilder/IRequestBuilderCallback.cs
  src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
  src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs
  src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
  src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs
  src/Build/BackEnd/Components/Scheduler/IScheduler.cs
  src/Build/BackEnd/Components/Scheduler/SchedulableRequest.cs
  src/Build/BackEnd/Components/Scheduler/Scheduler.cs
  src/Build/BackEnd/Components/Scheduler/SchedulingData.cs
  src/Build/BackEnd/Node/InProcNode.cs
  src/Build/BackEnd/Node/NodeConfiguration.cs
  src/Build/BackEnd/Node/OutOfProcNode.cs
  src/Build/BackEnd/Shared/ResourceRequest.cs
  src/Build/BackEnd/Shared/ResourceResponse.cs
  src/Build/Microsoft.Build.csproj
  src/Build/Resources/Strings.resx
  src/Build/Resources/xlf/Strings.cs.xlf
  src/Build/Resources/xlf/Strings.de.xlf
  src/Build/Resources/xlf/Strings.en.xlf
  src/Build/Resources/xlf/Strings.es.xlf
  src/Build/Resources/xlf/Strings.fr.xlf
  src/Build/Resources/xlf/Strings.it.xlf
  src/Build/Resources/xlf/Strings.ja.xlf
  src/Build/Resources/xlf/Strings.ko.xlf
  src/Build/Resources/xlf/Strings.pl.xlf
  src/Build/Resources/xlf/Strings.pt-BR.xlf
  src/Build/Resources/xlf/Strings.ru.xlf
  src/Build/Resources/xlf/Strings.tr.xlf
  src/Build/Resources/xlf/Strings.zh-Hans.xlf
  src/Build/Resources/xlf/Strings.zh-Hant.xlf
  src/Framework/IBuildEngine8.cs
  src/Framework/IBuildEngine9.cs
  src/MSBuild/OutOfProcTaskHostNode.cs
  src/Shared/INodePacket.cs
  src/Tasks.UnitTests/ResourceManagement_Tests.cs
  src/Utilities/Task.cs
Labels: merge-when-branch-open

#6301 Fix Bootstrap Build
  src/Build/Utilities/NuGetFrameworkWrapper.cs
Labels: merge-when-branch-open

#6286 Loc update
  src/Build/Resources/xlf/Strings.cs.xlf
  src/Build/Resources/xlf/Strings.de.xlf
  src/Build/Resources/xlf/Strings.es.xlf
  src/Build/Resources/xlf/Strings.fr.xlf
  src/Build/Resources/xlf/Strings.it.xlf
  src/Build/Resources/xlf/Strings.ja.xlf
  src/Build/Resources/xlf/Strings.ko.xlf
  src/Build/Resources/xlf/Strings.pl.xlf
  src/Build/Resources/xlf/Strings.pt-BR.xlf
  src/Build/Resources/xlf/Strings.ru.xlf
  src/Build/Resources/xlf/Strings.tr.xlf
  src/Build/Resources/xlf/Strings.zh-Hans.xlf
  src/Build/Resources/xlf/Strings.zh-Hant.xlf
  src/Deprecated/Engine/Resources/xlf/Strings.ru.xlf
  src/MSBuild/Resources/xlf/Strings.cs.xlf
  src/MSBuild/Resources/xlf/Strings.de.xlf
  src/MSBuild/Resources/xlf/Strings.es.xlf
  src/MSBuild/Resources/xlf/Strings.fr.xlf
  src/MSBuild/Resources/xlf/Strings.it.xlf
  src/MSBuild/Resources/xlf/Strings.ja.xlf
  src/MSBuild/Resources/xlf/Strings.ko.xlf
  src/MSBuild/Resources/xlf/Strings.pl.xlf
  src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
  src/MSBuild/Resources/xlf/Strings.ru.xlf
  src/MSBuild/Resources/xlf/Strings.tr.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Resources/xlf/Strings.cs.xlf
  src/Tasks/Resources/xlf/Strings.de.xlf
  src/Tasks/Resources/xlf/Strings.es.xlf
  src/Tasks/Resources/xlf/Strings.fr.xlf
  src/Tasks/Resources/xlf/Strings.it.xlf
  src/Tasks/Resources/xlf/Strings.ja.xlf
  src/Tasks/Resources/xlf/Strings.ko.xlf
  src/Tasks/Resources/xlf/Strings.pl.xlf
  src/Tasks/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Resources/xlf/Strings.ru.xlf
  src/Tasks/Resources/xlf/Strings.tr.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open

#6282 Remove ContainsKey where relevant
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/BuildManager/LegacyThreadingData.cs
  src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEntry.cs
  src/Build/BackEnd/Components/Caching/ResultsCache.cs
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs
  src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs
  src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/MSBuild.cs
  src/Build/BackEnd/Components/RequestBuilder/Lookup.cs
  src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs
  src/Build/BackEnd/Components/Scheduler/SchedulableRequest.cs
  src/Build/BackEnd/Components/Scheduler/SchedulingData.cs
  src/Build/BackEnd/Shared/BuildResult.cs
  src/Build/Construction/Solution/SolutionFile.cs
  src/Build/Construction/Solution/SolutionProjectGenerator.cs
  src/Build/Definition/Project.cs
  src/Build/Definition/ProjectCollection.cs
  src/Build/Evaluation/Evaluator.cs
  src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs
  src/Build/Graph/GraphBuilder.cs
  src/Build/Instance/HostServices.cs
  src/Build/Instance/ProjectInstance.cs
  src/Build/Instance/TaskFactories/TaskHostTask.cs
  src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs
  src/Build/Logging/ParallelLogger/ParallelLoggerHelpers.cs
  src/Shared/CommunicationsUtilities.cs
  src/Shared/FrameworkLocationHelper.cs
  src/Shared/NodePacketFactory.cs
  src/Shared/VersionUtilities.cs
  src/Tasks/AssemblyDependency/GlobalAssemblyCache.cs
  src/Tasks/AssemblyDependency/Reference.cs
  src/Tasks/AssemblyDependency/ReferenceTable.cs
  src/Tasks/GenerateBootstrapper.cs
  src/Tasks/InstalledSDKResolver.cs
  src/Tasks/MSBuild.cs
  src/Tasks/ManifestUtil/ApplicationManifest.cs
  src/Tasks/ResolveSDKReference.cs
  src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs
  src/Tasks/XamlTaskFactory/RelationsParser.cs
  src/Tasks/XamlTaskFactory/TaskGenerator.cs
  src/Tasks/XamlTaskFactory/XamlDataDrivenToolTask.cs
  src/Utilities/MuxLogger.cs
  src/Utilities/TrackedDependencies/CanonicalTrackedInputFiles.cs
  src/Utilities/TrackedDependencies/CanonicalTrackedOutputFiles.cs
  src/Utilities/TrackedDependencies/DependencyTableCache.cs
  src/Utilities/TrackedDependencies/FlatTrackingData.cs
Labels: merge-when-branch-open

#6270 Throw BadImageFormatException when missing PE metadata
  src/Tasks/AssemblyDependency/AssemblyInformation.cs
Labels: merge-when-branch-open

#6308 Properly Consider WarningsAsMessages In TaskLoggingHelper's `HasLoggedErrors`
  src/Build.UnitTests/BackEnd/MockLoggingService.cs
  src/Build.UnitTests/BackEnd/TaskHostConfiguration_Tests.cs
  src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs
  src/Build/BackEnd/Components/Logging/ILoggingService.cs
  src/Build/BackEnd/Components/Logging/LoggingService.cs
  src/Build/BackEnd/Components/Logging/TaskLoggingContext.cs
  src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs
  src/Build/Instance/TaskFactories/TaskHostTask.cs
  src/MSBuild/OutOfProcTaskHostNode.cs
  src/Shared/TaskHostConfiguration.cs
Labels: merge-when-branch-open
