Repository dotnet/msbuild, pull requests merged in 2021-04, with the labels that each got.

#6287 Log properties and items on ProjectEvaluationFinished
  eng/Packages.props
  ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs
  ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs
  src/Build.UnitTests/BackEnd/MockLoggingService.cs
  src/Build.UnitTests/BackEnd/NodePackets_Tests.cs
  src/Build.UnitTests/BackEnd/TranslationHelpers.cs
  src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
  src/Build.UnitTests/ConsoleLogger_Tests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Components/Logging/EvaluationLoggingContext.cs
  src/Build/BackEnd/Components/Logging/EventSourceSink.cs
  src/Build/BackEnd/Components/Logging/ILoggingService.cs
  src/Build/BackEnd/Components/Logging/LoggingService.cs
  src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs
  src/Build/BackEnd/Components/Logging/ProjectLoggingContext.cs
  src/Build/BackEnd/Node/LoggingNodeConfiguration.cs
  src/Build/BackEnd/Node/OutOfProcNode.cs
  src/Build/Collections/ArrayDictionary.cs
  src/Build/Collections/ItemDictionary.cs
  src/Build/Collections/PropertyDictionary.cs
  src/Build/Definition/ProjectCollection.cs
  src/Build/Evaluation/Evaluator.cs
  src/Build/Instance/ProjectInstance.cs
  src/Build/Logging/BaseConsoleLogger.cs
  src/Build/Logging/BinaryLogger/BinaryLogger.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
  src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs
  src/Build/Logging/SerialConsoleLogger.cs
  src/Build/Utilities/Utilities.cs
  src/Framework/BuildEventArgs.cs
  src/Framework/IEventSource4.cs
  src/Framework/ProjectEvaluationFinishedEventArgs.cs
  src/Framework/ProjectEvaluationStartedEventArgs.cs
  src/MSBuild/MSBuild.csproj
  src/Shared/LogMessagePacketBase.cs
  src/Shared/Traits.cs
  src/Utilities/MuxLogger.cs
Labels: merge-when-branch-open

#6321 branding update
  eng/Versions.props
  src/MSBuild/app.amd64.config
  src/MSBuild/app.config
Labels: merge-when-branch-open

#6284 Improve doc comments
  src/Tasks/ManifestUtil/ApplicationManifest.cs
Labels: merge-when-branch-open

#6237 Allow Custom CopyToOutputDirectory Location With TargetPath
  documentation/wiki/ChangeWaves.md
  src/Shared/Constants.cs
  src/Tasks.UnitTests/AssignTargetPath_Tests.cs
  src/Tasks/AssignTargetPath.cs
Labels: changewave 16.10, merge-when-branch-open

#6285 Allow parameter type name to be specified for WriteCodeFragment task
  src/Tasks.UnitTests/WriteCodeFragment_Tests.cs
  src/Tasks/Resources/Strings.resx
  src/Tasks/Resources/xlf/Strings.cs.xlf
  src/Tasks/Resources/xlf/Strings.de.xlf
  src/Tasks/Resources/xlf/Strings.en.xlf
  src/Tasks/Resources/xlf/Strings.es.xlf
  src/Tasks/Resources/xlf/Strings.fr.xlf
  src/Tasks/Resources/xlf/Strings.it.xlf
  src/Tasks/Resources/xlf/Strings.ja.xlf
  src/Tasks/Resources/xlf/Strings.ko.xlf
  src/Tasks/Resources/xlf/Strings.pl.xlf
  src/Tasks/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Resources/xlf/Strings.ru.xlf
  src/Tasks/Resources/xlf/Strings.tr.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/WriteCodeFragment.cs
Labels: merge-when-branch-open

#6312 Fail Restore when an SDK is unresolved or entry target does not exist
  ref/Microsoft.Build/net/Microsoft.Build.cs
  ref/Microsoft.Build/netstandard/Microsoft.Build.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/BuildManager/BuildRequestData.cs
  src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs
  src/Build/BackEnd/Shared/BuildRequestConfiguration.cs
  src/Build/Definition/ProjectLoadSettings.cs
  src/Build/Evaluation/Evaluator.cs
  src/MSBuild.UnitTests/XMake_Tests.cs
  src/MSBuild/XMake.cs
Labels: merge-when-branch-open

#6223 Allow users that have certain special characters in their username to build successfully when using exec
  documentation/wiki/ChangeWaves.md
  src/Shared/TempFileUtilities.cs
  src/Shared/UnitTests/TestEnvironment.cs
  src/Tasks.UnitTests/Exec_Tests.cs
  src/Tasks/Exec.cs
Labels: changewave 16.10, merge-when-branch-open

#6342 Bring back ProjectStarted.GlobalProperties
  src/Build/BackEnd/Components/Logging/LoggingService.cs
  src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs
  src/Build/Evaluation/Evaluator.cs
Labels: merge-when-branch-open

#6335 Fix some URLs from Microsoft/msbuild -> dotnet/msbuild
  Directory.Build.props
  README.md
  documentation/ProjectReference-Protocol.md
  documentation/WhenGlobbingReturnsOriginalFilespec.md
  documentation/assigning-msb-error-code.md
  documentation/specs/static-graph-implementation-details.md
  documentation/wiki/Binary-Log.md
  documentation/wiki/Building-Testing-and-Debugging-on-Full-Framework-MSBuild.md
  documentation/wiki/Interactions-with-the-internal-repository.md
  documentation/wiki/ResolveAssemblyReference.md
  documentation/wiki/Something's-wrong-in-my-build.md
  documentation/wiki/UnGAC.md
  src/MSBuild/Resources/Strings.resx
  src/MSBuild/Resources/xlf/Strings.cs.xlf
  src/MSBuild/Resources/xlf/Strings.de.xlf
  src/MSBuild/Resources/xlf/Strings.en.xlf
  src/MSBuild/Resources/xlf/Strings.es.xlf
  src/MSBuild/Resources/xlf/Strings.fr.xlf
  src/MSBuild/Resources/xlf/Strings.it.xlf
  src/MSBuild/Resources/xlf/Strings.ja.xlf
  src/MSBuild/Resources/xlf/Strings.ko.xlf
  src/MSBuild/Resources/xlf/Strings.pl.xlf
  src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
  src/MSBuild/Resources/xlf/Strings.ru.xlf
  src/MSBuild/Resources/xlf/Strings.tr.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open

#6346 Permit comments and trailing commas in solution filter files
  src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
  src/Build/Construction/Solution/SolutionFile.cs
Labels: merge-when-branch-open

#6274 Opt Into Perf Logging
  eng/cibuild_bootstrapped_msbuild.ps1
  eng/cibuild_bootstrapped_msbuild.sh
  src/MSBuild.UnitTests/PerfLog_Tests.cs
  src/MSBuild/PerformanceLogEventListener.cs
  src/Shared/UnitTests/TestAssemblyInfo.cs
Labels: merge-when-branch-open

#6326 Miscellaneous logging improvements
  ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
  src/Build.UnitTests/BackEnd/MockLoggingService.cs
  src/Build.UnitTests/BackEnd/TargetBuilder_Tests.cs
  src/Build.UnitTests/BinaryLogger_Tests.cs
  src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
  src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs
  src/Build/BackEnd/Components/Logging/ILoggingService.cs
  src/Build/BackEnd/Components/Logging/LoggingContext.cs
  src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs
  src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupLoggingHelper.cs
  src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs
  src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs
  src/Build/BackEnd/Components/RequestBuilder/TargetUpToDateChecker.cs
  src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
  src/Build/Evaluation/Evaluator.cs
  src/Build/Evaluation/PropertyTrackingEvaluatorDataWrapper.cs
  src/Build/Logging/BaseConsoleLogger.cs
  src/Build/Logging/BinaryLogger/BinaryLogger.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsFieldFlags.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsFields.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
  src/Framework/BuildEventArgs.cs
  src/Framework/BuildMessageEventArgs.cs
  src/Framework/BuildStatusEventArgs.cs
  src/Framework/LazyFormattedBuildEventArgs.cs
  src/Framework/ProjectFinishedEventArgs.cs
  src/Framework/ProjectImportedEventArgs.cs
  src/Framework/ProjectStartedEventArgs.cs
  src/Framework/PropertyReassignmentEventArgs.cs
  src/Framework/TargetFinishedEventArgs.cs
  src/Framework/TargetSkippedEventArgs.cs
  src/Framework/TargetStartedEventArgs.cs
  src/Framework/TaskCommandLineEventArgs.cs
  src/Framework/TaskFinishedEventArgs.cs
  src/Framework/TaskParameterEventArgs.cs
  src/Framework/TaskStartedEventArgs.cs
  src/Framework/TelemetryEventArgs.cs
  src/Shared/LogMessagePacketBase.cs
  src/Shared/TaskLoggingHelper.cs
  src/Shared/UnitTests/EngineTestEnvironment.cs
  src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
  src/Tasks/Copy.cs
Labels: Area: Logging, Performance-Scenario-Build, Task: Resolve Assembly References (RAR), merge-when-branch-open, performance

#6338 Allow turning detailed summary off
  src/Build/BackEnd/Components/Scheduler/IScheduler.cs
  src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
  src/MSBuild/CommandLineSwitches.cs
  src/MSBuild/Resources/Strings.resx
  src/MSBuild/Resources/xlf/Strings.cs.xlf
  src/MSBuild/Resources/xlf/Strings.de.xlf
  src/MSBuild/Resources/xlf/Strings.en.xlf
  src/MSBuild/Resources/xlf/Strings.es.xlf
  src/MSBuild/Resources/xlf/Strings.fr.xlf
  src/MSBuild/Resources/xlf/Strings.it.xlf
  src/MSBuild/Resources/xlf/Strings.ja.xlf
  src/MSBuild/Resources/xlf/Strings.ko.xlf
  src/MSBuild/Resources/xlf/Strings.pl.xlf
  src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
  src/MSBuild/Resources/xlf/Strings.ru.xlf
  src/MSBuild/Resources/xlf/Strings.tr.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
  src/MSBuild/XMake.cs
Labels: merge-when-branch-open

#6336 Make GenerateResource look up resgen.exe in 10.0 SDK
  ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs
  ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs
  src/Shared/FrameworkLocationHelper.cs
  src/Tasks.UnitTests/ResourceHandling/GenerateResourceOutOfProc_Tests.cs
  src/Tasks/GenerateResource.cs
  src/Utilities/ToolLocationHelper.cs
Labels: merge-when-branch-open

#6339 Add support for embedding arbitrary files into binlog
  src/Build/Logging/BinaryLogger/BinaryLogger.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
  src/Shared/Constants.cs
Labels: merge-when-branch-open

#6337 Fix TasksCanAddRecursiveDirBuiltInMetadata()
  src/Build.UnitTests/BackEnd/TaskBuilder_Tests.cs
Labels: merge-when-branch-open

#6332 Use powershell sleep in unit tests
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
  src/Shared/ProcessExtensions.cs
  src/Utilities.UnitTests/ProcessExtensions_Tests.cs
Labels: merge-when-branch-open

#6363 Remove SolutionFilterName support
  src/Build/Construction/Solution/SolutionFile.cs
  src/Build/Construction/Solution/SolutionProjectGenerator.cs
  src/Deprecated/Engine/Solution/SolutionWrapperProject.cs
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#6365 Enable FindInvalidProjectReferences for .NET Core
  ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
  src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
  src/Tasks/Microsoft.Build.Tasks.csproj
Labels: merge-when-branch-open

#6345 Fix project cache plugin exception handling
  src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
Labels: merge-when-branch-open

#6372 Changewave 16.10 for restore failures
  documentation/wiki/ChangeWaves.md
  src/Build/BackEnd/Shared/BuildRequestConfiguration.cs
  src/MSBuild.UnitTests/XMake_Tests.cs
  src/MSBuild/XMake.cs
Labels: merge-when-branch-open

#6334 Add binding redirects for all assemblies redistributed by MSBuild
  eng/Packages.props
  src/MSBuild/app.amd64.config
  src/MSBuild/app.config
Labels: merge-when-branch-open

#6232 Ignore comments and whitespace when parsing read-only XML files
  src/Build/Xml/XmlReaderExtension.cs
Labels: merge-when-branch-open

#6382 Snapshot Items of TaskParameters from another AppDomain
  src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupLoggingHelper.cs
  src/Build/Instance/ProjectItemInstance.cs
  src/Framework/TaskItemData.cs
  src/Shared/TaskParameter.cs
  src/Utilities/TaskItem.cs
Labels: merge-when-branch-open
