Repository dotnet/msbuild, pull requests merged in 2021-08, with the labels that each got.

#6703 Update description about transitive copying
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#6381 Optimize logging by moving message importance checks earlier
  eng/build.ps1
  ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs
  ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs
  src/Build.UnitTests/BackEnd/LoggingService_Tests.cs
  src/Build.UnitTests/BackEnd/MockLoggingService.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Components/Logging/ILoggingService.cs
  src/Build/BackEnd/Components/Logging/LoggingService.cs
  src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs
  src/Build/BackEnd/Components/Scheduler/Scheduler.cs
  src/Build/Definition/ProjectCollection.cs
  src/Build/Logging/BaseConsoleLogger.cs
  src/Build/Logging/ConsoleLogger.cs
  src/Build/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs
  src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs
  src/Build/Logging/SerialConsoleLogger.cs
  src/Framework/EngineServices.cs
  src/Framework/IBuildEngine10.cs
  src/MSBuild.UnitTests/XMake_Tests.cs
  src/MSBuild/OutOfProcTaskHostNode.cs
  src/MSBuild/XMake.cs
  src/Shared/TaskLoggingHelper.cs
  src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
Labels: Area: Logging, merge-when-branch-open, performance

#6725 Miscellaneous event tweaks
  src/Framework/MSBuildEventSource.cs
Labels: merge-when-branch-open

#5656 implement analyzers from runtime
  .editorconfig
  Directory.Build.props
  eng/Analyzers.props
  eng/CodeAnalysis.ruleset
  eng/Packages.props
Labels: merge-when-branch-open

#6740 Add PackageDescription to Microsoft.NET.StringTools
  src/StringTools/StringTools.csproj
Labels: merge-when-branch-open

#6670 Add up-to-date ETW for WriteLinesToFile
  src/Framework/MSBuildEventSource.cs
  src/Tasks/FileIO/WriteLinesToFile.cs
Labels: merge-when-branch-open

#6640 Specify project info in affinity missmatch error
  src/Build/BackEnd/Components/Scheduler/Scheduler.cs
  src/Build/Resources/Strings.resx
  src/Build/Resources/xlf/Strings.cs.xlf
  src/Build/Resources/xlf/Strings.de.xlf
  src/Build/Resources/xlf/Strings.en.xlf
  src/Build/Resources/xlf/Strings.es.xlf
  src/Build/Resources/xlf/Strings.fr.xlf
  src/Build/Resources/xlf/Strings.it.xlf
  src/Build/Resources/xlf/Strings.ja.xlf
  src/Build/Resources/xlf/Strings.ko.xlf
  src/Build/Resources/xlf/Strings.pl.xlf
  src/Build/Resources/xlf/Strings.pt-BR.xlf
  src/Build/Resources/xlf/Strings.ru.xlf
  src/Build/Resources/xlf/Strings.tr.xlf
  src/Build/Resources/xlf/Strings.zh-Hans.xlf
  src/Build/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open

#6742 Fix Misleading NuGet SDK Resolver Error Message
  src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs
Labels: merge-when-branch-open

#6735 Remove depenency on MemberRef Parent of a custom attribute constructor being a TypeReference
  src/Tasks/AssemblyDependency/AssemblyInformation.cs
Labels: merge-when-branch-open

#6746 Recalculate MSBuild path from VS Root
  src/Shared/BuildEnvironmentHelper.cs
Labels: merge-when-branch-open

#6724 SetPlatform Negotiation: Allow MSBuild `GetTargetFrameworks` call when `SetTargetFramework` already set
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#6759 Nix manual XSD updates
  documentation/wiki/Localization.md
Labels: merge-when-branch-open

#6755 Update XSD to include details about ImplicitUsings and Using items
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Labels: merge-when-branch-open

#6758 Add .NET Core solution open to OptProf training scenarios
  eng/config/OptProf.json
Labels: performance, merge-when-branch-open

#6760 Delete manual Markdown ToCs
  documentation/specs/project-cache.md
  documentation/specs/static-graph-implementation-details.md
  documentation/specs/static-graph.md
Labels: merge-when-branch-open

#6699 Update schema for combining TargetFramework info to allow for invalid xml names such as including '+'
  documentation/ProjectReference-Protocol.md
  ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
  ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
  src/Tasks/CombineTargetFrameworkInfoProperties.cs
  src/Tasks/CombineXmlElements.cs
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#6661 Add CopyUpToDate ETW
  src/Framework/MSBuildEventSource.cs
  src/Tasks/Copy.cs
Labels: merge-when-branch-open

#6726 Generate cache file for SuggestedBindingRedirects
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#6586 16.11 release note update
  documentation/Changelog.md
Labels: merge-when-branch-open

#6595 Enable Microsoft.CodeAnalysis.Collections
  eng/Packages.props
  src/Build/AssemblyInfo.cs
  src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs
  src/Build/Resources/xlf/Strings.en.xlf
  src/Deprecated/Conversion/AssemblyInfo.cs
  src/Deprecated/Conversion/Resources/xlf/Strings.en.xlf
  src/Deprecated/Engine/AssemblyInfo.cs
  src/Deprecated/Engine/Resources/xlf/Strings.en.xlf
  src/Directory.Build.props
  src/Directory.Build.targets
  src/Framework/Microsoft.Build.Framework.csproj
  src/Framework/NullableAttributes.cs
  src/Framework/Properties/AssemblyInfo.cs
  src/MSBuild/AssemblyInfo.cs
  src/MSBuild/Resources/xlf/Strings.en.xlf
  src/Package/Localization/Microsoft.Build.Localization.nuspec
  src/Package/MSBuild.VSSetup/files.swr
  src/Shared/Resources/xlf/Strings.shared.en.xlf
  src/Tasks/AssemblyInfo.cs
  src/Tasks/ManifestUtil/Resources/xlf/Strings.ManifestUtilities.en.xlf
  src/Tasks/Resources/xlf/Strings.en.xlf
  src/Utilities/AssemblyInfo.cs
  src/Utilities/Resources/xlf/Strings.en.xlf
Labels: merge-when-branch-open

#6716 Optimize item Remove operations
  src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs
  src/Build.UnitTests/Definition/ItemDataCollectionValue_Tests.cs
  src/Build/Evaluation/ItemDataCollectionValue.cs
  src/Build/Evaluation/ItemSpec.cs
  src/Build/Evaluation/LazyItemEvaluator.IItemOperation.cs
  src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs
  src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs
  src/Build/Evaluation/LazyItemEvaluator.OrderedItemDataCollection.cs
  src/Build/Evaluation/LazyItemEvaluator.RemoveOperation.cs
  src/Build/Evaluation/LazyItemEvaluator.UpdateOperation.cs
  src/Build/Evaluation/LazyItemEvaluator.cs
  src/Build/Microsoft.Build.csproj
  src/Build/Utilities/FileSpecMatchTester.cs
  src/Shared/Traits.cs
Labels: performance, merge-when-branch-open

#6769 Block Execution of GetType() in Evaluation
  src/Build.UnitTests/Evaluation/Evaluator_Tests.cs
  src/Build.UnitTests/Evaluation/Expander_Tests.cs
  src/Build/Evaluation/Expander.cs
  src/Shared/ResourceUtilities.cs
Labels: merge-when-branch-open

#6738 Propagate solution configuration information to project cache plugins
  src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs
  src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs
  src/Build/Construction/Solution/SolutionConfigurationInSolution.cs
  src/Build/Construction/Solution/SolutionFile.cs
  src/Build/Construction/Solution/SolutionProjectGenerator.cs
  src/Build/Graph/ProjectInterpretation.cs
  src/Samples/ProjectCachePlugin/AssemblyMockCache.cs
  src/Shared/UnitTests/ObjectModelHelpers.cs
  src/Tasks/ResolveProjectBase.cs
Labels: merge-when-branch-open
