Repository dotnet/msbuild, pull requests merged in 2021-07, with the labels that each got.

#6622 Default to transitively copying content items
  documentation/wiki/ChangeWaves.md
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: changewave17.0, merge-when-branch-open

#6650 Fix [DebuggerDisplay] for Project
  src/Build/Definition/Project.cs
Labels: merge-when-branch-open

#6632 Don't compile globbing regexes on .NET Framework
  documentation/wiki/ChangeWaves.md
  src/Build.UnitTests/Globbing/MSBuildGlob_Tests.cs
  src/Build/Globbing/MSBuildGlob.cs
  src/Shared/FileMatcher.cs
  src/Shared/UnitTests/FileMatcher_Tests.cs
Labels: changewave17.0, changewaves, merge-when-branch-open

#6558 Use extension in Next-to-MSBuild fallback
  src/Shared/MSBuildLoadContext.cs
Labels: merge-when-branch-open

#6634 ChangeWave 16.8 Becomes Default Behavior
  documentation/wiki/ChangeWaves.md
  src/Build.UnitTests/Evaluation/Expander_Tests.cs
  src/Build/Evaluation/Expander.cs
  src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs
  src/Framework/ChangeWaves.cs
  src/Shared/NativeMethodsShared.cs
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: changewave16.8, changewaves, merge-when-branch-open

#6638 Switch to Microsoft.DotNet.XUnitExtensions
  eng/Packages.props
  eng/Version.Details.xml
  eng/Versions.props
  src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
  src/Build.UnitTests/BackEnd/BuildRequest_Tests.cs
  src/Build.UnitTests/ConsoleLogger_Tests.cs
  src/Build.UnitTests/Instance/HostServices_Tests.cs
  src/Directory.Build.targets
  src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs
  src/Xunit.NetCore.Extensions/Attributes/ActiveIssueAttribute.cs
  src/Xunit.NetCore.Extensions/Attributes/ConditionalFactAttribute.cs
  src/Xunit.NetCore.Extensions/Attributes/ConditionalTheoryAttribute.cs
  src/Xunit.NetCore.Extensions/Attributes/OuterLoopAttribute.cs
  src/Xunit.NetCore.Extensions/Attributes/PlatformSpecificAttribute.cs
  src/Xunit.NetCore.Extensions/Attributes/SkipOnTargetFrameworkAttribute.cs
  src/Xunit.NetCore.Extensions/Discoverers/ActiveIssueDiscoverer.cs
  src/Xunit.NetCore.Extensions/Discoverers/ConditionalFactDiscoverer.cs
  src/Xunit.NetCore.Extensions/Discoverers/ConditionalTestDiscoverer.cs
  src/Xunit.NetCore.Extensions/Discoverers/ConditionalTheoryDiscoverer.cs
  src/Xunit.NetCore.Extensions/Discoverers/OuterLoopTestsDiscoverer.cs
  src/Xunit.NetCore.Extensions/Discoverers/PlatformSpecificDiscoverer.cs
  src/Xunit.NetCore.Extensions/Discoverers/SkipOnTargetFrameworkDiscoverer.cs
  src/Xunit.NetCore.Extensions/README.md
  src/Xunit.NetCore.Extensions/SkippedTestCase.cs
  src/Xunit.NetCore.Extensions/TargetFrameworkMonikers.cs
  src/Xunit.NetCore.Extensions/TestPlatforms.cs
  src/Xunit.NetCore.Extensions/XunitConstants.cs
Labels: merge-when-branch-open

#6656 16.11 Final Branding
  documentation/Changelog.md
  eng/Versions.props
Labels: merge-when-branch-open

#6669 Revert "Ignore comments and whitespace when parsing read-only XML files (#6232)"
  src/Build/Xml/XmlReaderExtension.cs
Labels: merge-when-branch-open

#6671 Avoid string allocation while searching for a char
  src/Build/Evaluation/Expander.cs
Labels: merge-when-branch-open, performance

#6678 Disable TP semaphore spinning for MSBuild processes
  src/MSBuild/app.amd64.config
  src/MSBuild/app.config
Labels: performance

#6533 Normalize RAR output paths
  src/Tasks/AssemblyDependency/Reference.cs
  src/Tasks/AssemblyDependency/ReferenceTable.cs
Labels: merge-when-branch-open

#6665 VS 1449000: Fix handling of satellite assemblies in ClickOnce
  src/Tasks/ResolveManifestFiles.cs
Labels: merge-when-branch-open

#6668 Remove import using `CoreCrossTargetingTargetsPath` property
  src/Tasks/Microsoft.Common.CrossTargeting.targets
Labels: merge-when-branch-open

#6676 Do not run analyzers for XamlPreCompile.
  src/Tasks/Microsoft.CSharp.CurrentVersion.targets
Labels: merge-when-branch-open

#6560 Move ref assembly to the obj folder
  documentation/wiki/ChangeWaves.md
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: changewave17.0, merge-when-branch-open

#6674 Move version check earlier
  src/Tasks/StateFileBase.cs
Labels: merge-when-branch-open

#6680 Fix lock contention in ProjectRootElementCache.Get
  src/Build.UnitTests/Evaluation/SimpleProjectRootElementCache_Tests.cs
  src/Build/Construction/ProjectRootElement.cs
  src/Build/Evaluation/Evaluator.cs
  src/Build/Evaluation/ProjectRootElementCache.cs
  src/Build/Evaluation/SimpleProjectRootElementCache.cs
Labels: merge-when-branch-open, performance

#6658 Add ETW trace for PerformDependencyAnalysis
  src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs
  src/Framework/MSBuildEventSource.cs
Labels: merge-when-branch-open

#6639 Improve debugging experience: add global switch MSBuildDebugEngine; Inject binary logger from BuildManager; print static graph as .dot file
  documentation/wiki/ChangeWaves.md
  src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs
  src/Build/BackEnd/Components/Scheduler/Scheduler.cs
  src/Build/BackEnd/Components/Scheduler/SchedulingPlan.cs
  src/Build/BackEnd/Node/OutOfProcNode.cs
  src/Build/Graph/ProjectGraph.cs
  src/MSBuild.UnitTests/XMake_Tests.cs
  src/MSBuild/OutOfProcTaskHostNode.cs
  src/Shared/CommunicationsUtilities.cs
  src/Shared/Debugging/DebugUtils.cs
  src/Shared/Debugging/PrintLineDebugger.cs
  src/Shared/ExceptionHandling.cs
  src/Shared/NodeEndpointOutOfProcBase.cs
  src/Shared/Traits.cs
Labels: merge-when-branch-open

#6705 Using ArrayPool for buffers in InterningBinaryReader
  src/Shared/InterningBinaryReader.cs
Labels: merge-when-branch-open

#6706 Fix deploy script for 64bits and net6
  scripts/Deploy-MSBuild.ps1
Labels: merge-when-branch-open

#6698 Skip Updating CopyComplete Marker When Not Necessary
  ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
  ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
  src/Tasks/Copy.cs
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#6663 Stop checking .ni.dll/exe on Core
  src/Shared/CoreCLRAssemblyLoader.cs
  src/Shared/MSBuildLoadContext.cs
Labels: merge-when-branch-open

#6683 Identify 64-bit MSBuildToolsPath from 64-bit API consumer
  src/Build.UnitTests/BuildEnvironmentHelper_Tests.cs
  src/Shared/BuildEnvironmentHelper.cs
Labels: merge-when-branch-open

#6718 Revert move of reference assemblies into obj
  documentation/wiki/ChangeWaves.md
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: Servicing-consider

#6655 ProjectReferences Negotiate SetPlatform Metadata
  documentation/ProjectReference-Protocol.md
  ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
  ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
  src/Tasks.UnitTests/GetCompatiblePlatform_Tests.cs
  src/Tasks/GetCompatiblePlatform.cs
  src/Tasks/Microsoft.Build.Tasks.csproj
  src/Tasks/Microsoft.Common.CrossTargeting.targets
  src/Tasks/Microsoft.Common.CurrentVersion.targets
  src/Tasks/Microsoft.Common.tasks
  src/Tasks/Resources/Strings.resx
  src/Tasks/Resources/xlf/Strings.cs.xlf
  src/Tasks/Resources/xlf/Strings.de.xlf
  src/Tasks/Resources/xlf/Strings.en.xlf
  src/Tasks/Resources/xlf/Strings.es.xlf
  src/Tasks/Resources/xlf/Strings.fr.xlf
  src/Tasks/Resources/xlf/Strings.it.xlf
  src/Tasks/Resources/xlf/Strings.ja.xlf
  src/Tasks/Resources/xlf/Strings.ko.xlf
  src/Tasks/Resources/xlf/Strings.pl.xlf
  src/Tasks/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Resources/xlf/Strings.ru.xlf
  src/Tasks/Resources/xlf/Strings.tr.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open
