Repository dotnet/msbuild, pull requests merged in 2021-05, with the labels that each got.

#6361 Update Visual Studio Version to 17.0
  ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs
  ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs
  src/Build.UnitTests/BuildEnvironmentHelper_Tests.cs
  src/MSBuild/app.amd64.config
  src/Package/MSBuild.VSSetup/files.swr
  src/Shared/BuildEnvironmentHelper.cs
  src/Shared/Constants.cs
  src/Shared/FrameworkLocationHelper.cs
  src/Tasks/Microsoft.Build.Tasks.csproj
  src/Tasks/Microsoft.VisualStudioVersion.v17.Common.props
  src/Utilities.UnitTests/ToolLocationHelper_Tests.cs
  src/Utilities/ToolLocationHelper.cs
Labels: merge-when-branch-open

#6437 Ensure context is not cached before logging info
  eng/Versions.props
  src/Build.UnitTests/BinaryLogger_Tests.cs
  src/Build/BackEnd/Components/Logging/NodeLoggingContext.cs
Labels: Servicing-approved

#6430 Allow projects with no restore target to build under `dotnet build`
  documentation/wiki/ChangeWaves.md
  ref/Microsoft.Build/net/Microsoft.Build.cs
  ref/Microsoft.Build/netstandard/Microsoft.Build.cs
  src/Build/BackEnd/BuildManager/BuildRequestData.cs
  src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs
  src/Build/BackEnd/Shared/BuildRequestConfiguration.cs
  src/Build/Evaluation/Evaluator.cs
  src/MSBuild.UnitTests/XMake_Tests.cs
  src/MSBuild/XMake.cs
Labels: Servicing-approved

#6438 Fix generated editor config files for xaml precompile
  src/Tasks/Microsoft.CSharp.CurrentVersion.targets
  src/Tasks/Microsoft.VisualBasic.CurrentVersion.targets
Labels: Servicing-approved

#6465 Building a subset of a VS solution at the command line causes MSB4057
  eng/Versions.props
  src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
  src/Build/Construction/Solution/SolutionProjectGenerator.cs
Labels: Servicing-consider

#6463 Fix signing tool lookup for VS64
  src/Tasks/ManifestUtil/SecurityUtil.cs
Labels: merge-when-branch-open

#6457 Fix memory leak in ProjectRootElement.Reload
  src/Build.OM.UnitTests/Construction/ProjectRootElement_Tests.cs
  src/Build/Construction/ProjectRootElement.cs
  src/Build/Evaluation/ProjectStringCache.cs
Labels: merge-when-branch-open

#6412 Lock writes to _overallBuildSuccess
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Samples/ProjectCachePlugin/AssemblyMockCache.cs
Labels: merge-when-branch-open

#6431 Use packaged C# compiler
  eng/Versions.props
Labels: merge-when-branch-open

#6471 Moves build into scale sets pool
  .vsts-dotnet.yml
Labels: merge-when-branch-open

#6385 Build out of proc sln file using MSBUILDNOINPROCNODE
  src/Build.UnitTests/BackEnd/BuildRequestConfiguration_Tests.cs
  src/Build/BackEnd/Shared/BuildRequestConfiguration.cs
  src/Build/Construction/Solution/SolutionProjectGenerator.cs
  src/Build/Instance/ProjectInstance.cs
  src/MSBuild.UnitTests/XMake_Tests.cs
Labels: merge-when-branch-open

#6350 Remove BinaryFormatter from StateFileBase
  src/Shared/BinaryTranslator.cs
  src/Shared/ITranslator.cs
  src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceCacheSerialization.cs
  src/Tasks.UnitTests/AssemblyRegistrationCache_Tests.cs
  src/Tasks.UnitTests/ResolveComReference_Tests.cs
  src/Tasks.UnitTests/ResourceHandling/ResGenDependencies_Tests.cs
  src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
  src/Tasks/AssemblyRegistrationCache.cs
  src/Tasks/Dependencies.cs
  src/Tasks/DependencyFile.cs
  src/Tasks/Microsoft.Build.Tasks.csproj
  src/Tasks/ResGenDependencies.cs
  src/Tasks/ResolveComReferenceCache.cs
  src/Tasks/StateFileBase.cs
  src/Tasks/SystemState.cs
Labels: merge-when-branch-open

#6324 Remove BinaryFormatter from GetSDKReferenceFiles
  src/Tasks.UnitTests/GetSDKReference_Tests.cs
  src/Tasks/GetSDKReferenceFiles.cs
Labels: merge-when-branch-open

#6393 Rar permissions fix
  src/Tasks/StateFileBase.cs
  src/Tasks/SystemState.cs
Labels: merge-when-branch-open

#6395 Remove KeyPair deserialization
  src/Shared/TranslatorHelpers.cs
Labels: merge-when-branch-open

#6386 Schedule proxy builds to inproc node
  src/Build.UnitTests/BackEnd/Scheduler_Tests.cs
  src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs
  src/Build/BackEnd/Components/Logging/LoggingContext.cs
  src/Build/BackEnd/Components/Scheduler/SchedulableRequest.cs
  src/Build/BackEnd/Components/Scheduler/Scheduler.cs
  src/Build/BackEnd/Shared/BuildRequest.cs
  src/Build/Resources/Strings.resx
  src/Build/Resources/xlf/Strings.cs.xlf
  src/Build/Resources/xlf/Strings.de.xlf
  src/Build/Resources/xlf/Strings.en.xlf
  src/Build/Resources/xlf/Strings.es.xlf
  src/Build/Resources/xlf/Strings.fr.xlf
  src/Build/Resources/xlf/Strings.it.xlf
  src/Build/Resources/xlf/Strings.ja.xlf
  src/Build/Resources/xlf/Strings.ko.xlf
  src/Build/Resources/xlf/Strings.pl.xlf
  src/Build/Resources/xlf/Strings.pt-BR.xlf
  src/Build/Resources/xlf/Strings.ru.xlf
  src/Build/Resources/xlf/Strings.tr.xlf
  src/Build/Resources/xlf/Strings.zh-Hans.xlf
  src/Build/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open

#6488 Update ubuntu version
  .vsts-dotnet-ci.yml
Labels: merge-when-branch-open

#6495 Fix deploy script for .net 6.0
  scripts/Deploy-MSBuild.ps1
Labels: merge-when-branch-open

#6489 Update test-upload TargetFramework
  .vsts-dotnet-ci.yml
Labels: merge-when-branch-open

#6454 Add solution-validation targets as hook points
  src/Build/Construction/Solution/SolutionProjectGenerator.cs
Labels: merge-when-branch-open

#6398 Improve vs debugging
  scripts/Deploy-MSBuild.ps1
  src/Build/BackEnd/BuildManager/BuildManager.cs
Labels: merge-when-branch-open

#6397 Log location of intrinsic tasks
  src/Build.UnitTests/BackEnd/NodePackets_Tests.cs
  src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
  src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs
  src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupLoggingHelper.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
  src/Framework/BuildMessageEventArgs.cs
  src/Framework/TaskParameterEventArgs.cs
Labels: Area: Debuggability, Area: Logging, merge-when-branch-open

#6402 Add TargetSkipReason and OriginalBuildEventContext to TargetSkippedEventArgs
  ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
  src/Build.UnitTests/BackEnd/NodePackets_Tests.cs
  src/Build.UnitTests/BackEnd/TargetResult_Tests.cs
  src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
  src/Build/BackEnd/Components/Communications/TranslatorExtensions.cs
  src/Build/BackEnd/Components/Logging/NodeLoggingContext.cs
  src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs
  src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs
  src/Build/BackEnd/Components/RequestBuilder/TargetUpToDateChecker.cs
  src/Build/BackEnd/Shared/TargetResult.cs
  src/Build/Logging/BinaryLogger/BinaryLogger.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
  src/Framework/BuildEventContext.cs
  src/Framework/BuildMessageEventArgs.cs
  src/Framework/TargetSkippedEventArgs.cs
Labels: merge-when-branch-open

#6399 Log TaskStarted line and column
  ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
  src/Build.UnitTests/BackEnd/MockLoggingService.cs
  src/Build.UnitTests/BackEnd/NodePackets_Tests.cs
  src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
  src/Build/BackEnd/Components/Logging/ILoggingService.cs
  src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs
  src/Build/BackEnd/Components/Logging/TaskLoggingContext.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
  src/Framework/TaskStartedEventArgs.cs
Labels: Area: Debuggability, Area: Logging, merge-when-branch-open

#6475 Make MSBuildFileSystemBase non-abstract to remove versioning and usability constraints
  ref/Microsoft.Build/net/Microsoft.Build.cs
  ref/Microsoft.Build/netstandard/Microsoft.Build.cs
  src/Build.UnitTests/Definition/ProjectEvaluationContext_Tests.cs
  src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs
  src/Build/Evaluation/Context/EvaluationContext.cs
  src/Build/FileSystem/IFileSystemAdapter.cs
  src/Build/FileSystem/MSBuildFileSystemAdapter.cs
  src/Build/FileSystem/MSBuildFileSystemBase.cs
  src/MSBuildTaskHost/FileSystem/MSBuildTaskHostFileSystem.cs
  src/Shared/FileSystem/CachingFileSystemWrapper.cs
  src/Shared/FileSystem/IFileSystem.cs
  src/Shared/FileSystem/MSBuildOnWindowsFileSystem.cs
  src/Shared/FileSystem/ManagedFileSystem.cs
  src/Shared/FileSystem/WindowsFileSystem.cs
  src/Shared/FileUtilities.cs
  src/Shared/UnitTests/FileMatcher_Tests.cs
  src/Shared/UnitTests/ObjectModelHelpers.cs
Labels: merge-when-branch-open

#6469 Stop MSBuildTaskHost importing Microsoft.VisualStudio.Setup.Configuration.Interop
  src/Directory.BeforeCommon.targets
  src/MSBuildTaskHost/MSBuildTaskHost.csproj
Labels: merge-when-branch-open

#6411 Official Builds With Custom OptProf 'Just Work'
  .vsts-dotnet.yml
Labels: merge-when-branch-open

#6500 Add common properties to XSD
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Labels: merge-when-branch-open
