Repository dotnet/msbuild, pull requests merged in 2021-09, with the labels that each got.

#6784 Update System.Text.Json to 5.0.2
  eng/Packages.props
  src/Build/System.Text.Encodings.Web.pkgdef
  src/Build/System.Text.Json.pkgdef
  src/MSBuild/MSBuild.csproj
  src/MSBuild/app.amd64.config
  src/MSBuild/app.config
  src/Package/MSBuild.VSSetup/files.swr
Labels: exp-branch

#6744 Doc comments: fix validation issues in docs build
  src/Build/Construction/ProjectElement.cs
  src/Build/Construction/ProjectElementContainer.cs
  src/Build/Definition/Project.cs
  src/Framework/Sdk/SdkResolver.cs
  src/Framework/Sdk/SdkResolverContext.cs
  src/Framework/Sdk/SdkResult.cs
  src/Tasks/CreateItem.cs
  src/Tasks/CreateProperty.cs
  src/Tasks/Hash.cs
  src/Tasks/MSBuild.cs
  src/Utilities/ToolLocationHelper.cs
  src/Utilities/TrackedDependencies/FileTracker.cs
Labels: merge-when-branch-open

#6798 Add invariant check to InternableString.ExpensiveConvertToString
  src/StringTools/InternableString.cs
Labels: merge-when-branch-open

#6786 Increase ProjectRootElementCache MRU cache
  src/Build/Evaluation/ProjectRootElementCache.cs
Labels: performance, Performance-Scenario-Solution-Open, merge-when-branch-open

#6805 Delete dead code.
  src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
Labels: merge-when-branch-open

#6830 Binding redirect Tasks.Extensions 4.2.0.1
  src/MSBuild/app.amd64.config
  src/MSBuild/app.config
Labels: Partner request

#6803 Expose LogTaskInputs to tasks
  ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs
  ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs
  src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
  src/Build.UnitTests/BackEnd/TaskHostConfiguration_Tests.cs
  src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs
  src/Build/Instance/TaskFactories/TaskHostTask.cs
  src/Framework/EngineServices.cs
  src/MSBuild/OutOfProcTaskHostNode.cs
  src/Shared/TaskHostConfiguration.cs
  src/Shared/TaskLoggingHelper.cs
  src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
Labels: merge-when-branch-open

#6816 Optimize InternableString.GetHashCode
  src/StringTools.UnitTests/SpanBasedStringBuilder_Tests.cs
  src/StringTools.UnitTests/WeakStringCache_Tests.cs
  src/StringTools/InternableString.cs
Labels: merge-when-branch-open

#6832 Process-wide caching of ToolsetConfigurationSection
  src/Build/Definition/ToolsetConfigurationReader.cs
  src/Shared/ToolsetElement.cs
Labels: merge-when-branch-open

#6845 Further optimize InternableString.GetHashCode by eliminating a ref parameter
  src/StringTools/InternableString.cs
Labels: merge-when-branch-open

#6837 Fix deadlock in BuildManager vs LoggingService
  src/Build/BackEnd/BuildManager/BuildManager.cs
Labels: merge-when-branch-open

#6804 Log message arguments for warnings and errors
  src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
Labels: Area: Logging, merge-when-branch-open

#6864 Use static CoreClrAssemblyLoader in the SdkResolverLoader
  src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs
  src/Build/BackEnd/Components/SdkResolution/SdkResolverLoader.cs
Labels: merge-when-branch-open

#6860 Add new Windows Forms specific props
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Labels: merge-when-branch-open

#6846 Skip Updating CopyComplete Marker When Not Necessary
  eng/Versions.props
  ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
  ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
  src/Tasks/Copy.cs
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: Servicing-approved

#6849 Add enumeration values for DebugType in XSD
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Labels: merge-when-branch-open, Area: IntelliSense

#6861 Add SatelliteResourceLanguages property to common types schema
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Labels: merge-when-branch-open, Area: IntelliSense

#6888 Deploy-MSBuild shouldn't deploy en resources
  scripts/Deploy-MSBuild.ps1
Labels: merge-when-branch-open

#6884 Avoid appending x64 to AL path if x64 is already appended
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#6873 Add labels documentation
  README.md
  documentation/wiki/Labels.md
Labels: merge-when-branch-open

#6889 SetPlatform: Use Platform Instead Of PlatformTarget
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#6881 Enable File Scoped Namespaces For Resources
  src/Tasks.UnitTests/CSharpParserUtilitites_Tests.cs
  src/Tasks/CSharpParserUtilities.cs
Labels: merge-when-branch-open

#6863 Initialize XmlReaders using StreamReaders
  src/Tasks/XslTransformation.cs
Labels: merge-when-branch-open

#6898 Delete intermediate sourcebuild package
  eng/common/templates/post-build/post-build.yml
Labels: merge-when-branch-open

#6890 Find dotnet.exe instead of <name>.exe when building out-of-proc using MSBuildLocator
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
Labels: merge-when-branch-open
