Repository dotnet/msbuild, pull requests merged in 2021-06, with the labels that each got.

#6468 Make cache queries parallel
  src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Components/ProjectCache/CacheResult.cs
  src/Build/BackEnd/Components/ProjectCache/ProjectCacheDescriptor.cs
  src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs
  src/Shared/UnitTests/ObjectModelHelpers.cs
Labels: merge-when-branch-open

#6448 Use dotnet certificate
  eng/Signing.props
Labels: merge-when-branch-open

#6505 Move RichCodeNav to its own job
  .vsts-dotnet-ci.yml
Labels: merge-when-branch-open

#6507 Add SourceBuildManagedOnly to SourceBuild.props
  eng/SourceBuild.props
Labels: merge-when-branch-open

#6509 Enable SignFile on .NET Core/5+
  ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
  src/Tasks/Microsoft.Build.Tasks.csproj
Labels: merge-when-branch-open

#6400 Scheduler should honor BuildParameters.DisableInprocNode
  src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
  src/Build.UnitTests/BackEnd/Scheduler_Tests.cs
  src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs
  src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs
  src/Build/BackEnd/Components/Scheduler/Scheduler.cs
Labels: merge-when-branch-open

#6410 Log RAR "size" in ETW
  src/Framework/MSBuildEventSource.cs
  src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
Labels: Performance-Scenario-Build, Task: Resolve Assembly References (RAR), merge-when-branch-open, performance

#6550 Switch VCTargetsPath to v170
  src/MSBuild/app.amd64.config
  src/MSBuild/app.config
Labels: C++ tasks and targets

#6561 Properly condition onelocbuild template
  .vsts-dotnet.yml
Labels: Area: Our Own Build, Localization

#6572 Set branch for loc PRs
  .vsts-dotnet.yml
Labels: Area: Our Own Build, Localization

#6530 Add .NET tool properties to XSD
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Labels: merge-when-branch-open

#6545 Bind to 17.0 version of Workflow build tasks for Dev17
  src/MSBuild/app.amd64.config
  src/MSBuild/app.config
Labels: Partner request, merge-when-branch-open

#6557 Issue templates apply needs-triage label
  .github/ISSUE_TEMPLATE/01_bugreport.md
  .github/ISSUE_TEMPLATE/02_performanceissue.md
  .github/ISSUE_TEMPLATE/03_mybuildisbroken.md
  .github/ISSUE_TEMPLATE/04_blankissue.md
Labels: Area: Our Own Build, merge-when-branch-open

#6559 Revert "Add more params to the evaluation pass stops"
  src/Build/Evaluation/Evaluator.cs
  src/Framework/MSBuildEventSource.cs
Labels: merge-when-branch-open

#6548 Simplify reference to Microsoft.Extensions.DependencyModel
  eng/BootStrapMSBuild.targets
  eng/Packages.props
  eng/Version.Details.xml
  src/MSBuild.Bootstrap/MSBuild.Bootstrap.csproj
Labels: Area: Our Own Build, merge-when-branch-open

#6573 Backport Ubuntu update to 16.11
  .vsts-dotnet-ci.yml
Labels: merge-when-branch-open

#6529 Minor perf fixes for LazyItemEvaluator
  src/Build/Evaluation/ExpressionShredder.cs
  src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs
  src/Build/Evaluation/LazyItemEvaluator.cs
Labels: merge-when-branch-open, performance

#6511 Do not expect PDB files for a refonly build
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#6534 Add reserved properties MSBuildFileVersion and MSBuildSemanticVersion
  src/Build.UnitTests/Evaluation/Evaluator_Tests.cs
  src/Build/Evaluation/Evaluator.cs
  src/Build/Resources/Constants.cs
Labels: merge-when-branch-open

#6589 Update build badge links
  README.md
Labels: Area: Our Own Build

#6578 Publish FileAssociation Icons correctly in Single-File ClickOnce publish
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#6556 Make InterningBinaryReader pool buffers
  src/Build.UnitTests/BackEnd/BinaryTranslator_Tests.cs
  src/Build/BackEnd/BuildManager/CacheSerialization.cs
  src/Build/BackEnd/Shared/BuildRequestConfiguration.cs
  src/Build/BackEnd/Shared/TargetResult.cs
  src/Shared/BinaryTranslator.cs
  src/Shared/ITranslator.cs
  src/Shared/InterningBinaryReader.cs
  src/Tasks/GetSDKReferenceFiles.cs
  src/Tasks/StateFileBase.cs
Labels: merge-when-branch-open, performance

#6568 Fix missing project instance in project cache requests
  src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs
  src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs
  src/Samples/ProjectCachePlugin/AssemblyMockCache.cs
  src/Samples/ProjectCachePlugin/ProjectCachePlugin.csproj
Labels: merge-when-branch-open

#6598 Use List<string> for excludes
  src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs
Labels: merge-when-branch-open, performance

#6569 Ensure project cache initialization happens only once
  src/Build.UnitTests/BackEnd/BuildRequestConfiguration_Tests.cs
  src/Build.UnitTests/Definition/ProjectEvaluationContext_Tests.cs
  src/Build.UnitTests/Graph/GraphLoadedFromSolution_tests.cs
  src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
  src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs
  src/Build/BackEnd/BuildManager/BuildParameters.cs
  src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs
  src/Shared/ErrorUtilities.cs
  src/Shared/UnitTests/TestAssemblyInfo.cs
Labels: merge-when-branch-open

#5799 Check TargetFramework Using Intrinsic Function
  src/Directory.BeforeCommon.targets
  src/Directory.Build.targets
Labels: merge-when-branch-open

#6535 Console logger support for IncludeEvaluationPropertiesAndItems
  src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
  src/Build.UnitTests/BackEnd/TaskBuilder_Tests.cs
  src/Build.UnitTests/ConsoleLogger_Tests.cs
  src/Build/Logging/BaseConsoleLogger.cs
  src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs
Labels: merge-when-branch-open

#6627 Don't log Building with tools version "Current".
  src/Build/BackEnd/Components/Logging/ProjectLoggingContext.cs
Labels: merge-when-branch-open
