Repository dotnet/msbuild, pull requests merged in 2021-02, with the labels that each got.

#6102 Loc updates
  src/Build/Resources/xlf/Strings.cs.xlf
  src/Build/Resources/xlf/Strings.de.xlf
  src/Build/Resources/xlf/Strings.es.xlf
  src/Build/Resources/xlf/Strings.fr.xlf
  src/Build/Resources/xlf/Strings.it.xlf
  src/Build/Resources/xlf/Strings.ja.xlf
  src/Build/Resources/xlf/Strings.ko.xlf
  src/Build/Resources/xlf/Strings.pl.xlf
  src/Build/Resources/xlf/Strings.pt-BR.xlf
  src/Build/Resources/xlf/Strings.ru.xlf
  src/Build/Resources/xlf/Strings.tr.xlf
  src/Build/Resources/xlf/Strings.zh-Hans.xlf
  src/Build/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open

#5994 Support gathering additional arbitrary properties from referenced projects
  documentation/ProjectReference-Protocol.md
  ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
  ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
  src/Tasks/CombineTargetFrameworkInfoProperties.cs
  src/Tasks/CombineXmlElements.cs
  src/Tasks/Microsoft.Build.Tasks.csproj
  src/Tasks/Microsoft.Common.CrossTargeting.targets
  src/Tasks/Microsoft.Common.CurrentVersion.targets
  src/Tasks/Microsoft.Common.tasks
Labels: merge-when-branch-open

#6059 Disable Mono CI
  .vsts-dotnet-ci.yml
Labels: merge-when-branch-open

#6104 Miscellaneous refactors leftover from #5238
  src/Shared/FileUtilities.cs
  src/Tasks.UnitTests/GenerateBindingRedirects_Tests.cs
Labels: merge-when-branch-open

#6093 Pass $(Nullable) to csc in XamlPreCompile
  src/Tasks/Microsoft.CSharp.CurrentVersion.targets
Labels: merge-when-branch-open

#6055 Fix FindOnPathSucceeds failing on some Linux flavors
  src/Utilities.UnitTests/ToolTask_Tests.cs
Labels: merge-when-branch-open

#6043 Update static graph docs
  documentation/specs/static-graph-implementation-details.md
  documentation/specs/static-graph.md
Labels: Documentation, merge-when-branch-open

#6042 Short doc on the threading model
  documentation/specs/threading.md
Labels: Documentation, merge-when-branch-open

#6018 Added Include/Exclude filtering capability to Unzip Task (#5169)
  ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
  ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
  src/Shared/FileMatcher.cs
  src/Tasks.UnitTests/Unzip_Tests.cs
  src/Tasks/Resources/Strings.resx
  src/Tasks/Resources/xlf/Strings.cs.xlf
  src/Tasks/Resources/xlf/Strings.de.xlf
  src/Tasks/Resources/xlf/Strings.en.xlf
  src/Tasks/Resources/xlf/Strings.es.xlf
  src/Tasks/Resources/xlf/Strings.fr.xlf
  src/Tasks/Resources/xlf/Strings.it.xlf
  src/Tasks/Resources/xlf/Strings.ja.xlf
  src/Tasks/Resources/xlf/Strings.ko.xlf
  src/Tasks/Resources/xlf/Strings.pl.xlf
  src/Tasks/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Resources/xlf/Strings.ru.xlf
  src/Tasks/Resources/xlf/Strings.tr.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Unzip.cs
Labels: merge-when-branch-open

#6081 Fix deploy-MSBuild after arcade change
  scripts/Deploy-MSBuild.ps1
Labels: merge-when-branch-open

#5929 Optimize RAR's GetReferenceItems method
  src/MSBuildTaskHost/Immutable/ImmutableDictionary.cs
  src/Shared/CopyOnWriteDictionary.cs
  src/Tasks/AssemblyDependency/ReferenceTable.cs
  src/Utilities/TaskItem.cs
Labels: merge-when-branch-open

#6016 Add /graph:noBuild
  ref/Microsoft.Build/net/Microsoft.Build.cs
  ref/Microsoft.Build/netstandard/Microsoft.Build.cs
  src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
  src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/Graph/GraphBuildRequestData.cs
  src/Build/Resources/Strings.resx
  src/Build/Resources/xlf/Strings.cs.xlf
  src/Build/Resources/xlf/Strings.de.xlf
  src/Build/Resources/xlf/Strings.en.xlf
  src/Build/Resources/xlf/Strings.es.xlf
  src/Build/Resources/xlf/Strings.fr.xlf
  src/Build/Resources/xlf/Strings.it.xlf
  src/Build/Resources/xlf/Strings.ja.xlf
  src/Build/Resources/xlf/Strings.ko.xlf
  src/Build/Resources/xlf/Strings.pl.xlf
  src/Build/Resources/xlf/Strings.pt-BR.xlf
  src/Build/Resources/xlf/Strings.ru.xlf
  src/Build/Resources/xlf/Strings.tr.xlf
  src/Build/Resources/xlf/Strings.zh-Hans.xlf
  src/Build/Resources/xlf/Strings.zh-Hant.xlf
  src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
  src/MSBuild/CommandLineSwitches.cs
  src/MSBuild/Resources/Strings.resx
  src/MSBuild/Resources/xlf/Strings.cs.xlf
  src/MSBuild/Resources/xlf/Strings.de.xlf
  src/MSBuild/Resources/xlf/Strings.en.xlf
  src/MSBuild/Resources/xlf/Strings.es.xlf
  src/MSBuild/Resources/xlf/Strings.fr.xlf
  src/MSBuild/Resources/xlf/Strings.it.xlf
  src/MSBuild/Resources/xlf/Strings.ja.xlf
  src/MSBuild/Resources/xlf/Strings.ko.xlf
  src/MSBuild/Resources/xlf/Strings.pl.xlf
  src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
  src/MSBuild/Resources/xlf/Strings.ru.xlf
  src/MSBuild/Resources/xlf/Strings.tr.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
  src/MSBuild/XMake.cs
  src/Shared/AssemblyUtilities.cs
  src/Shared/UnitTests/MockLogger.cs
  src/Shared/UnitTests/ObjectModelHelpers.cs
Labels: Static Graph, merge-when-branch-open

#6033 Optimize FileExists lookup
  src/Shared/FileDelegates.cs
  src/Shared/FileUtilities.cs
  src/Shared/UnitTests/FileUtilities_Tests.cs
  src/Tasks.UnitTests/AssemblyDependency/GlobalAssemblyCacheTests.cs
  src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs
  src/Tasks.UnitTests/AssemblyDependency/Perf.cs
  src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs
  src/Tasks.UnitTests/AssemblyDependency/VerifyTargetFrameworkAttribute.cs
  src/Tasks.UnitTests/HintPathResolver_Tests.cs
  src/Tasks/AssemblyDependency/AssemblyFoldersExResolver.cs
  src/Tasks/AssemblyDependency/AssemblyFoldersFromConfig/AssemblyFoldersFromConfigResolver.cs
  src/Tasks/AssemblyDependency/AssemblyFoldersResolver.cs
  src/Tasks/AssemblyDependency/AssemblyResolution.cs
  src/Tasks/AssemblyDependency/CandidateAssemblyFilesResolver.cs
  src/Tasks/AssemblyDependency/DirectoryResolver.cs
  src/Tasks/AssemblyDependency/FrameworkPathResolver.cs
  src/Tasks/AssemblyDependency/GacResolver.cs
  src/Tasks/AssemblyDependency/HintPathResolver.cs
  src/Tasks/AssemblyDependency/RawFilenameResolver.cs
  src/Tasks/AssemblyDependency/ReferenceTable.cs
  src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
  src/Tasks/AssemblyDependency/Resolver.cs
  src/Tasks/InstalledSDKResolver.cs
  src/Tasks/SystemState.cs
Labels: merge-when-branch-open

#6091 Skip reading environment variable when changewave has already been parsed
  src/Framework/ChangeWaves.cs
Labels: merge-when-branch-open, performance

#6106 Update Optprof Tests
  eng/config/OptProf.json
Labels: merge-when-branch-open

#6126 Change Load Behavior for NuGet Components
  src/Build/Utilities/NuGetFrameworkWrapper.cs
  src/Shared/MSBuildLoadContext.cs
Labels: merge-when-branch-open

#6017 Deduplicate strings in binlogs
  ref/Microsoft.Build/net/Microsoft.Build.cs
  ref/Microsoft.Build/netstandard/Microsoft.Build.cs
  src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
  src/Build/Logging/BinaryLogger/BinaryLogRecordKind.cs
  src/Build/Logging/BinaryLogger/BinaryLogReplayEventSource.cs
  src/Build/Logging/BinaryLogger/BinaryLogger.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
Labels: merge-when-branch-open, performance

#6036 Remove more unnecessary NuGet package references.
  eng/Packages.props
  src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
  src/Build/Microsoft.Build.csproj
  src/MSBuild/MSBuild.csproj
  src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
  src/Tasks/Microsoft.Build.Tasks.csproj
  src/Utilities.UnitTests/Microsoft.Build.Utilities.UnitTests.csproj
Labels: merge-when-branch-open

#6130 Use Span<T> on all platforms that support it
  src/Directory.BeforeCommon.targets
  src/Shared/FileUtilities.cs
Labels: merge-when-branch-open

#5945 Enhance msb4064 unexpected task attribute error
  src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
  src/Build/Resources/Strings.resx
  src/Build/Resources/xlf/Strings.cs.xlf
  src/Build/Resources/xlf/Strings.de.xlf
  src/Build/Resources/xlf/Strings.en.xlf
  src/Build/Resources/xlf/Strings.es.xlf
  src/Build/Resources/xlf/Strings.fr.xlf
  src/Build/Resources/xlf/Strings.it.xlf
  src/Build/Resources/xlf/Strings.ja.xlf
  src/Build/Resources/xlf/Strings.ko.xlf
  src/Build/Resources/xlf/Strings.pl.xlf
  src/Build/Resources/xlf/Strings.pt-BR.xlf
  src/Build/Resources/xlf/Strings.ru.xlf
  src/Build/Resources/xlf/Strings.tr.xlf
  src/Build/Resources/xlf/Strings.zh-Hans.xlf
  src/Build/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open

#6023 Reduce byte array allocations when reading/writing packets
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
  src/Shared/NodeEndpointOutOfProcBase.cs
Labels: merge-when-branch-open, performance

#6129 Enable building StringTools without 3.5 SP1 targeting pack installed
  src/StringTools/StringTools.csproj
Labels: merge-when-branch-open

#6157 Rename GenerateReferenceAssemblySources -> GenerateReferenceAssemblySource
  ref/Microsoft.Build.Engine/net/Microsoft.Build.Engine.cs
  ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
  ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
  ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
  ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs
  ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs
  ref/Microsoft.Build/net/Microsoft.Build.cs
  ref/Microsoft.Build/netstandard/Microsoft.Build.cs
  src/Build/Microsoft.Build.csproj
  src/Deprecated/Conversion/Microsoft.Build.Conversion.csproj
  src/Deprecated/Engine/Microsoft.Build.Engine.csproj
  src/Directory.BeforeCommon.targets
  src/Directory.Build.props
  src/Directory.Build.targets
  src/Framework/Microsoft.Build.Framework.csproj
  src/Tasks/Microsoft.Build.Tasks.csproj
  src/Utilities/Microsoft.Build.Utilities.csproj
Labels: Area: Our Own Build, merge-when-branch-open

#6035 Optimize Match-on-metadata
  src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs
  src/Build.UnitTests/BackEnd/IntrinsicTask_Tests.cs
  src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs
  src/Build/Evaluation/ItemSpec.cs
  src/Build/Evaluation/LazyItemEvaluator.RemoveOperation.cs
  src/Build/Resources/Strings.resx
  src/Build/Resources/xlf/Strings.cs.xlf
  src/Build/Resources/xlf/Strings.de.xlf
  src/Build/Resources/xlf/Strings.en.xlf
  src/Build/Resources/xlf/Strings.es.xlf
  src/Build/Resources/xlf/Strings.fr.xlf
  src/Build/Resources/xlf/Strings.it.xlf
  src/Build/Resources/xlf/Strings.ja.xlf
  src/Build/Resources/xlf/Strings.ko.xlf
  src/Build/Resources/xlf/Strings.pl.xlf
  src/Build/Resources/xlf/Strings.pt-BR.xlf
  src/Build/Resources/xlf/Strings.ru.xlf
  src/Build/Resources/xlf/Strings.tr.xlf
  src/Build/Resources/xlf/Strings.zh-Hans.xlf
  src/Build/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open

#6053 When sharing the terminal with child nodes, wait for the children to terminate before exiting ourselves.
  scripts/Deploy-MSBuild.ps1
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
  src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
  src/Build/Microsoft.Build.csproj
  src/Build/Resources/Strings.resx
  src/Build/Resources/xlf/Strings.cs.xlf
  src/Build/Resources/xlf/Strings.de.xlf
  src/Build/Resources/xlf/Strings.en.xlf
  src/Build/Resources/xlf/Strings.es.xlf
  src/Build/Resources/xlf/Strings.fr.xlf
  src/Build/Resources/xlf/Strings.it.xlf
  src/Build/Resources/xlf/Strings.ja.xlf
  src/Build/Resources/xlf/Strings.ko.xlf
  src/Build/Resources/xlf/Strings.pl.xlf
  src/Build/Resources/xlf/Strings.pt-BR.xlf
  src/Build/Resources/xlf/Strings.ru.xlf
  src/Build/Resources/xlf/Strings.tr.xlf
  src/Build/Resources/xlf/Strings.zh-Hans.xlf
  src/Build/Resources/xlf/Strings.zh-Hant.xlf
  src/Shared/NativeMethodsShared.cs
  src/Shared/ProcessExtensions.cs
  src/Tasks.UnitTests/Exec_Tests.cs
  src/Utilities.UnitTests/ProcessExtensions_Tests.cs
  src/Utilities/Microsoft.Build.Utilities.csproj
  src/Utilities/ToolTask.cs
Labels: merge-when-branch-open
