Repository dotnet/msbuild, pull requests merged in 2022-01, with the labels that each got.

#7217 Force `IncludeEvaluationPropertiesAndItems` if escape hatch is set
  src/Build/BackEnd/Components/Logging/LoggingService.cs
Labels: merge-when-branch-open

#7152 Port doc comment changes from docs repo
  src/Build/Definition/ProjectCollection.cs
  src/Build/Logging/BinaryLogger/BinaryLogger.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
  src/Build/Logging/ProfilerLogger.cs
  src/Framework/Sdk/SdkReference.cs
  src/Framework/Sdk/SdkResolver.cs
  src/Framework/Sdk/SdkResolverContext.cs
  src/Framework/Sdk/SdkResult.cs
  src/Tasks/CodeTaskFactory.cs
  src/Tasks/Copy.cs
  src/Tasks/Hash.cs
  src/Tasks/Unzip.cs
Labels: merge-when-branch-open

#7165 Remove all checks regarding $(MSBuildAssemblyVersion) being set or not
  src/Tasks/Microsoft.CSharp.targets
  src/Tasks/Microsoft.Common.props
  src/Tasks/Microsoft.Common.targets
  src/Tasks/Microsoft.Common.tasks
  src/Tasks/Microsoft.NETFramework.props
  src/Tasks/Microsoft.NETFramework.targets
  src/Tasks/Microsoft.VisualBasic.targets
Labels: merge-when-branch-open

#7251 Disable CA1805
  eng/Common.globalconfig
Labels: merge-when-branch-open

#7248 Enable warning on CA1050
  eng/Common.globalconfig
Labels: merge-when-branch-open

#7247 Enable warning on SA1125
  eng/Common.globalconfig
Labels: merge-when-branch-open

#7246 Enable warning on SA1520
  eng/Common.globalconfig
Labels: merge-when-branch-open

#7199 SA1002 The spacing around a semicolon is incorrect
  eng/Common.globalconfig
  src/Build.OM.UnitTests/Construction/ConstructionEditing_Tests.cs
  src/Build.OM.UnitTests/Construction/ProjectRootElement_Tests.cs
  src/Build.OM.UnitTests/Definition/DefinitionEditing_Tests.cs
  src/Build.OM.UnitTests/Definition/Project_Tests.cs
  src/Build.OM.UnitTests/ObjectModelRemoting/LinkedSpecialCasesScenarios.cs
  src/Build.OM.UnitTests/ObjectModelRemoting/RemoteProjectsProviderMock/ConstructionLinkMocks/MockProjectUsingTaskParameterElementLink.cs
  src/Build/Construction/ProjectElementContainer.cs
  src/Build/Graph/ProjectGraph.cs
  src/Framework/Sdk/SdkResultItem.cs
  src/Shared/FileUtilities.cs
  src/Tasks.UnitTests/ResolveSDKReference_Tests.cs
Labels: merge-when-branch-open

#7185 CA1836 Prefer IsEmpty over Count
  eng/Common.globalconfig
  src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
  src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs
  src/Build/Evaluation/LazyItemEvaluator.RemoveOperation.cs
  src/Build/Logging/ProfilerLogger.cs
  src/Shared/RegisteredTaskObjectCacheBase.cs
  src/Tasks/GetSDKReferenceFiles.cs
Labels: merge-when-branch-open

#7173 Random cleanup
  src/Build.OM.UnitTests/Definition/Project_Tests.cs
  src/Build.UnitTests/BackEnd/AssemblyTaskFactory_Tests.cs
  src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
  src/Build.UnitTests/BackEnd/TargetBuilder_Tests.cs
  src/Build.UnitTests/BackEnd/TaskHostFactory_Tests.cs
  src/Build.UnitTests/EscapingInProjects_Tests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEntry.cs
  src/Build/BackEnd/Components/Caching/ConfigCache.cs
  src/Build/BackEnd/Components/Caching/ResultsCache.cs
  src/Build/BackEnd/Components/Communications/NodeManager.cs
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs
  src/Build/BackEnd/Components/Logging/LoggingService.cs
  src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs
  src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
  src/Build/BackEnd/Node/InProcNode.cs
  src/Build/BackEnd/Node/OutOfProcNode.cs
  src/Build/BackEnd/Shared/BuildRequestConfiguration.cs
  src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
  src/Build/Construction/ProjectRootElement.cs
  src/Build/Construction/Solution/SolutionFile.cs
  src/Build/Construction/Solution/SolutionProjectGenerator.cs
  src/Build/Definition/Project.cs
  src/Build/Definition/Toolset.cs
  src/Build/Evaluation/Expander.cs
  src/Build/Instance/TaskFactories/AssemblyTaskFactory.cs
  src/Build/Instance/TaskRegistry.cs
  src/Build/Logging/LoggerDescription.cs
  src/Build/Utilities/RegistryKeyWrapper.cs
  src/Framework/NativeMethods.cs
  src/MSBuild/OutOfProcTaskAppDomainWrapperBase.cs
  src/MSBuild/OutOfProcTaskHostNode.cs
  src/MSBuild/XMake.cs
  src/Shared/FileMatcher.cs
  src/Shared/LogMessagePacketBase.cs
  src/Shared/NodeEndpointOutOfProcBase.cs
  src/Shared/RegisteredTaskObjectCacheBase.cs
  src/Shared/TaskParameterTypeVerifier.cs
  src/Shared/UnitTests/ObjectModelHelpers.cs
  src/Tasks/AppConfig/BindingRedirect.cs
  src/Tasks/AssemblyDependency/AssemblyInformation.cs
  src/Tasks/AssemblyDependency/ReferenceTable.cs
  src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
  src/Tasks/Copy.cs
  src/Tasks/ErrorFromResources.cs
  src/Tasks/GenerateResource.cs
  src/Tasks/GenerateTrustInfo.cs
  src/Tasks/GetInstalledSDKLocations.cs
  src/Tasks/GetSDKReferenceFiles.cs
  src/Tasks/ManifestUtil/AssemblyIdentity.cs
  src/Tasks/ManifestUtil/SecurityUtil.cs
  src/Tasks/XamlTaskFactory/TaskParser.cs
  src/Tasks/XmlPeek.cs
  src/Tasks/XmlPoke.cs
  src/Tasks/XslTransformation.cs
  src/Utilities/MuxLogger.cs
  src/Utilities/PlatformManifest.cs
  src/Utilities/SDKManifest.cs
  src/Utilities/ToolLocationHelper.cs
Labels: merge-when-branch-open

#7254 Remove CultureName and CultureInfo from LazyFormattedBuildEventArgs
  src/Framework/LazyFormattedBuildEventArgs.cs
Labels: merge-when-branch-open

#7203 SA1136 place each enum value on its own line
  src/Build/Evaluation/Conditionals/Token.cs
  src/Build/Graph/ProjectInterpretation.cs
  src/Tasks.UnitTests/ResolveComReference_Tests.cs
  src/Tasks/BootstrapperUtil/Product.cs
  src/Tasks/FormatVersion.cs
  src/Tasks/GenerateApplicationManifest.cs
  src/Tasks/GenerateManifestBase.cs
  src/Tasks/StrongNameUtils.cs
Labels: merge-when-branch-open

#7263 SA1134 Each attribute should be placed on its own line of code
  eng/Common.globalconfig
  src/MSBuildTaskHost/Concurrent/ConcurrentQueue.cs
Labels: merge-when-branch-open

#7277 Revert "Add more SdkResolverService events and allow SdkResolvers to log events (#7139)"
  documentation/specs/event-source.md
  src/Build/BackEnd/Components/SdkResolution/CachingSdkResolverService.cs
  src/Build/BackEnd/Components/SdkResolution/OutOfProcNodeSdkResolverService.cs
  src/Framework/MSBuildEventSource.cs
  src/Framework/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Framework/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Framework/Sdk/SdkLogger.cs
Labels: Servicing-approved

#7162 Remove unnecessary allocations in Hash task.
  src/Tasks.UnitTests/Hash_Tests.cs
  src/Tasks/Hash.cs
Labels: performance, merge-when-branch-open

#7211 ItemDictionary<T>.Enumerator has an unnecessary finalizer
  src/Build/Collections/ItemDictionary.cs
Labels: merge-when-branch-open

#7261 SA1102 Query clause should follow previous clause
  eng/Common.globalconfig
  src/Shared/AssemblyFolders/AssemblyFoldersFromConfig.cs
Labels: merge-when-branch-open

#7270 SA1504 All accessors should be single-line or multi-line
  eng/Common.globalconfig
  src/Build/Construction/Solution/ProjectInSolution.cs
  src/Build/Definition/ProjectItem.cs
  src/Build/Evaluation/LazyItemEvaluator.OrderedItemDataCollection.cs
  src/Build/Instance/ProjectInstance.cs
  src/Build/Logging/BaseConsoleLogger.cs
  src/Framework/ReuseableStringBuilder.cs
  src/Tasks/AssemblyDependency/Reference.cs
  src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
  src/Tasks/GenerateResource.cs
Labels: merge-when-branch-open

#7303 Add targetpath metadata to file getting added to ContentWithTargetPath group
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#7197 SA1626 single-line comment which begins with three forward slashes in…
  src/Build.OM.UnitTests/Construction/ProjectExtensionsElement_Tests.cs
  src/Build.OM.UnitTests/ObjectModelRemoting/LinkedEvaluationModify_Tests.cs
  src/Build.OM.UnitTests/ObjectModelRemoting/RemoteProjectsProviderMock/EvaluationLinkMocks/MockProjectItemDefinitionLink.cs
  src/Build.OM.UnitTests/ObjectModelRemoting/RemoteProjectsProviderMock/EvaluationLinkMocks/MockProjectItemLink.cs
  src/Build.OM.UnitTests/ObjectModelRemoting/RemoteProjectsProviderMock/EvaluationLinkMocks/MockProjectLink.cs
  src/Build.OM.UnitTests/ObjectModelRemoting/RemoteProjectsProviderMock/EvaluationLinkMocks/MockProjectMetadataLink.cs
  src/Build.OM.UnitTests/ObjectModelRemoting/RemoteProjectsProviderMock/EvaluationLinkMocks/MockProjectPropertyLink.cs
  src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
  src/Build/Construction/ProjectRootElement.cs
  src/Build/Utilities/EngineFileUtilities.cs
  src/Tasks.UnitTests/AssemblyDependency/FilePrimary.cs
  src/Tasks.UnitTests/AssemblyDependency/NonSpecificVersionStrictPrimary.cs
  src/Tasks.UnitTests/AssemblyDependency/StronglyNamedDependencyAppConfig.cs
  src/Tasks.UnitTests/AssignProjectConfiguration_Tests.cs
Labels: merge-when-branch-open

#7268 SA1302 Interface names should begin with I
  eng/Common.globalconfig
  src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs
  src/Build.UnitTests/BackEnd/IntrinsicTask_Tests.cs
  src/Shared/UnitTests/ObjectModelHelpers.cs
  src/Tasks/NativeMethods.cs
  src/Tasks/RegisterAssembly.cs
Labels: merge-when-branch-open

#7274 SA1509 Opening braces should not be preceded by blank line
  eng/Common.globalconfig
  src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs
  src/Build/Utilities/EngineFileUtilities.cs
  src/MSBuild/CommandLineSwitchException.cs
  src/MSBuild/InitializationException.cs
  src/StringTools/StringTools.cs
  src/Tasks.UnitTests/XslTransformation_Tests.cs
Labels: merge-when-branch-open

#7278 Remove MSBuild.Engine.Corext
  MSBuild.sln
  src/Package/MSBuild.Engine.Corext/MSBuild.Engine.Corext.csproj
  src/Package/MSBuild.Engine.Corext/MSBuild.Engine.Corext.cxspec
  src/Package/MSBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec
  src/Package/MSBuild.Engine.Corext/README.md
  src/Package/MSBuild.Engine.Corext/TestBuild.cmd
Labels: Area: Our Own Build, merge-when-branch-open

#7279 Remove long-unused VS build things
  src/MSBuild/msbuild.suitebin.config
  src/MSBuild/msbuild_rascal.manifest
  src/MSBuild/xclpupdate.bat
  src/Packages.dgml
Labels: Area: Our Own Build, merge-when-branch-open

#7283 Start windowless process for the KillTree test
  src/Utilities.UnitTests/ProcessExtensions_Tests.cs
Labels: merge-when-branch-open

#7193 Remove extra usings
  src/Build.UnitTests/BackEnd/TaskExecutionHost_Tests.cs
  src/Build.UnitTests/EscapingInProjects_Tests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs
  src/Build/BackEnd/Components/Communications/NodeEndpointInProc.cs
  src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs
  src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupLoggingHelper.cs
  src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
  src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs
  src/Build/BackEnd/Node/NodeConfiguration.cs
  src/Build/BackEnd/Node/OutOfProcNode.cs
  src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
  src/Build/Construction/Solution/SolutionProjectGenerator.cs
  src/Build/Definition/Project.cs
  src/Build/Definition/ProjectCollection.cs
  src/Build/Definition/Toolset.cs
  src/Build/Evaluation/Evaluator.cs
  src/Build/Evaluation/Expander.cs
  src/Build/Instance/TaskFactories/AssemblyTaskFactory.cs
  src/Build/Logging/LoggerDescription.cs
  src/Directory.BeforeCommon.targets
  src/Framework/NativeMethods.cs
  src/Framework/TaskParameterEventArgs.cs
  src/MSBuild.UnitTests/PerfLog_Tests.cs
  src/MSBuild.UnitTests/XMake_Tests.cs
  src/MSBuild/OutOfProcTaskAppDomainWrapperBase.cs
  src/MSBuild/XMake.cs
  src/Shared/BuildEnvironmentHelper.cs
  src/Shared/ExceptionHandling.cs
  src/Shared/FileMatcher.cs
  src/Shared/LogMessagePacketBase.cs
  src/Shared/TaskLoader.cs
  src/Shared/ToolsetElement.cs
  src/Shared/UnitTests/EngineTestEnvironment.cs
  src/Shared/UnitTests/FileMatcher_Tests.cs
  src/Tasks/AssemblyDependency/AssemblyInformation.cs
  src/Tasks/GenerateResource.cs
  src/Tasks/GetReferenceAssemblyPaths.cs
  src/Tasks/ManifestUtil/SecurityUtil.cs
  src/Tasks/SGen.cs
Labels: merge-when-branch-open

#7280 MissingRestorePropertyError
  src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
  src/MSBuild/CommandLineSwitches.cs
Labels: merge-when-branch-open

#7289 Apply source-build patches
  src/Build/Microsoft.Build.csproj
  src/Directory.BeforeCommon.targets
  src/Directory.Build.props
  src/Samples/Directory.Build.props
  src/Tasks/Microsoft.Build.Tasks.csproj
  src/Utilities/Microsoft.Build.Utilities.csproj
Labels: merge-when-branch-open

#7291 Add NuGet package READMEs
  Directory.Build.targets
  documentation/consuming-nuget-package.md
  src/Build/README.md
  src/Deprecated/Conversion/README.md
  src/Deprecated/Engine/README.md
  src/Framework/README.md
  src/MSBuild/README.md
  src/StringTools/README.md
  src/Tasks/README.md
  src/Utilities/README.md
Labels: Area: Our Own Build, Area: API, merge-when-branch-open

#7295 Doc-commentify StringBuilderCache
  src/Framework/StringBuilderCache.cs
Labels: merge-when-branch-open

#7296 Reuse StringBuilders in EventArgsFormatting
  src/Framework/ReuseableStringBuilder.cs
  src/Shared/EventArgsFormatting.cs
Labels: performance, merge-when-branch-open

#7305 Improve the Project Cache log strings
  src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs
  src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs
  src/Build/Resources/Strings.resx
  src/Build/Resources/xlf/Strings.cs.xlf
  src/Build/Resources/xlf/Strings.de.xlf
  src/Build/Resources/xlf/Strings.es.xlf
  src/Build/Resources/xlf/Strings.fr.xlf
  src/Build/Resources/xlf/Strings.it.xlf
  src/Build/Resources/xlf/Strings.ja.xlf
  src/Build/Resources/xlf/Strings.ko.xlf
  src/Build/Resources/xlf/Strings.pl.xlf
  src/Build/Resources/xlf/Strings.pt-BR.xlf
  src/Build/Resources/xlf/Strings.ru.xlf
  src/Build/Resources/xlf/Strings.tr.xlf
  src/Build/Resources/xlf/Strings.zh-Hans.xlf
  src/Build/Resources/xlf/Strings.zh-Hant.xlf
  src/Framework/MSBuildEventSource.cs
Labels: merge-when-branch-open

#7307 Explain perf keywords
  src/Framework/MSBuildEventSource.cs
Labels: merge-when-branch-open

#7328 Fix import of x86 COM Component in ClickOnce Publish
  src/Tasks/ManifestUtil/ComImporter.cs
Labels: Servicing-approved, ClickOnce

#7190 CA2241 Provide correct arguments to formatting methods
  eng/Common.globalconfig
  src/Build.UnitTests/FileUtilitiesRegex_Tests.cs
Labels: merge-when-branch-open

#7294 Account for ARM64 in ProcessorArchitecture Tests
  src/Utilities.UnitTests/ProcessorArchitecture_Tests.cs
  src/Utilities/ToolLocationHelper.cs
Labels: merge-when-branch-open

#7302 Refactoring: use C# pattern matching for type checking & type casting.
  src/Build.UnitTests/BackEnd/CustomLogAndReturnTask.cs
  src/Build.UnitTests/BackEnd/LoggingServicesLogMethod_Tests.cs
  src/Build.UnitTests/ConsoleLogger_Tests.cs
  src/Build/BackEnd/Components/Logging/LoggingService.cs
  src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs
  src/Build/Evaluation/Expander.cs
  src/Build/Instance/ProjectTargetInstance.cs
  src/Build/Instance/TaskFactories/TaskHostTask.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsDispatcher.cs
  src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs
  src/Deprecated/Engine.UnitTests/FileLogger_Tests.cs
  src/Deprecated/Engine.UnitTests/Project_Tests.cs
  src/Deprecated/Engine/Collections/CopyOnWriteHashtable.cs
  src/Deprecated/Engine/Engine/Engine.cs
  src/Deprecated/Engine/Engine/EngineProxy.cs
  src/Deprecated/Engine/Engine/ToolsetReader.cs
  src/Deprecated/Engine/Logging/ConsoleLogger.cs
  src/Deprecated/Engine/Logging/DistributedLoggers/DistributedFileLogger.cs
  src/Deprecated/Engine/Shared/FileUtilities.cs
  src/Deprecated/Engine/Shared/FrameworkLocationHelper.cs
  src/Deprecated/Engine/Shared/UnitTests/MockEngine.cs
  src/Framework/Profiler/EvaluationLocation.cs
  src/Framework/Profiler/ProfilerResult.cs
  src/MSBuild/XMake.cs
  src/Shared/FileUtilitiesRegex.cs
  src/Shared/TaskParameter.cs
  src/Tasks/AssemblyDependency/GenerateBindingRedirects.cs
  src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
  src/Tasks/Exec.cs
  src/Tasks/GenerateManifestBase.cs
  src/Tasks/GenerateResource.cs
  src/Tasks/ManifestUtil/Manifest.cs
  src/Tasks/ManifestUtil/SecurityUtil.cs
  src/Tasks/ManifestUtil/mansign2.cs
  src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs
  src/Utilities/CommandLineBuilder.cs
  src/Utilities/PlatformManifest.cs
  src/Utilities/ToolLocationHelper.cs
Labels: performance, merge-when-branch-open

#7180 CA1823 Avoid unused private fields
  eng/Common.globalconfig
  src/Build/Collections/RetrievableEntryHashSet/HashSet.cs
  src/MSBuild.UnitTests/PerfLog_Tests.cs
  src/Shared/FileUtilities.cs
  src/Shared/UnitTests/EngineTestEnvironment.cs
  src/Tasks/GenerateResource.cs
  src/Tasks/LockCheck.cs
  src/Tasks/ManifestUtil/SecurityUtil.cs
  src/Tasks/ManifestUtil/Util.cs
  src/Tasks/ManifestUtil/mansign2.cs
  src/Tasks/NativeMethods.cs
  src/Tasks/ResolveKeySource.cs
  src/Tasks/ResolveSDKReference.cs
  src/Tasks/ResourceHandling/MSBuildResXReader.cs
Labels: merge-when-branch-open

#7304 Require VS 2022 to build this repo
  MSBuild.sln
  README.md
  documentation/wiki/Building-Testing-and-Debugging-on-Full-Framework-MSBuild.md
  global.json
Labels: merge-when-branch-open

#7326 MSBuild command line arguments aren't logged in dotnet build
  src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
  src/MSBuild/XMake.cs
Labels: merge-when-branch-open

#7306 Improved error message when created node crashes
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
Labels: merge-when-branch-open

#7333 Enable feature flags for things enabled in .NET Core 2.0
  src/Build.OM.UnitTests/Definition/ProjectCollection_Tests.cs
  src/Build.UnitTests/Construction/ElementLocation_Tests.cs
  src/Build.UnitTests/Evaluation/Expander_Tests.cs
  src/Build.UnitTests/Evaluation/ProjectStringCache_Tests.cs
  src/Build/BackEnd/BuildManager/BuildParameters.cs
  src/Build/BackEnd/Components/Communications/TranslatorExtensions.cs
  src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
  src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs
  src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
  src/Build/ElementLocation/XmlDocumentWithLocation.cs
  src/Build/Instance/ProjectInstance.cs
  src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs
  src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Build/Resources/Constants.cs
  src/Deprecated/Engine/Engine/Engine.cs
  src/Deprecated/Engine/Engine/Project.cs
  src/Deprecated/Engine/Engine/TargetCollection.cs
  src/Deprecated/Engine/Items/BuildItem.cs
  src/Deprecated/Engine/Microsoft.Build.Engine.csproj
  src/Directory.BeforeCommon.targets
  src/Framework/AssemblyUtilities.cs
  src/Framework/NativeMethods.cs
  src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
  src/MSBuild/CommandLineSwitches.cs
  src/MSBuild/XMake.cs
  src/Shared/BuildEventFileInfo.cs
  src/Shared/EnvironmentUtilities.cs
  src/Shared/ExceptionHandling.cs
  src/Shared/LogMessagePacketBase.cs
  src/Shared/TaskLoader.cs
Labels: merge-when-branch-open

#7179 CA1810 Initialize reference type static fields inline
  eng/Common.globalconfig
  src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupLoggingHelper.cs
  src/Build/Evaluation/ProjectRootElementCache.cs
  src/MSBuild/XMake.cs
  src/Shared/ExceptionHandling.cs
  src/Shared/FrameworkLocationHelper.cs
  src/Shared/MSBuildNameIgnoreCaseComparer.cs
  src/Shared/TypeLoader.cs
  src/Tasks/CultureInfoCache.cs
  src/Tasks/GenerateResource.cs
  src/Tasks/GetFrameworkPath.cs
  src/Utilities/TrackedDependencies/FileTracker.cs
Labels: merge-when-branch-open
