Repository dotnet/msbuild, pull requests merged in 2022-04, with the labels that each got.

#6928 Remove opt in for new schema for CombineTargetFrameworkInfoProperties
  src/Framework/ChangeWaves.cs
  src/Tasks/CombineTargetFrameworkInfoProperties.cs
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#7485 Always make bootstrap
  eng/BootStrapMSBuild.targets
Labels: merge-when-branch-open

#7538 Bump refs to System packages
  eng/Packages.props
  eng/dependabot/Packages.props
  src/Directory.Build.targets
  src/MSBuild/MSBuild.csproj
  src/StringTools.Benchmark/StringTools.Benchmark.csproj
Labels: Area: Our Own Build, merge-when-branch-open

#7517 Fix dotnet/msbuild#7504 DateTimeOffset property function
  src/Build/Resources/Constants.cs
Labels: merge-when-branch-open

#7483 Manage .NET6-only dependencies with Dependabot
  eng/Packages.props
  eng/dependabot/Packages.props
Labels: Area: Our Own Build, merge-when-branch-open

#7520 Respect deps.json
  src/Framework/ChangeWaves.cs
  src/Shared/MSBuildLoadContext.cs
  src/Shared/UnitTests/TypeLoader_Tests.cs
  src/Tasks/CombineTargetFrameworkInfoProperties.cs
Labels: merge-when-branch-open

#7547 Use Versions.props to eliminate source-build prebuilts
  eng/Packages.props
  eng/Versions.props
Labels: merge-when-branch-open

#7413 Fix low priority issues
  documentation/specs/low-priority-switch.md
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Components/Communications/INodeManager.cs
  src/Build/BackEnd/Components/Communications/INodeProvider.cs
  src/Build/BackEnd/Components/Communications/NodeEndpointOutOfProc.cs
  src/Build/BackEnd/Components/Communications/NodeManager.cs
  src/Build/BackEnd/Components/Communications/NodeProviderInProc.cs
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs
  src/Build/BackEnd/Components/Communications/TaskHostNodeManager.cs
  src/Build/BackEnd/Node/OutOfProcNode.cs
  src/MSBuild/XMake.cs
  src/MSBuildTaskHost/OutOfProcTaskHost.cs
Labels: merge-when-branch-open

#7541 Add Timeout parameter for the DownloadFile task
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
  src/Tasks/DownloadFile.cs
  src/Tasks/PublicAPI/net/PublicAPI.Shipped.txt
  src/Tasks/PublicAPI/netstandard/PublicAPI.Shipped.txt
Labels: merge-when-branch-open

#7536 Remove 16.10 changewave
  documentation/wiki/ChangeWaves-Dev.md
  documentation/wiki/ChangeWaves.md
  src/Build.UnitTests/Scanner_Tests.cs
  src/Build/Evaluation/Conditionals/Scanner.cs
  src/Build/Evaluation/Evaluator.cs
  src/Framework/ChangeWaves.cs
  src/Shared/FileMatcher.cs
  src/Tasks.UnitTests/AssignTargetPath_Tests.cs
  src/Tasks.UnitTests/Exec_Tests.cs
  src/Tasks/AssignTargetPath.cs
  src/Tasks/Exec.cs
Labels: merge-when-branch-open

#7467 Find assemblies by path from RoslynCodeTaskFactory Fixes #5106
  src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
  src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs
  src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs
Labels: merge-when-branch-open

#7408 project cache plugin cancellation fix
  src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs
Labels: merge-when-branch-open

#7436 Enable LockCheck on .NET on Windows
  src/Tasks.UnitTests/Copy_Tests.cs
  src/Tasks/Copy.cs
  src/Tasks/LockCheck.cs
Labels: merge-when-branch-open

#7539 Make ToolLocationHelper available on Core
  src/Shared/AssemblyFolders/AssemblyFoldersEx.cs
  src/Shared/RegistryDelegates.cs
  src/Shared/RegistryHelper.cs
  src/Utilities/AssemblyFolders/AssemblyFoldersExInfo.cs
  src/Utilities/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Utilities/ToolLocationHelper.cs
Labels: merge-when-branch-open

#7561 Put win32 back for .NET Standard
  src/Utilities/Microsoft.Build.Utilities.csproj
Labels: merge-when-branch-open

#7570 revert deps.json change
  src/Shared/MSBuildLoadContext.cs
  src/Shared/UnitTests/TypeLoader_Tests.cs
Labels: merge-when-branch-open

#7513 Parallelize Node Spawning
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Components/Communications/INodeManager.cs
  src/Build/BackEnd/Components/Communications/INodeProvider.cs
  src/Build/BackEnd/Components/Communications/NodeManager.cs
  src/Build/BackEnd/Components/Communications/NodeProviderInProc.cs
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs
  src/Build/BackEnd/Components/Communications/TaskHostNodeManager.cs
  src/Build/BackEnd/Components/IBuildComponent.cs
  src/Shared/CommunicationsUtilities.cs
Labels: merge-when-branch-open

#7492 LoggingService log contention
  src/Build.UnitTests/BackEnd/LoggingServiceFactory_Tests.cs
  src/Build.UnitTests/BackEnd/LoggingServicesLogMethod_Tests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Components/Logging/LoggingService.cs
  src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs
  src/Build/Definition/Project.cs
  src/Build/Definition/ProjectCollection.cs
Labels: merge-when-branch-open

#7554 Base64 converter Fixes #7442
  src/Build.UnitTests/Evaluation/Expander_Tests.cs
  src/Build/Evaluation/Expander.cs
  src/Build/Evaluation/IntrinsicFunctions.cs
Labels: merge-when-branch-open

#7577 Enable Live Unit Testing
  .gitignore
  MSBuild.lutconfig
Labels: Area: Our Own Build, merge-when-branch-open

#7540 [WIP-FEATURE] MSBuild client
  src/Build/BackEnd/Client/MSBuildClient.cs
  src/Build/BackEnd/Client/MSBuildClientExitResult.cs
  src/Build/BackEnd/Client/MSBuildClientExitType.cs
  src/Build/BackEnd/Client/MSBuildClientPacketPump.cs
  src/Build/BackEnd/Node/OutOfProcServerNode.cs
  src/Build/Microsoft.Build.csproj
  src/Build/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Framework/Traits.cs
  src/MSBuild/MSBuild.csproj
  src/MSBuild/MSBuildClientApp.cs
  src/MSBuild/XMake.cs
Labels: performance

#7585 Workaround mismatch type resolving
  src/Build/Instance/TaskRegistry.cs
Labels: merge-when-branch-open

#7567 Maybe fix flaky test
  src/Build.UnitTests/Evaluation/Evaluator_Tests.cs
Labels: merge-when-branch-open

#7560 Auto-detect that we need Core
  scripts/Deploy-MSBuild.ps1
Labels: merge-when-branch-open
