Repository dotnet/msbuild, pull requests merged in 2022-09, with the labels that each got.

#7968 Server shouldn't start during interactive build
  src/MSBuild.UnitTests/MSBuildServer_Tests.cs
  src/MSBuild/XMake.cs
Labels: merge-when-branch-open, Priority:0

#7879 Simplify import throwing logic
  src/Build/Evaluation/Evaluator.cs
Labels: merge-when-branch-open

#7962 Avoid stomping on SatelliteDllsProjectOutputGroupDependsOn
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#7708 Avoid building dwproj
  documentation/wiki/ChangeWaves.md
  src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
  src/Build/Xml/ProjectXmlUtilities.cs
Labels: merge-when-branch-open

#7926 Deduplicate list of assemblies loaded in TypeLoader
  src/Samples/PortableTask/PortableTask.csproj
  src/Shared/TypeLoader.cs
  src/Shared/UnitTests/TypeLoader_Tests.cs
Labels: merge-when-branch-open

#7928 Exempt our env var Fixes #7922
  src/Build/BackEnd/Components/Logging/ProjectLoggingContext.cs
  src/Build/Definition/ProjectProperty.cs
  src/Build/Evaluation/Evaluator.cs
  src/Build/Instance/ProjectPropertyInstance.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
  src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs
  src/Build/Logging/SerialConsoleLogger.cs
  src/Shared/EnvironmentUtilities.cs
  src/Utilities/MuxLogger.cs
Labels: merge-when-branch-open

#8000 Fallback when server launch fail due to create mutex error
  src/Build/BackEnd/Client/MSBuildClient.cs
Labels: merge-when-branch-open

#8002 Fix IsRidAgnostic fallback logic
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#8011 Ignore case when checking for pseudolocales
  src/Tasks.UnitTests/AssignCulture_Tests.cs
  src/Tasks/CultureInfoCache.cs
Labels: Servicing-approved

#8016 Restore console mode after server build
  src/Build/BackEnd/Client/MSBuildClient.cs
Labels: Servicing-approved
