Repository dotnet/msbuild, pull requests merged in 2022-08, with the labels that each got.

#7854 Enables logging when building metaprojects
  src/Build/Construction/Solution/SolutionProjectGenerator.cs
  src/Build/Instance/ProjectInstance.cs
Labels: merge-when-branch-open

#7855 RoslynCodeTaskFactory fix handling of Source and Type attributes on Code element (#7730)
  src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs
  src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs
Labels: merge-when-branch-open

#7857 Directory.CreateDirectory already checks if it exists
  src/Shared/ExceptionHandling.cs
Labels: merge-when-branch-open

#7852 BuildManager.ShutdownAllNodes shall shut down server as well
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Client/MSBuildClient.cs
  src/Build/BackEnd/Client/MSBuildClientPacketPump.cs
  src/Build/BackEnd/Node/OutOfProcServerNode.cs
  src/Build/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/MSBuild.UnitTests/MSBuildServer_Tests.cs
  src/Shared/UnitTests/TestEnvironment.cs
Labels: merge-when-branch-open

#7860 Read packet data in loop
  src/Build/BackEnd/Client/MSBuildClientPacketPump.cs
Labels: merge-when-branch-open

#7849 ProjectReference NuGet assets stuff is transitive
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Labels: merge-when-branch-open, Area: IntelliSense

#7861 Simplify labeler bot
  .github/fabricbot.json
Labels: merge-when-branch-open

#7853 Call New GetCultureInfo API When Validating Cultures
  src/Tasks.UnitTests/AssignCulture_Tests.cs
  src/Tasks/CultureInfoCache.cs
Labels: merge-when-branch-open

#7833 Refactor ProjectCacheService and fix various issues
  src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/BuildManager/BuildParameters.cs
  src/Build/BackEnd/Components/ProjectCache/ProjectCacheDescriptor.cs
  src/Build/BackEnd/Components/ProjectCache/ProjectCacheDescriptorEqualityComparer.cs
  src/Build/BackEnd/Components/ProjectCache/ProjectCacheItem.cs
  src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs
  src/Build/Evaluation/Evaluator.cs
  src/Build/PublicAPI/net/PublicAPI.Shipped.txt
  src/Build/PublicAPI/netstandard/PublicAPI.Shipped.txt
  src/Build/Resources/Strings.resx
  src/Build/Resources/xlf/Strings.cs.xlf
  src/Build/Resources/xlf/Strings.de.xlf
  src/Build/Resources/xlf/Strings.es.xlf
  src/Build/Resources/xlf/Strings.fr.xlf
  src/Build/Resources/xlf/Strings.it.xlf
  src/Build/Resources/xlf/Strings.ja.xlf
  src/Build/Resources/xlf/Strings.ko.xlf
  src/Build/Resources/xlf/Strings.pl.xlf
  src/Build/Resources/xlf/Strings.pt-BR.xlf
  src/Build/Resources/xlf/Strings.ru.xlf
  src/Build/Resources/xlf/Strings.tr.xlf
  src/Build/Resources/xlf/Strings.zh-Hans.xlf
  src/Build/Resources/xlf/Strings.zh-Hant.xlf
  src/Shared/UnitTests/ObjectModelHelpers.cs
Labels: merge-when-branch-open

#7871 Fix flaky CanShutdownServerProcess test
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Client/MSBuildClient.cs
  src/Build/BackEnd/Node/OutOfProcServerNode.cs
  src/MSBuild.UnitTests/MSBuildServer_Tests.cs
  src/UnitTests.Shared/RunnerUtilities.cs
Labels: merge-when-branch-open

#7877 Help Standalone MSBuild Find Its Family
  eng/Versions.props
  src/Shared/BuildEnvironmentHelper.cs
Labels: Servicing-consider

#7868 Fix for Scheduler using build parameter from previous build
  src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs
  src/Build/BackEnd/Components/Scheduler/Scheduler.cs
  src/Framework/Traits.cs
  src/MSBuild/XMake.cs
Labels: merge-when-branch-open

#7863 Cleanup / Remove some dead code from NodeEndpointOutOfProc
  src/Build/BackEnd/Components/Communications/NodeEndpointOutOfProc.cs
  src/Build/BackEnd/Node/OutOfProcNode.cs
Labels: merge-when-branch-open

#7901 Added proper config file for task host
  src/Package/MSBuild.VSSetup/files.swr
Labels: merge-when-branch-open

#7909 Update Change Waves env var in docs
  documentation/wiki/ChangeWaves-Dev.md
  documentation/wiki/ChangeWaves.md
  src/Build.UnitTests/ChangeWaves_Tests.cs
  src/Build/Resources/Strings.resx
  src/Build/Resources/xlf/Strings.cs.xlf
  src/Build/Resources/xlf/Strings.de.xlf
  src/Build/Resources/xlf/Strings.es.xlf
  src/Build/Resources/xlf/Strings.fr.xlf
  src/Build/Resources/xlf/Strings.it.xlf
  src/Build/Resources/xlf/Strings.ja.xlf
  src/Build/Resources/xlf/Strings.ko.xlf
  src/Build/Resources/xlf/Strings.pl.xlf
  src/Build/Resources/xlf/Strings.pt-BR.xlf
  src/Build/Resources/xlf/Strings.ru.xlf
  src/Build/Resources/xlf/Strings.tr.xlf
  src/Build/Resources/xlf/Strings.zh-Hans.xlf
  src/Build/Resources/xlf/Strings.zh-Hant.xlf
  src/Framework/ChangeWaves.cs
Labels: merge-when-branch-open

#7897 Ensure diagnostic logger verbosity Fixes #7780
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/MSBuild/XMake.cs
Labels: merge-when-branch-open
