Repository dotnet/msbuild, pull requests merged in 2022-03, with the labels that each got.

#7194 CA1200: Avoid using cref tags with a prefix
  eng/Common.globalconfig
  src/Build/Collections/RetrievableEntryHashSet/HashSet.cs
  src/Build/Construction/ProjectElementContainer.cs
  src/Build/Definition/ProjectCollection.cs
  src/Build/Graph/ProjectGraph.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
  src/Framework/NativeMethods.cs
  src/Framework/Sdk/SdkResolver.cs
  src/MSBuildTaskHost/Concurrent/ConcurrentDictionary.cs
  src/Tasks/Hash.cs
  src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs
Labels: merge-when-branch-open

#7398 Adopt sbom
  .vsts-dotnet.yml
Labels: merge-when-branch-open

#7426 Remove CS8632 suppression
  src/Framework/Microsoft.Build.Framework.csproj
Labels: Area: Our Own Build, merge-when-branch-open

#7401 .NET SDK 6.0.200
  global.json
Labels: merge-when-branch-open

#7244 Simplify MainNodeSdkResolverService
  src/Build/BackEnd/Components/SdkResolution/MainNodeSdkResolverService.cs
Labels: merge-when-branch-open

#6148 MSBuild Upgrade: netstandard2.0 -> net6.0
  eng/Packages.props
  src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
  src/Directory.BeforeCommon.targets
  src/Directory.Build.props
  src/Framework/NativeMethods.cs
  src/Framework/README.md
  src/Framework/Sdk/SdkResultItem.cs
  src/Framework/SupportedOSPlatform.cs
  src/MSBuild/MSBuild.csproj
  src/MSBuildTaskHost/MSBuildTaskHost.csproj
  src/Samples/PortableTask/PortableTask.csproj
  src/StringTools/InternableString.cs
  src/StringTools/WeakStringCache.Concurrent.cs
  src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs
  src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
  src/Tasks/BootstrapperUtil/BootstrapperBuilder.cs
  src/Tasks/BootstrapperUtil/Util.cs
  src/Tasks/DownloadFile.cs
  src/Tasks/FormatUrl.cs
  src/Tasks/GenerateApplicationManifest.cs
  src/Tasks/GenerateDeploymentManifest.cs
  src/Tasks/GenerateLauncher.cs
  src/Tasks/GenerateManifestBase.cs
  src/Tasks/ManifestUtil/ComImporter.cs
  src/Tasks/ManifestUtil/FileReference.cs
  src/Tasks/ManifestUtil/SecurityUtil.cs
  src/Tasks/ManifestUtil/Util.cs
  src/Tasks/ManifestUtil/mansign2.cs
  src/Tasks/Microsoft.Build.Tasks.csproj
  src/Tasks/NativeMethods.cs
  src/Tasks/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Tasks/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Tasks/Resources/Strings.resx
  src/Tasks/Resources/xlf/Strings.cs.xlf
  src/Tasks/Resources/xlf/Strings.de.xlf
  src/Tasks/Resources/xlf/Strings.es.xlf
  src/Tasks/Resources/xlf/Strings.fr.xlf
  src/Tasks/Resources/xlf/Strings.it.xlf
  src/Tasks/Resources/xlf/Strings.ja.xlf
  src/Tasks/Resources/xlf/Strings.ko.xlf
  src/Tasks/Resources/xlf/Strings.pl.xlf
  src/Tasks/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Resources/xlf/Strings.ru.xlf
  src/Tasks/Resources/xlf/Strings.tr.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/SignFile.cs
  src/Utilities/README.md
Labels: merge-when-branch-open

#7029 Throw exception or log warning upon drive enumeration glob anomaly detection
  src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs
  src/Build.OM.UnitTests/Instance/ProjectItemInstance_Tests.cs
  src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs
  src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
  src/Build/Definition/Project.cs
  src/Build/Evaluation/Evaluator.cs
  src/Build/Evaluation/Expander.cs
  src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs
  src/Build/Utilities/EngineFileUtilities.cs
  src/Framework/Traits.cs
  src/Shared/FileMatcher.cs
  src/Shared/Resources/Strings.shared.resx
  src/Shared/Resources/xlf/Strings.shared.cs.xlf
  src/Shared/Resources/xlf/Strings.shared.de.xlf
  src/Shared/Resources/xlf/Strings.shared.es.xlf
  src/Shared/Resources/xlf/Strings.shared.fr.xlf
  src/Shared/Resources/xlf/Strings.shared.it.xlf
  src/Shared/Resources/xlf/Strings.shared.ja.xlf
  src/Shared/Resources/xlf/Strings.shared.ko.xlf
  src/Shared/Resources/xlf/Strings.shared.pl.xlf
  src/Shared/Resources/xlf/Strings.shared.pt-BR.xlf
  src/Shared/Resources/xlf/Strings.shared.ru.xlf
  src/Shared/Resources/xlf/Strings.shared.tr.xlf
  src/Shared/Resources/xlf/Strings.shared.zh-Hans.xlf
  src/Shared/Resources/xlf/Strings.shared.zh-Hant.xlf
  src/Shared/UnitTests/FileMatcher_Tests.cs
  src/Shared/UnitTests/ObjectModelHelpers.cs
  src/Tasks.UnitTests/CreateItem_Tests.cs
  src/Tasks/CreateItem.cs
  src/Tasks/Microsoft.Build.Tasks.csproj
  src/Utilities/TrackedDependencies/TrackedDependencies.cs
Labels: merge-when-branch-open

#7431 Added MSBuild server doc (communication protocol)
  documentation/MSBuild-Server.md
Labels: performance

#7434 Fix dotnet/msbuild#7428 Enhancement: Add System.Environment::NewLine as a supported static property
  src/Build/Resources/Constants.cs
Labels: merge-when-branch-open

#7404 Fixes dotnet / msbuild#6313 FormatUrl
  src/Tasks.UnitTests/FormatUrl_Tests.cs
  src/Tasks/FormatUrl.cs
  src/Tasks/LC.cs
  src/Tasks/ManifestUtil/PathUtil.cs
  src/Tasks/ResolveComReference.cs
Labels: merge-when-branch-open

#7476 Fix missing transitive dependencies
  src/Build/Graph/GraphBuilder.cs
Labels: Partner request, merge-when-branch-open

#7450 Capture output in XMake_Tests
  src/MSBuild.UnitTests/XMake_Tests.cs
Labels: merge-when-branch-open, Area: Tests

#7471 Stop disabling CA1416 Fixes #6376
  src/Framework/NativeMethods.cs
  src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs
  src/Tasks.UnitTests/Copy_Tests.cs
Labels: merge-when-branch-open

#7469 Remove duplicate app.config entries Fixes #7451
  src/MSBuild/app.amd64.config
  src/MSBuild/app.config
Labels: merge-when-branch-open

#7454 Make DeepCopyFrom (for ProjectElementContainers) copy all descendants instead of just the direct children
  src/Build.OM.UnitTests/Construction/ProjectItemGroupElement_tests.cs
  src/Build/Construction/ProjectElementContainer.cs
Labels: merge-when-branch-open

#7366 Ensure path writable for MSBuildDebugEngine
  src/MSBuild/Resources/Strings.resx
  src/MSBuild/Resources/xlf/Strings.cs.xlf
  src/MSBuild/Resources/xlf/Strings.de.xlf
  src/MSBuild/Resources/xlf/Strings.es.xlf
  src/MSBuild/Resources/xlf/Strings.fr.xlf
  src/MSBuild/Resources/xlf/Strings.it.xlf
  src/MSBuild/Resources/xlf/Strings.ja.xlf
  src/MSBuild/Resources/xlf/Strings.ko.xlf
  src/MSBuild/Resources/xlf/Strings.pl.xlf
  src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
  src/MSBuild/Resources/xlf/Strings.ru.xlf
  src/MSBuild/Resources/xlf/Strings.tr.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
  src/MSBuild/XMake.cs
  src/Shared/Debugging/DebugUtils.cs
  src/Shared/FileUtilities.cs
  src/Utilities/Resources/Strings.resx
  src/Utilities/Resources/xlf/Strings.cs.xlf
  src/Utilities/Resources/xlf/Strings.de.xlf
  src/Utilities/Resources/xlf/Strings.es.xlf
  src/Utilities/Resources/xlf/Strings.fr.xlf
  src/Utilities/Resources/xlf/Strings.it.xlf
  src/Utilities/Resources/xlf/Strings.ja.xlf
  src/Utilities/Resources/xlf/Strings.ko.xlf
  src/Utilities/Resources/xlf/Strings.pl.xlf
  src/Utilities/Resources/xlf/Strings.pt-BR.xlf
  src/Utilities/Resources/xlf/Strings.ru.xlf
  src/Utilities/Resources/xlf/Strings.tr.xlf
  src/Utilities/Resources/xlf/Strings.zh-Hans.xlf
  src/Utilities/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open
