Repository dotnet/msbuild, pull requests merged in 2022-06, with the labels that each got.

#7655 Solving memory leak by reusing BuildManager and ProjectRoolElementCache
  src/Build/Definition/ProjectCollection.cs
  src/Build/Evaluation/ProjectRootElementCache.cs
  src/Build/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/MSBuild/XMake.cs
Labels: performance

#7649 Properly recover from SDK resolver exception.
  src/Build/BackEnd/Components/SdkResolution/MainNodeSdkResolverService.cs
Labels: merge-when-branch-open

#7661 Put msbuild server feature under ChangeWave 17.4.
  documentation/wiki/ChangeWaves.md
  src/MSBuild/XMake.cs
Labels: performance

#7668 Add support for MSBUILDDEBUGONSTART for msbuild server.
  src/MSBuild/XMake.cs
Labels: performance

#7480 Implement Platform Negotiation in ProjectGraph
  src/Build.UnitTests/Graph/GetCompatiblePlatformGraph_Tests.cs
  src/Build/BackEnd/Shared/ConfigurationMetadata.cs
  src/Build/Graph/GraphBuilder.cs
  src/Build/Graph/ProjectInterpretation.cs
  src/Build/Microsoft.Build.csproj
  src/Shared/PlatformNegotiation.cs
  src/Tasks/GetCompatiblePlatform.cs
  src/Tasks/Microsoft.Build.Tasks.csproj
Labels: merge-when-branch-open

#7673 Fix msbuild server process launch.
  src/Build/BackEnd/Client/MSBuildClient.cs
  src/Build/BackEnd/Components/Communications/CurrentHost.cs
  src/Build/BackEnd/Components/Communications/NodeLauncher.cs
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
  src/Build/Microsoft.Build.csproj
  src/Build/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/MSBuild/MSBuildClientApp.cs
Labels: performance

#7592 Add test for MSBuild Server
  src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj
  src/Build.OM.UnitTests/NugetRestoreTests.cs
  src/Build/BackEnd/Client/MSBuildClient.cs
  src/Framework/Microsoft.Build.Framework.csproj
  src/MSBuild.UnitTests/MSBuildServer_Tests.cs
  src/MSBuild.UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj
  src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
  src/UnitTests.Shared/RunnerUtilities.cs
Labels: performance

#7696 CopyParallel - break from loop if cancellation was requested
  src/Tasks/Copy.cs
Labels: Area: Tasks, merge-when-branch-open

#7715 Make environment-derived properties change opt-in and read at use time
  src/Build.UnitTests/BinaryLogger_Tests.cs
  src/Framework/Traits.cs
Labels: merge-when-branch-open

#7699 Cleaning up msbuild static graph setplatform negotiation logic
  src/Build.UnitTests/Graph/GetCompatiblePlatformGraph_Tests.cs
  src/Build/BackEnd/Shared/ConfigurationMetadata.cs
  src/Build/Graph/GraphBuilder.cs
  src/Build/Graph/ProjectInterpretation.cs
Labels: merge-when-branch-open

#7735 Hide new internal dependencies
  src/MSBuild/MSBuild.csproj
Labels: Area: Our Own Build

#7737 Update Newtonsoft.Json in test projects
  eng/dependabot/Packages.props
  src/Directory.Build.targets
Labels: Area: Our Own Build

#7724 Update to .NET SDK 6.0.301
  global.json
Labels: Area: Our Own Build

#7741 Stop ngen for resource assemblies
  src/Package/MSBuild.VSSetup.Arm64/files.arm64.swr
  src/Package/MSBuild.VSSetup/files.swr
Labels: Area: Visual Studio

#7745 MSBuild Server: Always run MSBuild nodes with MSBUILDUSESERVER disabled.
  src/Build/BackEnd/Client/MSBuildClient.cs
  src/Build/BackEnd/Components/Communications/NodeLauncher.cs
Labels: performance
