Repository dotnet/msbuild, pull requests merged in 2022-10, with the labels that each got.

#7887 Reduce unnecessary allocations when accessing information about global properties
  src/Build/BackEnd/Shared/ConfigurationMetadata.cs
  src/Build/Definition/Project.cs
  src/Build/Definition/ProjectCollection.cs
  src/Build/Definition/ProjectProperty.cs
  src/Build/Instance/ProjectInstance.cs
  src/Build/ObjectModelRemoting/DefinitionObjectsLinks/ProjectLink.cs
  src/Build/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt
Labels: merge-when-branch-open

#7893 Specialcase UAP == windows
  src/Tasks.UnitTests/ResolveSDKReference_Tests.cs
  src/Tasks/ResolveSDKReference.cs
Labels: merge-when-branch-open

#7955 Support for Arm64 immutable directories fast file up to date check
  src/Build/Definition/ToolsetReader.cs
  src/Framework/FileClassifier.cs
  src/MSBuild/app.amd64.config
  src/MSBuild/app.config
Labels: merge-when-branch-open

#7999 Undeclared projects needs to be normalized and case insensitive so that the current project can be ignored properly
  src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
  src/Shared/FileUtilities.cs
Labels: merge-when-branch-open

#8020 Update docker tag to the latest schema
  .vsts-dotnet-ci.yml
  .vsts-dotnet.yml
Labels: merge-when-branch-open

#7945 Fix processor count on Windows for multiple processor groups
  src/Framework/NativeMethods.cs
Labels: merge-when-branch-open

#7979 Support ItemDefinitionGroup in Choose/When
  src/Build.UnitTests/Parser_Tests.cs
  src/Build/Construction/ProjectItemDefinitionGroupElement.cs
  src/Build/Evaluation/Evaluator.cs
  src/Build/Evaluation/ProjectParser.cs
Labels: merge-when-branch-open

#7989 Fix issue 7828: enabling the binary logger adds console output
  src/Build.UnitTests/BinaryLogger_Tests.cs
  src/MSBuild/XMake.cs
Labels: merge-when-branch-open

#7975 ngen arm64 binaries as arm64
  src/Package/MSBuild.VSSetup.Arm64/files.arm64.swr
Labels: merge-when-branch-open

#8013 Restore newline auto return
  src/Build/BackEnd/Client/MSBuildClient.cs
  src/Framework/NativeMethods.cs
Labels: merge-when-branch-open

#7998 Log each inner exception of an aggregate exception in TaskLoggingHelper.LogErrorFromException()
  src/Shared/TaskLoggingHelper.cs
  src/Utilities.UnitTests/TaskLoggingHelper_Tests.cs
Labels: merge-when-branch-open

#8064 README: mention long paths
  README.md
Labels: merge-when-branch-open

#7840 Add note when updating system.memory
  eng/Packages.props
  eng/Versions.props
Labels: merge-when-branch-open

#7965 Eliminate project string cache under a change wave.
  documentation/wiki/ChangeWaves.md
  src/Build.OM.UnitTests/Construction/ProjectRootElement_Tests.cs
  src/Build.UnitTests/Evaluation/ProjectStringCache_Tests.cs
  src/Build/Evaluation/ProjectStringCache.cs
  src/Framework/ChangeWaves.cs
Labels: performance, merge-when-branch-open

#8066 Fix Microsoft.NET.StringTools netstandard2.0 pack
  src/Directory.Build.props
  src/StringTools/StringTools.csproj
Labels: Servicing-approved

#8063 [Project Cache] Fix CacheResult.CreateTaskItem
  src/Build/BackEnd/Components/ProjectCache/CacheResult.cs
Labels: merge-when-branch-open

#8062 Update to .NET SDK RC2
  global.json
Labels: merge-when-branch-open

#8069 Avoid losing the exception stack in BuildManager.EndBuild
  src/Build/BackEnd/BuildManager/BuildManager.cs
Labels: merge-when-branch-open

#8070 Fix race condition with ProjectCacheService disposal and background initialization
  src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
Labels: merge-when-branch-open

#8073 Fix wrong architecture detection in tests.
  src/Shared/UnitTests/XmakeAttributes_Tests.cs
Labels: merge-when-branch-open

#8083 Update Building-Testing-and-Debugging-on-.Net-Core-MSBuild.md
  documentation/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild.md
Labels: merge-when-branch-open

#8078 Fixed some URLs in the documentation
  documentation/wiki/Binary-Log.md
  documentation/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild.md
  documentation/wiki/Building-Testing-and-Debugging-on-Full-Framework-MSBuild.md
  documentation/wiki/Building-Testing-and-Debugging-on-Mono-MSBuild.md
  documentation/wiki/Contributing-Code.md
  documentation/wiki/Contributing-Tasks.md
  documentation/wiki/Localization.md
  documentation/wiki/MSBuild-Resources.md
  documentation/wiki/MSBuild-Tips-&-Tricks.md
  documentation/wiki/Microsoft.Build.Framework.md
  documentation/wiki/Rebuilding-when-nothing-changed.md
  documentation/wiki/ResolveAssemblyReference.md
  documentation/wiki/Target-Maps.md
  documentation/wiki/UnGAC.md
Labels: merge-when-branch-open
