Repository dotnet/msbuild, pull requests merged in 2022-02, with the labels that each got.

#7323 Provide option to fail ClickOnce publish if RFC3161 timestamping fails.
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
  src/Tasks/ManifestUtil/SecurityUtil.cs
  src/Tasks/ManifestUtil/mansign2.cs
  src/Tasks/Microsoft.Common.CurrentVersion.targets
  src/Tasks/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Tasks/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Tasks/SignFile.cs
Labels: merge-when-branch-open

#7005 msbuild overview doc
  documentation/Contributions/MSBuild-overview.md
  documentation/Contributions/README.md
  documentation/Home.md
  documentation/wiki/Home.md
Labels: merge-when-branch-open

#7342 Fix dotnet/msbuild#5884: Add EnsureSingleQuoted and EnsureDoubleQuoted
  src/Shared/FileUtilities.cs
  src/Shared/UnitTests/FileUtilities_Tests.cs
  src/UnitTests.Shared/RunnerUtilities.cs
Labels: merge-when-branch-open

#7361 Fix handling of relative paths when using graph builds with implicit restore
  src/Build/Graph/GraphBuilder.cs
  src/Build/Graph/ProjectGraphEntryPoint.cs
Labels: merge-when-branch-open

#7186 CA1838 Avoid 'StringBuilder' parameters for P/Invokes
  eng/Common.globalconfig
  src/Framework/NativeMethods.cs
  src/Tasks/AssemblyDependency/AssemblyInformation.cs
  src/Tasks/AssemblyDependency/GlobalAssemblyCache.cs
  src/Tasks/ComReference.cs
  src/Tasks/LockCheck.cs
  src/Tasks/NativeMethods.cs
  src/Tasks/ResolveComReference.cs
Labels: merge-when-branch-open

#7363 Remove unnecessary package dependency on System.Net.Http package.
  src/Tasks/Microsoft.Build.Tasks.csproj
Labels: merge-when-branch-open

#7309 Implement warnnotaserror Fixes #3062
  src/Build.UnitTests/BackEnd/MockLoggingService.cs
  src/Build.UnitTests/BackEnd/TaskHostConfiguration_Tests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/BuildManager/BuildParameters.cs
  src/Build/BackEnd/Components/Logging/ILoggingService.cs
  src/Build/BackEnd/Components/Logging/LoggingService.cs
  src/Build/BackEnd/Components/Logging/TaskLoggingContext.cs
  src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
  src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs
  src/Build/Instance/TaskFactories/TaskHostTask.cs
  src/Build/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
  src/MSBuild.UnitTests/XMake_Tests.cs
  src/MSBuild/CommandLineSwitches.cs
  src/MSBuild/OutOfProcTaskHostNode.cs
  src/MSBuild/Resources/Strings.resx
  src/MSBuild/Resources/xlf/Strings.cs.xlf
  src/MSBuild/Resources/xlf/Strings.de.xlf
  src/MSBuild/Resources/xlf/Strings.es.xlf
  src/MSBuild/Resources/xlf/Strings.fr.xlf
  src/MSBuild/Resources/xlf/Strings.it.xlf
  src/MSBuild/Resources/xlf/Strings.ja.xlf
  src/MSBuild/Resources/xlf/Strings.ko.xlf
  src/MSBuild/Resources/xlf/Strings.pl.xlf
  src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
  src/MSBuild/Resources/xlf/Strings.ru.xlf
  src/MSBuild/Resources/xlf/Strings.tr.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
  src/MSBuild/XMake.cs
  src/Shared/Constants.cs
  src/Shared/TaskHostConfiguration.cs
Labels: merge-when-branch-open

#7386 Opt into IncludeEvaluationPropertiesAndItems in NullLogger
  src/Build/BackEnd/BuildManager/BuildManager.cs
Labels: Area: Logging, merge-when-branch-open

#7245 Add solution parser documentation
  documentation/Contributions/solution-parser.md
Labels: merge-when-branch-open

#7213 Provide nice error when an environment variable is not expanded on the command line, including the full command line for all switch errors Fixes #7210
  src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
  src/MSBuild.UnitTests/ProjectSchemaValidationHandler_Tests.cs
  src/MSBuild.UnitTests/XMake_Tests.cs
  src/MSBuild/CommandLineSwitches.cs
  src/MSBuild/Resources/Strings.resx
  src/MSBuild/Resources/xlf/Strings.cs.xlf
  src/MSBuild/Resources/xlf/Strings.de.xlf
  src/MSBuild/Resources/xlf/Strings.es.xlf
  src/MSBuild/Resources/xlf/Strings.fr.xlf
  src/MSBuild/Resources/xlf/Strings.it.xlf
  src/MSBuild/Resources/xlf/Strings.ja.xlf
  src/MSBuild/Resources/xlf/Strings.ko.xlf
  src/MSBuild/Resources/xlf/Strings.pl.xlf
  src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
  src/MSBuild/Resources/xlf/Strings.ru.xlf
  src/MSBuild/Resources/xlf/Strings.tr.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
  src/MSBuild/XMake.cs
  src/Shared/UnitTests/TestEnvironment.cs
Labels: merge-when-branch-open

#7367 Better evaluator errors Fixes #6460
  src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
  src/Build/Evaluation/LazyItemEvaluator.cs
  src/Build/Resources/Strings.resx
  src/Build/Resources/xlf/Strings.cs.xlf
  src/Build/Resources/xlf/Strings.de.xlf
  src/Build/Resources/xlf/Strings.es.xlf
  src/Build/Resources/xlf/Strings.fr.xlf
  src/Build/Resources/xlf/Strings.it.xlf
  src/Build/Resources/xlf/Strings.ja.xlf
  src/Build/Resources/xlf/Strings.ko.xlf
  src/Build/Resources/xlf/Strings.pl.xlf
  src/Build/Resources/xlf/Strings.pt-BR.xlf
  src/Build/Resources/xlf/Strings.ru.xlf
  src/Build/Resources/xlf/Strings.tr.xlf
  src/Build/Resources/xlf/Strings.zh-Hans.xlf
  src/Build/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open

#6783 Allow an Override Flag in UsingTasks
  src/Build.UnitTests/BackEnd/TaskRegistry_Tests.cs
  src/Build/Construction/ProjectUsingTaskElement.cs
  src/Build/Evaluation/ProjectParser.cs
  src/Build/Instance/TaskRegistry.cs
  src/Build/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Build/Resources/Strings.resx
  src/Build/Resources/xlf/Strings.cs.xlf
  src/Build/Resources/xlf/Strings.de.xlf
  src/Build/Resources/xlf/Strings.es.xlf
  src/Build/Resources/xlf/Strings.fr.xlf
  src/Build/Resources/xlf/Strings.it.xlf
  src/Build/Resources/xlf/Strings.ja.xlf
  src/Build/Resources/xlf/Strings.ko.xlf
  src/Build/Resources/xlf/Strings.pl.xlf
  src/Build/Resources/xlf/Strings.pt-BR.xlf
  src/Build/Resources/xlf/Strings.ru.xlf
  src/Build/Resources/xlf/Strings.tr.xlf
  src/Build/Resources/xlf/Strings.zh-Hans.xlf
  src/Build/Resources/xlf/Strings.zh-Hant.xlf
  src/Shared/ConversionUtilities.cs
  src/Shared/XMakeAttributes.cs
Labels: merge-when-branch-open, review-by-diff

#7297 Support ProjectConfigurationDescription when SDK loggers are attached
  src/Build.UnitTests/ConsoleLogger_Tests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs
  src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs
  src/MSBuild.UnitTests/XMake_Tests.cs
  src/MSBuild/XMake.cs
  src/Shared/EventArgsFormatting.cs
Labels: Area: Logging, merge-when-branch-open

#7415 Revert "Loosen version comparisons in loading assemblies (#7042)"
  eng/Versions.props
  src/Shared/CoreCLRAssemblyLoader.cs
  src/Shared/MSBuildLoadContext.cs
Labels: Servicing-approved
