Repository dotnet/msbuild, pull requests merged in 2022-07, with the labels that each got.

#7802 Preserve original stack for graph build submission exceptions
  src/Build/BackEnd/BuildManager/BuildManager.cs
Labels: merge-when-branch-open

#7797 Make BuildEventContext.Invalid a singleton
  src/Framework/BuildEventContext.cs
Labels: merge-when-branch-open

#7785 Add PublishAot to CommonTypes and fix a couple comments
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Labels: merge-when-branch-open, Area: IntelliSense

#7816 Fix msbuild client exit type for connection errors.
  src/Build/BackEnd/Client/MSBuildClient.cs
  src/Build/BackEnd/Client/MSBuildClientExitType.cs
  src/Build/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/MSBuild/MSBuildClientApp.cs
Labels: performance

#7795 Disable Microsoft.IO.Redist in source-build.
  src/Build/FileSystem/DirectoryCacheFileSystemWrapper.cs
  src/Directory.BeforeCommon.targets
  src/Shared/FileMatcher.cs
Labels: merge-when-branch-open

#7818 Link to new canonical-error doc
  src/Shared/TaskLoggingHelper.cs
Labels: Documentation, merge-when-branch-open

#7798 Use package version properties for dependabot project during source build
  eng/dependabot/Packages.props
Labels: merge-when-branch-open

#7692 Allow Opt-Out When Importing Platforms from ProjectConfiguration
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open, Area: SetPlatform

#7810 Check derivable from ITaskItem directly
  src/Build.UnitTests/BackEnd/AssemblyTaskFactory_Tests.cs
  src/Build.UnitTests/BackEnd/TaskExecutionHost_Tests.cs
  src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
  src/MSBuildTaskHost/TypeLoader.cs
  src/Shared/LoadedType.cs
  src/Shared/TypeLoader.cs
Labels: Servicing-approved

#7817 Fix Graph and ProjectCache UTs
  src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
  src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Shared/UnitTests/ObjectModelHelpers.cs
Labels: merge-when-branch-open

#7812 Don't allocate closure objects when enumerating properties
  src/Build/Logging/BaseConsoleLogger.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
  src/Build/Utilities/Utilities.cs
  src/Shared/LogMessagePacketBase.cs
Labels: merge-when-branch-open

#7823 Reuse singleton comparer instance in build logger
  src/Build/Logging/BaseConsoleLogger.cs
Labels: performance, Area: Logging, merge-when-branch-open

#7809 Don't use hardcoded package versions
  eng/Packages.props
  eng/Versions.props
Labels: merge-when-branch-open

#7831 Simplify exception handling for graph builds
  src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
  src/Build.UnitTests/Graph/GraphLoadedFromSolution_tests.cs
  src/Build.UnitTests/Graph/ParallelWorkSet_Tests.cs
  src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/Graph/GraphBuildResult.cs
  src/Build/Graph/ParallelWorkSet.cs
  src/MSBuild/XMake.cs
Labels: merge-when-branch-open

#7830 Account for FileTrackerA4 in LoadFileTrackerDll
  src/Shared/InprocTrackingNativeMethods.cs
Labels: merge-when-branch-open

#7820 Fix incorrect WarningsAsErrors elements
  src/StringTools/StringTools.csproj
Labels: merge-when-branch-open

#7813 Null annotate some build event args types
  src/Framework/BuildEventArgs.cs
  src/Framework/BuildEventContext.cs
  src/Framework/BuildFinishedEventArgs.cs
  src/Framework/BuildStartedEventArgs.cs
  src/Framework/BuildStatusEventArgs.cs
  src/Framework/LazyFormattedBuildEventArgs.cs
  src/Framework/ProjectEvaluationFinishedEventArgs.cs
  src/Framework/ProjectEvaluationStartedEventArgs.cs
  src/Framework/ProjectFinishedEventArgs.cs
  src/Framework/ProjectStartedEventArgs.cs
  src/Shared/BinaryReaderExtensions.cs
  src/Shared/BinaryWriterExtensions.cs
Labels: merge-when-branch-open

#7803 SetPlatform Negotiation: No global properties during GetTargetFrameworks
  src/Shared/PlatformNegotiation.cs
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#7786 Reduce allocations in ProjectCollection locking
  src/Build/Definition/ProjectCollection.cs
  src/Build/Microsoft.Build.csproj
  src/Build/Utilities/ReaderWriterLockSlimExtensions.cs
Labels: performance, Area: Engine, merge-when-branch-open

#7685 Prevent symlink cycle
  src/Directory.BeforeCommon.targets
  src/Shared/FileMatcher.cs
  src/Shared/UnitTests/FileMatcher_Tests.cs
  src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
Labels: Area: Engine, merge-when-branch-open

#7736 XamlTaskFactory prefers msbuild's root directory when finding dll's
  src/Tasks/XamlTaskFactory/XamlTaskFactory.cs
Labels: Area: Tasks, merge-when-branch-open

#7826 Sbom for VS insertion
  .vsts-dotnet.yml
  global.json
Labels: merge-when-branch-open

#7836 Revert "Sbom for VS insertion (#7826)"
  .vsts-dotnet.yml
  global.json
Labels: merge-when-branch-open

#7512 [Opt-in] Parallelize Targets when building a solution
  src/Build.UnitTests/BackEnd/MSBuild_Tests.cs
  src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
  src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/MSBuild.cs
  src/Build/Construction/Solution/SolutionProjectGenerator.cs
  src/Framework/Traits.cs
  src/Tasks.UnitTests/MSBuild_Tests.cs
  src/Tasks/MSBuild.cs
Labels: merge-when-branch-open

#7838 Disable server for nodereuse:false
  src/MSBuild.UnitTests/MSBuildServer_Tests.cs
  src/MSBuild/XMake.cs
Labels: merge-when-branch-open

#7839 Setplatform stop config from overriding platforms
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: Servicing-approved

#7837 [Graph] Fix target list when there are multiple ProjectReferences with different Targets metadata
  src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
  src/Build/Graph/GraphBuilder.cs
  src/Build/Graph/ProjectGraph.cs
  src/Build/Graph/ProjectGraphNode.cs
  src/Build/Graph/ProjectInterpretation.cs
Labels: merge-when-branch-open

#7844 Fix ProjectReferenceTargets for Publish and Rebuild
  src/Tasks/Microsoft.Managed.After.targets
Labels: merge-when-branch-open
