Repository dotnet/msbuild, pull requests merged in 2022-11, with the labels that each got.

#8085 Configure OptProf v2 pipeline
  .opt-prof.yml
  .vsts-dotnet.yml
  eng/config/OptProf.runsettings
Labels: merge-when-branch-open

#8111 enable producing reference assemblies by default
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#8089 Mention MSBUILDDEBUGENGINE in Tips&Tricks
  documentation/wiki/MSBuild-Tips-&-Tricks.md
Labels: merge-when-branch-open

#8096 Remove wave 17_0
  documentation/wiki/ChangeWaves.md
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs
  src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs
  src/Build/BackEnd/Components/Scheduler/Scheduler.cs
  src/Build/Definition/ToolsetConfigurationReader.cs
  src/Build/Globbing/MSBuildGlob.cs
  src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs
  src/Framework/ChangeWaves.cs
  src/Framework/NativeMethods.cs
  src/Shared/CommunicationsUtilities.cs
  src/Shared/ExceptionHandling.cs
  src/Shared/FileSystem/ManagedFileSystem.cs
  src/Shared/ToolsetElement.cs
  src/Shared/UnitTests/FileMatcher_Tests.cs
  src/Tasks/AssemblyDependency/ReferenceTable.cs
Labels: merge-when-branch-open

#8106 Fixing overbuilding of platform negotiated projects
  src/Shared/PlatformNegotiation.cs
  src/Tasks.UnitTests/GetCompatiblePlatform_Tests.cs
Labels: Partner request, merge-when-branch-open

#8092 AsOrdered was removed
  src/Build/Definition/Project.cs
Labels: merge-when-branch-open

#8122 Create problematic test path on current tmp path
  src/Build.UnitTests/BackEnd/BuildRequestConfiguration_Tests.cs
Labels: merge-when-branch-open

#8114 DisableTransitiveProjectReferences is not required for SetPlatform
  documentation/ProjectReference-Protocol.md
Labels: merge-when-branch-open

#8101 Use `EntryPointNodes` in lieu of `GraphRoots` in `GetTargetLists` (#8…
  src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
  src/Build/Graph/ProjectGraph.cs
Labels: merge-when-branch-open

#8110 Fix CodeQL bug about a zip slip
  src/Tasks/Resources/Strings.resx
  src/Tasks/Resources/xlf/Strings.cs.xlf
  src/Tasks/Resources/xlf/Strings.de.xlf
  src/Tasks/Resources/xlf/Strings.es.xlf
  src/Tasks/Resources/xlf/Strings.fr.xlf
  src/Tasks/Resources/xlf/Strings.it.xlf
  src/Tasks/Resources/xlf/Strings.ja.xlf
  src/Tasks/Resources/xlf/Strings.ko.xlf
  src/Tasks/Resources/xlf/Strings.pl.xlf
  src/Tasks/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Resources/xlf/Strings.ru.xlf
  src/Tasks/Resources/xlf/Strings.tr.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Unzip.cs
Labels: merge-when-branch-open

#8098 Batch metadata updates for better performance
  src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
  src/Build/Instance/ProjectItemInstance.cs
Labels: merge-when-branch-open

#8087 Update 17.2 from 17.0
  .vsts-dotnet.yml
  src/Build.OM.UnitTests/Definition/Project_Tests.cs
  src/Build.UnitTests/Construction/SolutionFile_Tests.cs
  src/Tasks.UnitTests/Exec_Tests.cs
Labels: merge-when-branch-open

#8125 Added logging message for tasks that fail without error
  src/Build.UnitTests/BackEnd/OnError_Tests.cs
  src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
Labels: merge-when-branch-open

#8135 Copy XSDs only in outer build
  src/MSBuild/MSBuild.csproj
Labels: merge-when-branch-open

#8136 [Unzip] Only add trailing slash to dest. directory when needed
  src/Tasks/Unzip.cs
Labels: merge-when-branch-open

#8141 Set BuildParameters.StartupDirectory upon build command
  src/Build/BackEnd/BuildManager/BuildParameters.cs
  src/Build/BackEnd/Node/OutOfProcServerNode.cs
  src/MSBuild.UnitTests/MSBuildServer_Tests.cs
Labels: merge-when-branch-open

#8143 Use OptProf v2 data in CI builds
  .vsts-dotnet.yml
Labels: performance, merge-when-branch-open

#8095 Log an error when no provided search path for an import exists
  documentation/wiki/ChangeWaves.md
  src/Build/Evaluation/Evaluator.cs
Labels: merge-when-branch-open

#8127 Remove Bootstrap Property from Onboarding Docs
  README.md
  documentation/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild.md
  documentation/wiki/Building-Testing-and-Debugging-on-Full-Framework-MSBuild.md
Labels: merge-when-branch-open

#8150 Update 17.3 from 17.2
  .vsts-dotnet.yml
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/build.ps1
  eng/common/generate-sbom-prep.ps1
  eng/common/generate-sbom-prep.sh
  eng/common/init-tools-native.ps1
  eng/common/internal/NuGet.config
  eng/common/internal/Tools.csproj
  eng/common/sdl/sdl.ps1
  eng/common/templates/job/execute-sdl.yml
  eng/common/templates/job/onelocbuild.yml
  eng/common/templates/job/source-build.yml
  eng/common/templates/jobs/jobs.yml
  eng/common/templates/post-build/post-build.yml
  eng/common/templates/steps/execute-sdl.yml
  eng/common/tools.ps1
  global.json
  src/Build.OM.UnitTests/Definition/Project_Tests.cs
  src/Build.UnitTests/Construction/SolutionFile_Tests.cs
  src/Tasks.UnitTests/Exec_Tests.cs
Labels: merge-when-branch-open

#8185 Build DetermineWhetherSerializedObjectLoads less
  src/Tasks/GenerateResource.cs
Labels: merge-when-branch-open

#8181 SimpleVersion.Parse() ignores leading and trailing whitespace
  src/Build.UnitTests/Evaluation/SimpleVersion_Tests.cs
  src/Build/Utilities/SimpleVersion.cs
Labels: merge-when-branch-open

#8157 Fix Copy with UseSymbolicLinksIfPossible = true
  src/Tasks.UnitTests/Copy_Tests.cs
  src/Tasks/NativeMethods.cs
Labels: merge-when-branch-open

#7690 Add Microsoft.Build.dll to the arm64 directory
  eng/BootStrapMSBuild.targets
  src/Package/MSBuild.VSSetup.Arm64/files.arm64.swr
Labels: merge-when-branch-open

#8193 Fix the malformed test transforming an item allows access to metadata value
  src/Build.UnitTests/Evaluation/Evaluator_Tests.cs
Labels: merge-when-branch-open

#8198 Drop the net35 asset from the StringTools package
  src/StringTools/StringTools.csproj
Labels: merge-when-branch-open
