Repository dotnet/msbuild, pull requests merged in 2023-03, with the labels that each got.

#8473 Fix Mac ARM64 unit tests.
  src/Shared/BuildEnvironmentHelper.cs
Labels: merge-when-branch-open

#8287 Simpler loop structures
  src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEntry.cs
  src/Build/BackEnd/Components/RequestBuilder/TargetUpToDateChecker.cs
  src/Build/BackEnd/Components/Scheduler/Scheduler.cs
  src/Build/BackEnd/Components/Scheduler/SchedulingPlan.cs
  src/Build/BackEnd/Shared/BuildResult.cs
  src/Framework/ITaskItemExtensions.cs
  src/Framework/XamlTypes/ProjectSchemaDefinitions.cs
  src/MSBuild/OutOfProcTaskHostNode.cs
  src/Tasks/AssemblyDependency/ReferenceTable.cs
  src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
  src/Tasks/ResolveSDKReference.cs
  src/Utilities/TrackedDependencies/CanonicalTrackedInputFiles.cs
  src/Utilities/TrackedDependencies/CanonicalTrackedOutputFiles.cs
Labels: merge-when-branch-open

#8265 Only log task started once
  src/Build.UnitTests/BackEnd/TaskBuilder_Tests.cs
  src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
Labels: merge-when-branch-open

#8222 fixing global properties error in Dynamic platform resolution
  src/Build.UnitTests/Graph/GetCompatiblePlatformGraph_Tests.cs
  src/Build/Graph/ProjectInterpretation.cs
Labels: merge-when-branch-open

#8533 Add ProjectOptions.Interactive so that callers can specify that project evaluation can be interactive
  src/Build.UnitTests/Definition/Project_Internal_Tests.cs
  src/Build.UnitTests/Instance/ProjectInstance_Internal_Tests.cs
  src/Build/Definition/Project.cs
  src/Build/Definition/ProjectOptions.cs
  src/Build/Instance/ProjectInstance.cs
Labels: merge-when-branch-open

#8485 net35 task host properly handle isolated AppDomain tasks
  src/Shared/LoadedType.cs
Labels: merge-when-branch-open

#8526 Consider XML cache valid if loaded from non modifiable file
  src/Build/Evaluation/ProjectRootElementCache.cs
Labels: performance, merge-when-branch-open, Iteration:2023March

#8532 Add resource for failing to copy via hardlink
  src/Tasks/NativeMethods.cs
Labels: merge-when-branch-open

#8543 Add doc for InvariantGlobalization property
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Labels: merge-when-branch-open

#8548 [Bugfix] Do not read Location of dynamic assemblies
  src/Build/BackEnd/Components/RequestBuilder/AssemblyLoadsTracker.cs
Labels: merge-when-branch-open

#8552 BuildManager instances acquire its own BuildTelemetry instance (#8444)
  eng/Build.props
  eng/Versions.props
  src/Build.UnitTests/BackEnd/KnownTelemetry_Tests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Client/MSBuildClient.cs
  src/Build/BackEnd/Node/OutOfProcServerNode.cs
  src/Framework/Telemetry/KnownTelemetry.cs
  src/MSBuild/MSBuildClientApp.cs
  src/MSBuild/XMake.cs
Labels: Servicing-consider

#8522 Move ResolveSdkStop event to finally
  src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs
Labels: merge-when-branch-open

#8333 Improve PFX error message
  src/Tasks/ResolveKeySource.cs
  src/Tasks/Resources/Strings.resx
  src/Tasks/Resources/xlf/Strings.cs.xlf
  src/Tasks/Resources/xlf/Strings.de.xlf
  src/Tasks/Resources/xlf/Strings.es.xlf
  src/Tasks/Resources/xlf/Strings.fr.xlf
  src/Tasks/Resources/xlf/Strings.it.xlf
  src/Tasks/Resources/xlf/Strings.ja.xlf
  src/Tasks/Resources/xlf/Strings.ko.xlf
  src/Tasks/Resources/xlf/Strings.pl.xlf
  src/Tasks/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Resources/xlf/Strings.ru.xlf
  src/Tasks/Resources/xlf/Strings.tr.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open

#8560 Trim away netframework targets in source-build
  eng/SourceBuild.props
Labels: merge-when-branch-open

#8557 Log DownloadFile error stack trace to low priority message
  src/Tasks/DownloadFile.cs
Labels: merge-when-branch-open

#8561 Concurrency bug fix - BuildManager instances acquire its own BuildTelemetry instance (#8444)
  eng/Build.props
  eng/Versions.props
  src/Build.UnitTests/BackEnd/KnownTelemetry_Tests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Client/MSBuildClient.cs
  src/Build/BackEnd/Node/OutOfProcServerNode.cs
  src/Framework/Telemetry/KnownTelemetry.cs
  src/MSBuild/MSBuildClientApp.cs
  src/MSBuild/XMake.cs
Labels: Servicing-consider

#8275 Issue8273 corrupt nu get cache
  src/Tasks.UnitTests/Copy_Tests.cs
  src/Tasks/Copy.cs
  src/Tasks/NativeMethods.cs
Labels: merge-when-branch-open

#8558 Change WriteCodeFragment task to create directory
  src/Tasks.UnitTests/WriteCodeFragment_Tests.cs
  src/Tasks/WriteCodeFragment.cs
Labels: merge-when-branch-open

#8572 Add per-file locking to ProjectRootElementCache
  src/Build/Evaluation/ProjectRootElementCache.cs
Labels: merge-when-branch-open

#8575 Use AutoResetEvent as oppose to ManualResetEventSlim
  eng/Versions.props
  src/Build/BackEnd/Components/Logging/LoggingService.cs
Labels: performance, Servicing-approved

#8590 Consolidate solution configuration xml parsing logic
  src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs
  src/Build/Construction/Solution/SolutionProjectGenerator.cs
  src/Build/Microsoft.Build.csproj
  src/Shared/SolutionConfiguration.cs
  src/Tasks/AssignProjectConfiguration.cs
  src/Tasks/Microsoft.Build.Tasks.csproj
  src/Tasks/ResolveProjectBase.cs
Labels: merge-when-branch-open

#8583 Tell bot to only post when a PR is opened or reopened and let it target more servicing branches
  .github/fabricbot.json
Labels: merge-when-branch-open

#8540 ProjectRootElementCache.Clear do not clear immutable files
  src/Build/Evaluation/ProjectRootElementCache.cs
Labels: merge-when-branch-open

#8566 Jennybai/issue8517
  .github/ISSUE_TEMPLATE/06_feature_request.yml
Labels: merge-when-branch-open

#8603 Any have metadata value when empty Fixes #5113
  documentation/wiki/ChangeWaves.md
  src/Build.UnitTests/Evaluation/Expander_Tests.cs
  src/Build/Evaluation/Expander.cs
Labels: merge-when-branch-open

#8606 Demote WriteLinesToFile warning to message
  src/Tasks.UnitTests/WriteLinesToFile_Tests.cs
  src/Tasks/FileIO/WriteLinesToFile.cs
Labels: merge-when-branch-open

#8524 Add warning for using BinaryFormatter in GenerateResource on .NET 8
  src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs
  src/Tasks.UnitTests/ResourceHandling/MSBuildResXReader_Tests.cs
  src/Tasks.UnitTests/ResourceHandling/ResGenDependencies_Tests.cs
  src/Tasks/GenerateResource.cs
  src/Tasks/Microsoft.Common.CurrentVersion.targets
  src/Tasks/ResGenDependencies.cs
  src/Tasks/ResourceHandling/MSBuildResXReader.cs
  src/Tasks/Resources/Strings.resx
  src/Tasks/Resources/xlf/Strings.cs.xlf
  src/Tasks/Resources/xlf/Strings.de.xlf
  src/Tasks/Resources/xlf/Strings.es.xlf
  src/Tasks/Resources/xlf/Strings.fr.xlf
  src/Tasks/Resources/xlf/Strings.it.xlf
  src/Tasks/Resources/xlf/Strings.ja.xlf
  src/Tasks/Resources/xlf/Strings.ko.xlf
  src/Tasks/Resources/xlf/Strings.pl.xlf
  src/Tasks/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Resources/xlf/Strings.ru.xlf
  src/Tasks/Resources/xlf/Strings.tr.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open
