Repository dotnet/msbuild, pull requests merged in 2023-04, with the labels that each got.

#8608 Localize response-file-used message
  src/MSBuild/Resources/Strings.resx
  src/MSBuild/Resources/xlf/Strings.cs.xlf
  src/MSBuild/Resources/xlf/Strings.de.xlf
  src/MSBuild/Resources/xlf/Strings.es.xlf
  src/MSBuild/Resources/xlf/Strings.fr.xlf
  src/MSBuild/Resources/xlf/Strings.it.xlf
  src/MSBuild/Resources/xlf/Strings.ja.xlf
  src/MSBuild/Resources/xlf/Strings.ko.xlf
  src/MSBuild/Resources/xlf/Strings.pl.xlf
  src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
  src/MSBuild/Resources/xlf/Strings.ru.xlf
  src/MSBuild/Resources/xlf/Strings.tr.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
  src/MSBuild/XMake.cs
Labels: merge-when-branch-open

#8626 Clarify what .default means
  documentation/specs/static-graph.md
Labels: merge-when-branch-open

#8620 Move EncodingUtilities to Framework
  src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj
  src/Build/Microsoft.Build.csproj
  src/Framework/EncodingUtilities.cs
  src/Tasks/Microsoft.Build.Tasks.csproj
  src/Utilities/Microsoft.Build.Utilities.csproj
Labels: merge-when-branch-open

#8506 Document 'Resolve Assembly Reference core scenarios'
  documentation/design/rar-core-scenarios.md
Labels: Documentation, merge-when-branch-open

#8638 Fix flaky test CanShutdownServerProcess
  src/Build/BackEnd/Client/MSBuildClient.cs
  src/MSBuild.UnitTests/MSBuildServer_Tests.cs
Labels: merge-when-branch-open

#8630 Change IDE0055 (Fix Formatting) warning->message
  .editorconfig
Labels: Area: Our Own Build, merge-when-branch-open

#8544 Reset internal terminated flag in ToolTask (#8541)
  src/Utilities.UnitTests/ToolTask_Tests.cs
  src/Utilities/ToolTask.cs
Labels: merge-when-branch-open

#8637 Delete src/MSBuild/Properties/launchSettings.json
  .gitignore
  src/MSBuild/Properties/launchSettings.json
Labels: merge-when-branch-open

#8646 Avoid overly-specific cast in bulk metadata copy
  eng/Versions.props
  src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
Labels: Servicing-approved

#8619 LiveLogger v2
  src/Build/BackEnd/Client/MSBuildClient.cs
  src/Build/BackEnd/Components/Logging/LoggingService.cs
  src/Framework/NativeMethods.cs
  src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
  src/MSBuild.UnitTests/LiveLogger_Tests.cs
  src/MSBuild.UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj
  src/MSBuild.UnitTests/MockTerminal.cs
  src/MSBuild/CommandLineSwitches.cs
  src/MSBuild/LiveLogger/ANSIBuilder.cs
  src/MSBuild/LiveLogger/AnsiCodes.cs
  src/MSBuild/LiveLogger/BuildMessage.cs
  src/MSBuild/LiveLogger/ITerminal.cs
  src/MSBuild/LiveLogger/LiveLogger.cs
  src/MSBuild/LiveLogger/MessageNode.cs
  src/MSBuild/LiveLogger/MessageSeverity.cs
  src/MSBuild/LiveLogger/Project.cs
  src/MSBuild/LiveLogger/ProjectNode.cs
  src/MSBuild/LiveLogger/TargetNode.cs
  src/MSBuild/LiveLogger/TaskNode.cs
  src/MSBuild/LiveLogger/Terminal.cs
  src/MSBuild/LiveLogger/TerminalBuffer.cs
  src/MSBuild/MSBuild.csproj
  src/MSBuild/XMake.cs
  src/Shared/StringExtensions.cs
Labels: merge-when-branch-open, size:7, Iteration:2023March, Iteration:2023April

#8653 Add diagnostics to symlink embedding unittest
  src/Build.UnitTests/BinaryLogger_Tests.cs
  src/UnitTests.Shared/RequiresSymbolicLinksFactAttribute.cs
Labels: merge-when-branch-open

#8581 Log item self-expansion
  documentation/wiki/ChangeWaves.md
  src/Build.UnitTests/BackEnd/MSBuild_Tests.cs
  src/Build/BackEnd/Components/Logging/LoggingContext.cs
  src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs
  src/Build/Definition/ProjectItemDefinition.cs
  src/Build/Evaluation/Expander.cs
  src/Build/Evaluation/IItemTypeDefinition.cs
  src/Build/Instance/ProjectItemDefinitionInstance.cs
  src/Build/Instance/ProjectItemInstance.cs
  src/Build/Microsoft.Build.csproj
  src/Build/Resources/Strings.resx
  src/Build/Resources/xlf/Strings.cs.xlf
  src/Build/Resources/xlf/Strings.de.xlf
  src/Build/Resources/xlf/Strings.es.xlf
  src/Build/Resources/xlf/Strings.fr.xlf
  src/Build/Resources/xlf/Strings.it.xlf
  src/Build/Resources/xlf/Strings.ja.xlf
  src/Build/Resources/xlf/Strings.ko.xlf
  src/Build/Resources/xlf/Strings.pl.xlf
  src/Build/Resources/xlf/Strings.pt-BR.xlf
  src/Build/Resources/xlf/Strings.ru.xlf
  src/Build/Resources/xlf/Strings.tr.xlf
  src/Build/Resources/xlf/Strings.zh-Hans.xlf
  src/Build/Resources/xlf/Strings.zh-Hant.xlf
Labels: Feature: Warning Waves, merge-when-branch-open

#8667 Update .NetSDK
  global.json
Labels: merge-when-branch-open

#8665 Unify "used response file" messages
  src/MSBuild/Resources/Strings.resx
  src/MSBuild/Resources/xlf/Strings.cs.xlf
  src/MSBuild/Resources/xlf/Strings.de.xlf
  src/MSBuild/Resources/xlf/Strings.es.xlf
  src/MSBuild/Resources/xlf/Strings.fr.xlf
  src/MSBuild/Resources/xlf/Strings.it.xlf
  src/MSBuild/Resources/xlf/Strings.ja.xlf
  src/MSBuild/Resources/xlf/Strings.ko.xlf
  src/MSBuild/Resources/xlf/Strings.pl.xlf
  src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
  src/MSBuild/Resources/xlf/Strings.ru.xlf
  src/MSBuild/Resources/xlf/Strings.tr.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
  src/MSBuild/XMake.cs
Labels: merge-when-branch-open

#8434 Update `ProjectReference` docs
  documentation/ProjectReference-Protocol.md
  documentation/specs/single-project-isolated-builds.md
  documentation/specs/static-graph.md
Labels: Documentation, merge-when-branch-open

#8669 Avoid package dependencies on inbox libraries
  documentation/Changelog.md
  eng/Packages.props
  src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj
  src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
  src/Build/Microsoft.Build.csproj
  src/Framework.UnitTests/Microsoft.Build.Framework.UnitTests.csproj
  src/MSBuild.UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj
  src/Samples/ProjectCachePlugin/ProjectCachePlugin.csproj
  src/StringTools.UnitTests/StringTools.UnitTests.csproj
  src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
  src/Tasks/Microsoft.Build.Tasks.csproj
  src/Utilities.UnitTests/Microsoft.Build.Utilities.UnitTests.csproj
Labels: merge-when-branch-open

#8680 ItemSpec: Do not call MatchCount when count is not needed
  src/Build/Evaluation/ItemSpec.cs
Labels: merge-when-branch-open

#8666 Add tsa config file to enable validation pipeline
  eng/sdl-tsa-vars.config
Labels: merge-when-branch-open

#8659 NoProfile in ToolTaskThatTimeoutAndRetry test
  src/Utilities.UnitTests/ToolTask_Tests.cs
Labels: merge-when-branch-open

#8599 Ensure metadata location when created from xml element with known location
  src/Build.OM.UnitTests/Construction/ProjectItemElement_Tests.cs
  src/Build.UnitTests/BackEnd/MSBuild_Tests.cs
  src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs
  src/Build/Construction/ProjectMetadataElement.cs
  src/Build/Construction/ProjectRootElement.cs
  src/Build/ElementLocation/XmlDocumentWithLocation.cs
  src/Build/Evaluation/ProjectParser.cs
  src/Shared/UnitTests/MockLogger.cs
  src/Shared/UnitTests/ObjectModelHelpers.cs
  src/Shared/XmlUtilities.cs
Labels: merge-when-branch-open

#8690 Update Providing-Binary-Logs.md
  documentation/wiki/Providing-Binary-Logs.md
Labels: merge-when-branch-open

#8686 Revert "Issue8273 corrupt nu get cache (#8275)"
  eng/Versions.props
  src/Tasks.UnitTests/Copy_Tests.cs
  src/Tasks/Copy.cs
  src/Tasks/NativeMethods.cs
Labels: merge-when-branch-open

#8494 Document references peculiarities
  documentation/README.md
  documentation/wiki/Controlling-Dependencies-Behavior.md
Labels: Documentation, merge-when-branch-open

#8660 GetReferenceAssemblyPaths continues on error in design-time builds
  src/Tasks/Microsoft.Common.CurrentVersion.targets
Labels: merge-when-branch-open

#8656 Add readonly to struct methods
  .editorconfig
  src/Build/Collections/ConvertingEnumerable.cs
  src/Build/Construction/ProjectElementContainer.cs
  src/Build/Definition/Project.cs
  src/Build/Definition/ToolsetReader.cs
  src/Build/Evaluation/Expander.cs
  src/Build/Evaluation/ItemsAndMetadataPair.cs
  src/Build/Evaluation/LazyItemEvaluator.cs
  src/Build/Graph/ProjectGraph.cs
  src/Build/Graph/ProjectGraphEntryPoint.cs
  src/Build/Xml/ProjectXmlUtilities.XmlElementChildIterator.cs
  src/Deprecated/Engine/ItemsAndProperties/ExpressionShredder.cs
  src/Framework/BuildEngineResult.cs
  src/Framework/NativeMethods.cs
  src/Framework/Profiler/EvaluationLocation.cs
  src/Shared/FileMatcher.cs
  src/Shared/FileSystem/WindowsNative.cs
  src/Shared/Pair.cs
  src/StringTools/InternableString.Simple.cs
  src/StringTools/InternableString.cs
  src/StringTools/SpanBasedStringBuilder.Simple.cs
  src/Tasks/AssemblyDependency/AssemblyNameReference.cs
  src/Tasks/ComDependencyWalker.cs
Labels: merge-when-branch-open

#8689 Fix outputIsScreen on non-windows OS.
  src/Framework/NativeMethods.cs
Labels: merge-when-branch-open

#8682 [LiveLogger ] Localize strings
  src/MSBuild.UnitTests/MockTerminal.cs
  src/MSBuild/LiveLogger/ITerminal.cs
  src/MSBuild/LiveLogger/LiveLogger.cs
  src/MSBuild/LiveLogger/Terminal.cs
  src/MSBuild/Resources/Strings.resx
  src/MSBuild/Resources/xlf/Strings.cs.xlf
  src/MSBuild/Resources/xlf/Strings.de.xlf
  src/MSBuild/Resources/xlf/Strings.es.xlf
  src/MSBuild/Resources/xlf/Strings.fr.xlf
  src/MSBuild/Resources/xlf/Strings.it.xlf
  src/MSBuild/Resources/xlf/Strings.ja.xlf
  src/MSBuild/Resources/xlf/Strings.ko.xlf
  src/MSBuild/Resources/xlf/Strings.pl.xlf
  src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
  src/MSBuild/Resources/xlf/Strings.ru.xlf
  src/MSBuild/Resources/xlf/Strings.tr.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open

#8702 Using URI file schema for Live Logger hyperlinks
  src/MSBuild/LiveLogger/LiveLogger.cs
Labels: merge-when-branch-open

#8625 Emulate AssignProjectConfiguration behavior in graph construction
  eng/Versions.props
  src/Build.UnitTests/Graph/GraphLoadedFromSolution_tests.cs
  src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
  src/Build/Construction/Solution/SolutionProjectGenerator.cs
  src/Build/Graph/GraphBuilder.cs
  src/Build/Graph/ProjectInterpretation.cs
  src/Shared/SolutionConfiguration.cs
  src/Tasks/AssignProjectConfiguration.cs
Labels: Servicing-approved

#8692 Emit relative path to output
  src/MSBuild/LiveLogger/LiveLogger.cs
Labels: merge-when-branch-open
