Repository dotnet/msbuild, pull requests merged in 2023-05, with the labels that each got.

#8716 Let env find bash
  build.sh
Labels: merge-when-branch-open

#8715 Colorize TF instead of enclosing it in brackets
  src/MSBuild/LiveLogger/AnsiCodes.cs
  src/MSBuild/LiveLogger/ITerminal.cs
  src/MSBuild/LiveLogger/LiveLogger.cs
  src/MSBuild/LiveLogger/TerminalColor.cs
  src/MSBuild/Resources/Strings.resx
  src/MSBuild/Resources/xlf/Strings.cs.xlf
  src/MSBuild/Resources/xlf/Strings.de.xlf
  src/MSBuild/Resources/xlf/Strings.es.xlf
  src/MSBuild/Resources/xlf/Strings.fr.xlf
  src/MSBuild/Resources/xlf/Strings.it.xlf
  src/MSBuild/Resources/xlf/Strings.ja.xlf
  src/MSBuild/Resources/xlf/Strings.ko.xlf
  src/MSBuild/Resources/xlf/Strings.pl.xlf
  src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
  src/MSBuild/Resources/xlf/Strings.ru.xlf
  src/MSBuild/Resources/xlf/Strings.tr.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open, livelogger

#8712 Deemphasize MSBUILDDEBUGENGINE in binlog doc
  documentation/wiki/Providing-Binary-Logs.md
Labels: merge-when-branch-open

#8701 Reorganize docs
  documentation/README.md
  documentation/specs/archive/rar-as-service.md
  documentation/specs/rar-core-scenarios.md
Labels: Documentation, merge-when-branch-open

#8695 [vs17.2] Customize opt-in for CG step
  .vsts-dotnet.yml
  eng/Versions.props
Labels: Area: Our Own Build, merge-when-branch-open

#8683 Add source generated files properties to project XSD
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Labels: merge-when-branch-open

#8727 Remove stale PublishToBlob.proj
  PublishToBlob.proj
Labels: merge-when-branch-open, merge-carefully

#8576 Remove unnecessary remove from ProjectRootElementCache
  src/Build/Collections/WeakValueDictionary.cs
  src/Build/Evaluation/ProjectRootElementCache.cs
Labels: merge-when-branch-open

#8520 Proposal for secrets metadata feature
  documentation/specs/proposed/security-metadata.md
Labels: Documentation, merge-when-branch-open

#8719 [LiveLogger] Fix error and warning message alignment
  src/MSBuild/LiveLogger/AnsiCodes.cs
  src/MSBuild/LiveLogger/LiveLogger.cs
Labels: merge-when-branch-open

#8714 Avoid package dependencies on inbox libraries (second attempt)
  src/Build/Microsoft.Build.csproj
  src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
  src/Tasks/Microsoft.Build.Tasks.csproj
Labels: merge-when-branch-open, merge-carefully

#8730 [vs17.2] Update sdk version to bump pulled runtime
  eng/Versions.props
  global.json
Labels: merge-when-branch-open

#8688 [RAR] Don't do I/O on SDK-provided references
  documentation/wiki/ChangeWaves.md
  src/Framework/ChangeWaves.cs
  src/Shared/Constants.cs
  src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs
  src/Tasks.UnitTests/HintPathResolver_Tests.cs
  src/Tasks/AssemblyDependency/AssemblyFoldersExResolver.cs
  src/Tasks/AssemblyDependency/AssemblyFoldersFromConfig/AssemblyFoldersFromConfigResolver.cs
  src/Tasks/AssemblyDependency/AssemblyFoldersResolver.cs
  src/Tasks/AssemblyDependency/AssemblyResolution.cs
  src/Tasks/AssemblyDependency/CandidateAssemblyFilesResolver.cs
  src/Tasks/AssemblyDependency/DirectoryResolver.cs
  src/Tasks/AssemblyDependency/FrameworkPathResolver.cs
  src/Tasks/AssemblyDependency/GacResolver.cs
  src/Tasks/AssemblyDependency/HintPathResolver.cs
  src/Tasks/AssemblyDependency/RawFilenameResolver.cs
  src/Tasks/AssemblyDependency/ReferenceTable.cs
  src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
  src/Tasks/AssemblyDependency/Resolver.cs
  src/Tasks/InstalledSDKResolver.cs
Labels: performance, merge-when-branch-open

#8742 Optimize locking in ProjectCollection (low risk)
  src/Build/Definition/ProjectCollection.cs
  src/Build/Utilities/ReaderWriterLockSlimExtensions.cs
Labels: performance

#8739 [Own build] Don't use AssemblyInformationCachePaths
  Directory.Build.props
Labels: merge-when-branch-open

#8734 Fix logerror xslTransform task
  src/Tasks/XslTransformation.cs
Labels: merge-when-branch-open

#8744 Link from ChangeWaves-dev to ChangeWaves
  documentation/wiki/ChangeWaves-Dev.md
Labels: merge-when-branch-open

#8503 Detect .NET SDK & VSLANG Custom Language Settings & Apply To MSBuild
  newc/Program.cs
  newc/newc.csproj
  src/Build/Logging/DistributedLoggers/DistributedFileLogger.cs
  src/Build/Logging/FileLogger.cs
  src/Deprecated/Engine/Logging/FileLogger.cs
  src/Framework/EncodingUtilities.cs
  src/MSBuild.UnitTests/XMake_Tests.cs
  src/MSBuild/AutomaticEncodingRestorer.cs
  src/MSBuild/MSBuild.csproj
  src/MSBuild/XMake.cs
Labels: Breaking Change, merge-when-branch-open

#8740 [vs17.2] Update vulnerable packages versions
  eng/Packages.props
  eng/Versions.props
  src/Directory.Build.targets
  src/MSBuild/MSBuild.csproj
  src/StringTools.Benchmark/StringTools.Benchmark.csproj
Labels: merge-when-branch-open

#8747 Use CopyOnWritePropertyDictionary.ImportProperties for batching
  src/Build/Instance/ProjectInstance.cs
  src/Build/Instance/ProjectItemDefinitionInstance.cs
  src/Build/Instance/ProjectItemInstance.cs
Labels: merge-when-branch-open

#8758 [vs17.2] Expliciltly require matching version of VS for signing validation step
  eng/Versions.props
  global.json
Labels: merge-when-branch-open
