Repository dotnet/msbuild, pull requests merged in 2023-06, with the labels that each got.

#8805 Change how verbosity is set Fixes #4543
  src/MSBuild/XMake.cs
Labels: merge-when-branch-open

#8530 Localize error
  src/Tasks/ResourceHandling/MSBuildResXReader.cs
  src/Tasks/Resources/Strings.resx
  src/Tasks/Resources/xlf/Strings.cs.xlf
  src/Tasks/Resources/xlf/Strings.de.xlf
  src/Tasks/Resources/xlf/Strings.es.xlf
  src/Tasks/Resources/xlf/Strings.fr.xlf
  src/Tasks/Resources/xlf/Strings.it.xlf
  src/Tasks/Resources/xlf/Strings.ja.xlf
  src/Tasks/Resources/xlf/Strings.ko.xlf
  src/Tasks/Resources/xlf/Strings.pl.xlf
  src/Tasks/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Resources/xlf/Strings.ru.xlf
  src/Tasks/Resources/xlf/Strings.tr.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open

#8806 Clarify help text for verbosity Resolves #2359
  src/MSBuild/Resources/Strings.resx
  src/MSBuild/Resources/xlf/Strings.cs.xlf
  src/MSBuild/Resources/xlf/Strings.de.xlf
  src/MSBuild/Resources/xlf/Strings.es.xlf
  src/MSBuild/Resources/xlf/Strings.fr.xlf
  src/MSBuild/Resources/xlf/Strings.it.xlf
  src/MSBuild/Resources/xlf/Strings.ja.xlf
  src/MSBuild/Resources/xlf/Strings.ko.xlf
  src/MSBuild/Resources/xlf/Strings.pl.xlf
  src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
  src/MSBuild/Resources/xlf/Strings.ru.xlf
  src/MSBuild/Resources/xlf/Strings.tr.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open

#8859 Avoid delegate allocation in EvaluatorData constructor
  src/Build/Evaluation/LazyItemEvaluator.EvaluatorData.cs
  src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs
  src/Build/Evaluation/LazyItemEvaluator.cs
Labels: performance

#8872 Add solution global properties for solution-based graphs
  src/Build.UnitTests/Graph/GraphLoadedFromSolution_tests.cs
  src/Build/Graph/GraphBuilder.cs
Labels: merge-when-branch-open

#8918 17.7 final branding
  eng/Versions.props
Labels: Area: Our Own Build
