Repository dotnet/msbuild, pull requests merged in 2023-02, with the labels that each got.

#8356 [FancyLogger] -> LiveLogger
  documentation/fancylogger/Opt-In-Mechanism.md
  documentation/livelogger/Opt-In-Mechanism.md
  src/MSBuild/CommandLineSwitches.cs
  src/MSBuild/LiveLogger/ANSIBuilder.cs
  src/MSBuild/LiveLogger/LiveLogger.cs
  src/MSBuild/LiveLogger/MessageNode.cs
  src/MSBuild/LiveLogger/ProjectNode.cs
  src/MSBuild/LiveLogger/TargetNode.cs
  src/MSBuild/LiveLogger/TaskNode.cs
  src/MSBuild/LiveLogger/TerminalBuffer.cs
  src/MSBuild/MSBuild.csproj
  src/MSBuild/XMake.cs
Labels: merge-when-branch-open

#8249 Support laxer isolation mode `-isolate:Message`
  src/Build.UnitTests/BackEnd/CacheSerialization_Tests.cs
  src/Build.UnitTests/BackEnd/MockHost.cs
  src/Build.UnitTests/BackEnd/NodeEndpointInProc_Tests.cs
  src/Build.UnitTests/BackEnd/Scheduler_Tests.cs
  src/Build.UnitTests/Graph/IsolateProjects_Tests.cs
  src/Build.UnitTests/Graph/ResultCacheBasedBuilds_Tests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/BuildManager/BuildParameters.cs
  src/Build/BackEnd/BuildManager/CacheSerialization.cs
  src/Build/BackEnd/BuildManager/ProjectIsolationMode.cs
  src/Build/BackEnd/Components/Caching/ConfigCacheWithOverride.cs
  src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
  src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
  src/Build/BackEnd/Components/Scheduler/Scheduler.cs
  src/Build/BackEnd/Shared/BuildResult.cs
  src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
  src/Build/Microsoft.Build.csproj
  src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
  src/MSBuild/Resources/Strings.resx
  src/MSBuild/Resources/xlf/Strings.cs.xlf
  src/MSBuild/Resources/xlf/Strings.de.xlf
  src/MSBuild/Resources/xlf/Strings.es.xlf
  src/MSBuild/Resources/xlf/Strings.fr.xlf
  src/MSBuild/Resources/xlf/Strings.it.xlf
  src/MSBuild/Resources/xlf/Strings.ja.xlf
  src/MSBuild/Resources/xlf/Strings.ko.xlf
  src/MSBuild/Resources/xlf/Strings.pl.xlf
  src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
  src/MSBuild/Resources/xlf/Strings.ru.xlf
  src/MSBuild/Resources/xlf/Strings.tr.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
  src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
  src/MSBuild/XMake.cs
  src/Shared/UnitTests/ObjectModelHelpers.cs
Labels: merge-when-branch-open

#8314 [FancyLogger] Footer shows progress bar of completed projects
  src/MSBuild/LiveLogger/LiveLogger.cs
  src/MSBuild/LiveLogger/TerminalBuffer.cs
Labels: merge-when-branch-open

#8315 Sync ProcessorArchitectures with those known by runtime.
  src/Framework/NativeMethods.cs
  src/Utilities.UnitTests/ProcessorArchitecture_Tests.cs
  src/Utilities/ProcessorArchitecture.cs
Labels: merge-when-branch-open

#8395 Set an environment variable indicating that the binary logger is enabled
  src/Build/Logging/BinaryLogger/BinaryLogger.cs
Labels: merge-when-branch-open

#8340 Fix .NET 3.5 InternableString.GetHashCode to match the full implementation
  src/StringTools/InternableString.Simple.cs
Labels: merge-when-branch-open

#8324 [FancyLogger] Show link to project outputs
  src/MSBuild/LiveLogger/ANSIBuilder.cs
  src/MSBuild/LiveLogger/LiveLogger.cs
  src/MSBuild/LiveLogger/MessageNode.cs
  src/MSBuild/LiveLogger/ProjectNode.cs
  src/MSBuild/LiveLogger/TerminalBuffer.cs
Labels: merge-when-branch-open

#8397 [LiveLogger] Add code to high priority messages
  src/MSBuild/LiveLogger/MessageNode.cs
Labels: merge-when-branch-open

#8390 Added README.md and updated the table of contents in `documentation` folder
  documentation/Home.md
  documentation/README.md
  documentation/WhenGlobbingReturnsOriginalFilespec.md
  documentation/deprecated/Building-Testing-and-Debugging-on-Mono-MSBuild.md
  documentation/design/rar-as-service.md
  documentation/specs/sdk-resolvers-algorithm.md
  documentation/specs/sdk-resolvers.md
  documentation/specs/single-project-isolated-builds.md
  documentation/wiki/Interactions-with-the-internal-repository.md
  documentation/wiki/Mac-Debugging.md
Labels: merge-when-branch-open

#8330 Support `SkipNonexistentTargets` in project reference target protocol
  src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
  src/Build.UnitTests/Graph/ResultCacheBasedBuilds_Tests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/BuildManager/CacheSerialization.cs
  src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs
  src/Build/BackEnd/Components/Scheduler/Scheduler.cs
  src/Build/BackEnd/Shared/BuildRequestConfiguration.cs
  src/Build/BackEnd/Shared/BuildResult.cs
  src/Build/Graph/ProjectInterpretation.cs
  src/Shared/UnitTests/ObjectModelHelpers.cs
  src/Tasks/Microsoft.Managed.After.targets
Labels: Area: Static Graph, merge-when-branch-open

#8352 Fix temp file filtering in FileTracker
  src/Utilities.UnitTests/TrackedDependencies/FileTrackerTests.cs
  src/Utilities/TrackedDependencies/FileTracker.cs
Labels: Servicing-approved

#8383 Add nodes orchestration doc
  documentation/README.md
  documentation/wiki/Nodes-Orchestration.md
Labels: merge-when-branch-open

#8378 Enable temporary comm logging for CanShutdownServerProcess test
  src/Build.UnitTests/BackEnd/DebugUtils_tests.cs
  src/Build.UnitTests/Graph/IsolateProjects_Tests.cs
  src/Build/BackEnd/Client/MSBuildClient.cs
  src/MSBuild.UnitTests/MSBuildServer_Tests.cs
  src/Shared/UnitTests/TestAssemblyInfo.cs
  src/Shared/UnitTests/TestEnvironment.cs
Labels: merge-when-branch-open

#8368 Introduce backport GHA
  .github/workflows/backport.yml
Labels: merge-when-branch-open

#8366 Add ability to create temp mapped drive for integration tests
  src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs
  src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj
  src/UnitTests.Shared/DriveMapping.cs
  src/UnitTests.Shared/DummyMappedDrive.cs
Labels: merge-when-branch-open

#8385 [LiveLogger] First tweaks to UI
  src/MSBuild/LiveLogger/ANSIBuilder.cs
  src/MSBuild/LiveLogger/LiveLogger.cs
  src/MSBuild/LiveLogger/ProjectNode.cs
  src/MSBuild/LiveLogger/TerminalBuffer.cs
Labels: merge-when-branch-open

#8345 New Trace overloads without array allocation and boxing
  src/Shared/CommunicationsUtilities.cs
Labels: merge-when-branch-open

#8328 Skip symlink tests when symlinks cannot be created
  src/Build.UnitTests/BackEnd/DebugUtils_tests.cs
  src/Build.UnitTests/BinaryLogger_Tests.cs
  src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
  src/Framework/NativeMethods.cs
  src/Shared/UnitTests/FileMatcher_Tests.cs
  src/Tasks.UnitTests/Copy_Tests.cs
  src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
  src/UnitTests.Shared/RequiresSymbolicLinksFactAttribute.cs
Labels: merge-when-branch-open

#8437 Update links referencing git branches from master -> main
  .github/ISSUE_TEMPLATE/03_mybuildisbroken.md
  documentation/specs/project-cache.md
  documentation/specs/single-project-isolated-builds.md
  documentation/specs/task-isolation-and-dependencies.md
  documentation/wiki/Building-Testing-and-Debugging-on-Full-Framework-MSBuild.md
  documentation/wiki/Contributing-Code.md
  documentation/wiki/Localization.md
  src/Framework/ChangeWaves.cs
  src/Shared/FileMatcher.cs
Labels: Documentation, merge-when-branch-open

#8427 Store desired color for top color
  src/MSBuild/LiveLogger/ProjectNode.cs
  src/MSBuild/LiveLogger/TerminalBuffer.cs
Labels: merge-when-branch-open

#8423 switched to YAML github templates
  .github/ISSUE_TEMPLATE/01_bugreport.md
  .github/ISSUE_TEMPLATE/01_bugreport.yml
  .github/ISSUE_TEMPLATE/02_performanceissue.md
  .github/ISSUE_TEMPLATE/02_performanceissue.yml
  .github/ISSUE_TEMPLATE/03_mybuildisbroken.md
  .github/ISSUE_TEMPLATE/03_mybuildisbroken.yml
  .github/ISSUE_TEMPLATE/04_blankissue.md
  .github/ISSUE_TEMPLATE/05_unhandledexception.md
  .github/ISSUE_TEMPLATE/05_unhandledexception.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: merge-when-branch-open

#8371 Warn about unused WriteOnlyWhenDifferent attribute
  src/Tasks/FileIO/WriteLinesToFile.cs
  src/Tasks/Resources/Strings.resx
  src/Tasks/Resources/xlf/Strings.cs.xlf
  src/Tasks/Resources/xlf/Strings.de.xlf
  src/Tasks/Resources/xlf/Strings.es.xlf
  src/Tasks/Resources/xlf/Strings.fr.xlf
  src/Tasks/Resources/xlf/Strings.it.xlf
  src/Tasks/Resources/xlf/Strings.ja.xlf
  src/Tasks/Resources/xlf/Strings.ko.xlf
  src/Tasks/Resources/xlf/Strings.pl.xlf
  src/Tasks/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Resources/xlf/Strings.ru.xlf
  src/Tasks/Resources/xlf/Strings.tr.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open

#8351 Fix temp file filtering in FileTracker
  src/Utilities.UnitTests/TrackedDependencies/FileTrackerTests.cs
  src/Utilities/TrackedDependencies/FileTracker.cs
Labels: merge-when-branch-open

#8424 Added support for logging interpolated strings in tasks.
  src/Framework/LogInterpolatedStringHandler.cs
  src/Shared/TaskLoggingHelper.cs
  src/Utilities.UnitTests/MockEngine.cs
  src/Utilities.UnitTests/TaskLoggingHelper_Tests.cs
Labels: merge-when-branch-open

#8454 Fix grammar in IForwardingLogger
  src/Framework/IForwardingLogger.cs
Labels: Documentation, merge-when-branch-open

#8444 BuildManager instances acquire its own BuildTelemetry instance
  src/Build.UnitTests/BackEnd/KnownTelemetry_Tests.cs
  src/Build/BackEnd/BuildManager/BuildManager.cs
  src/Build/BackEnd/Client/MSBuildClient.cs
  src/Build/BackEnd/Node/OutOfProcServerNode.cs
  src/Framework/Telemetry/KnownTelemetry.cs
  src/MSBuild/MSBuildClientApp.cs
  src/MSBuild/XMake.cs
Labels: merge-when-branch-open

#8451 Make LiveLogger distributed
  src/MSBuild/LiveLogger/LiveLogger.cs
  src/MSBuild/XMake.cs
Labels: performance, merge-when-branch-open

#8446 Improve VS binlogs providing info
  documentation/wiki/Binary-Log.md
  documentation/wiki/Providing-Binary-Logs.md
Labels: merge-when-branch-open

#8440 Add exception message and stack strace for task DownloadFile fails
  src/Tasks/DownloadFile.cs
Labels: merge-when-branch-open

#8467 [LiveLogger] Fix for conhost.exe
  src/MSBuild/XMake.cs
Labels: merge-when-branch-open

#8465 [LiveLogger] Report build time
  src/MSBuild/LiveLogger/LiveLogger.cs
Labels: merge-when-branch-open

#8477 Fix graph p2p protocol when using DeployOnBuild=true
  src/Tasks/Microsoft.Managed.After.targets
Labels: merge-when-branch-open

#8406 LiveLogger: Don't blink
  src/MSBuild/LiveLogger/ANSIBuilder.cs
  src/MSBuild/LiveLogger/ProjectNode.cs
Labels: merge-when-branch-open

#8316 Log assembly loads during task run
  documentation/wiki/ChangeWaves.md
  src/Build.UnitTests/BinaryLogger_Tests.cs
  src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
  src/Build/BackEnd/Components/Logging/LoggingService.cs
  src/Build/BackEnd/Components/RequestBuilder/AssemblyLoadsTracker.cs
  src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
  src/Build/Evaluation/Evaluator.cs
  src/Build/Instance/TaskFactories/AssemblyTaskFactory.cs
  src/Build/Logging/BinaryLogger/BinaryLogRecordKind.cs
  src/Build/Logging/BinaryLogger/BinaryLogger.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
  src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
  src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs
  src/Build/Microsoft.Build.csproj
  src/Build/Resources/Strings.resx
  src/Build/Resources/xlf/Strings.cs.xlf
  src/Build/Resources/xlf/Strings.de.xlf
  src/Build/Resources/xlf/Strings.es.xlf
  src/Build/Resources/xlf/Strings.fr.xlf
  src/Build/Resources/xlf/Strings.it.xlf
  src/Build/Resources/xlf/Strings.ja.xlf
  src/Build/Resources/xlf/Strings.ko.xlf
  src/Build/Resources/xlf/Strings.pl.xlf
  src/Build/Resources/xlf/Strings.pt-BR.xlf
  src/Build/Resources/xlf/Strings.ru.xlf
  src/Build/Resources/xlf/Strings.tr.xlf
  src/Build/Resources/xlf/Strings.zh-Hans.xlf
  src/Build/Resources/xlf/Strings.zh-Hant.xlf
  src/Framework.UnitTests/AssemblyLoadBuildEventArgs_Tests.cs
  src/Framework/AssemblyLoadBuildEventArgs.cs
  src/Framework/AssemblyLoadingContext.cs
  src/Framework/Traits.cs
  src/MSBuild/OutOfProcTaskAppDomainWrapperBase.cs
  src/MSBuild/XMake.cs
  src/Shared/BinaryReaderExtensions.cs
  src/Shared/BinaryWriterExtensions.cs
  src/Shared/LogMessagePacketBase.cs
  src/Shared/TaskLoader.cs
  src/Shared/UnitTests/EngineTestEnvironment.cs
Labels: merge-when-branch-open

#8482 Dogfood "build acceleration"
  Directory.Build.props
Labels: merge-when-branch-open

#8480 LiveLogger: ConcurrentDictionary for projects
  src/MSBuild/LiveLogger/LiveLogger.cs
Labels: merge-when-branch-open
