Repository dotnet/msbuild, pull requests merged in 2023-01, with the labels that each got.

#8256 Update .vsconfig to remove .NET Core 2.1 component
  .vsconfig
Labels: merge-when-branch-open

#8271 Stop dumping stack for BadImageFormatException
  src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs
  src/Tasks/AssemblyDependency/BadImageReferenceException.cs
  src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
Labels: merge-when-branch-open

#8258 [FancyLogger] Add nodes data structures and optimize buffer
  src/Build/Logging/FancyLogger/FancyLogger.cs
  src/Build/Logging/FancyLogger/FancyLoggerBuffer.cs
  src/Build/Logging/FancyLogger/FancyLoggerMessageNode.cs
  src/Build/Logging/FancyLogger/FancyLoggerNode.cs
  src/Build/Logging/FancyLogger/FancyLoggerProjectNode.cs
  src/Build/Logging/FancyLogger/FancyLoggerTargetNode.cs
  src/Build/Logging/FancyLogger/FancyLoggerTaskNode.cs
Labels: merge-when-branch-open

#8266 Ensure trailing slash for string used as key in AssemblyTableInfo's cache
  src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
  src/Tasks/RedistList.cs
Labels: merge-when-branch-open

#8257 Exclude isolation-violating cache results from output results cache (#4386)
  src/Build.UnitTests/BackEnd/CacheSerialization_Tests.cs
  src/Build.UnitTests/BackEnd/ConfigCache_Tests.cs
  src/Build/BackEnd/BuildManager/CacheSerialization.cs
  src/Build/BackEnd/Components/Caching/ConfigCache.cs
Labels: merge-when-branch-open

#8264 Backport opt-prof v2 vs17.2
  .opt-prof.yml
  .vsts-dotnet.yml
  eng/config/OptProf.runsettings
Labels: merge-when-branch-open

#8234 Disable MotW check on core in GenerateResource
  src/Tasks/GenerateResource.cs
Labels: Servicing-approved

#8267 Avoid removing outer -> inner graph edge
  src/Build.UnitTests/Graph/GraphLoadedFromSolution_tests.cs
  src/Build.UnitTests/Graph/GraphTestingUtilities.cs
  src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
  src/Build/Graph/GraphBuilder.cs
  src/Build/Graph/ProjectInterpretation.cs
Labels: Area: Static Graph, merge-when-branch-open

#8309 FancyLogger: Hide cursor on alternate buffer
  src/Build/Logging/FancyLogger/ANSIBuilder.cs
  src/Build/Logging/FancyLogger/FancyLoggerBuffer.cs
Labels: merge-when-branch-open

#8310 [FancyLogger] Clear screen on ctrl-c
  src/Build/Logging/FancyLogger/FancyLogger.cs
Labels: merge-when-branch-open

#8284 [FancyLogger] Hide messages for completed projects during build, but show them again in summary
  src/Build/Logging/FancyLogger/FancyLogger.cs
  src/Build/Logging/FancyLogger/FancyLoggerBuffer.cs
  src/Build/Logging/FancyLogger/FancyLoggerMessageNode.cs
  src/Build/Logging/FancyLogger/FancyLoggerProjectNode.cs
  src/Build/Logging/FancyLogger/FancyLoggerTargetNode.cs
Labels: merge-when-branch-open

#8288 Update version to 17.6
  eng/Versions.props
Labels: merge-when-branch-open

#8305 Allow to set empty string for XmlPoke Value
  src/Tasks.UnitTests/XmlPoke_Tests.cs
  src/Tasks/XmlPoke.cs
Labels: merge-when-branch-open

#8307 Use GetTemporaryFileName over GetTemporaryFile to avoid extraneous i/o
  src/Build.OM.UnitTests/Construction/ProjectFormatting_Tests.cs
  src/Build.OM.UnitTests/Construction/ProjectImportElement_Tests.cs
  src/Build.OM.UnitTests/Construction/ProjectRootElement_Tests.cs
  src/Build.OM.UnitTests/Construction/SolutionFile_Tests.cs
  src/Build.OM.UnitTests/Construction/WhiteSpacePreservation_Tests.cs
  src/Build.OM.UnitTests/Definition/ProjectCollection_Tests.cs
  src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs
  src/Build.OM.UnitTests/Definition/ProjectProperty_Tests.cs
  src/Build.OM.UnitTests/Definition/Project_Tests.cs
  src/Build.OM.UnitTests/Definition/ProtectImports_Tests.cs
  src/Build.OM.UnitTests/Instance/ProjectTargetInstance_Tests.cs
  src/Build.UnitTests/BackEnd/IntrinsicTask_Tests.cs
  src/Build.UnitTests/BackEnd/TargetUpToDateChecker_Tests.cs
  src/Build.UnitTests/Construction/ElementLocation_Tests.cs
  src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
  src/Build.UnitTests/Definition/ItemDefinitionGroup_Tests.cs
  src/Build.UnitTests/Evaluation/Evaluator_Tests.cs
  src/Build.UnitTests/Evaluation/ProjectRootElementCache_Tests.cs
  src/Build.UnitTests/Evaluation/ProjectStringCache_Tests.cs
  src/Build.UnitTests/ExpressionTree_Tests.cs
  src/Build.UnitTests/FileLogger_Tests.cs
  src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
  src/MSBuild.UnitTests/ProjectSchemaValidationHandler_Tests.cs
  src/Shared/TempFileUtilities.cs
  src/Shared/UnitTests/NativeMethodsShared_Tests.cs
  src/Tasks.UnitTests/AssemblyDependency/FilePrimary.cs
  src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs
  src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs
  src/Tasks.UnitTests/AssemblyDependency/StronglyNamedDependencyAppConfig.cs
  src/Tasks.UnitTests/AssemblyDependency/StronglyNamedDependencyAutoUnify.cs
  src/Tasks.UnitTests/Move_Tests.cs
  src/Tasks.UnitTests/ReadLinesFromFile_Tests.cs
  src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs
  src/Tasks.UnitTests/ResourceHandling/ResGenDependencies_Tests.cs
  src/Tasks.UnitTests/XamlTaskFactory_Tests.cs
  src/Tasks/Exec.cs
  src/Tasks/ManifestUtil/ManifestWriter.cs
  src/Tasks/ManifestUtil/Util.cs
  src/Utilities.UnitTests/TaskLoggingHelper_Tests.cs
  src/Utilities.UnitTests/ToolTask_Tests.cs
  src/Utilities.UnitTests/TrackedDependencies/FileTrackerTests.cs
  src/Utilities/ToolTask.cs
  src/Utilities/TrackedDependencies/FileTracker.cs
Labels: merge-when-branch-open

#8306 Handle symlinks embedding into binlogs - approach #2
  src/Build.UnitTests/BinaryLogger_Tests.cs
  src/Build/Logging/BinaryLogger/ProjectImportsCollector.cs
  src/Framework/NativeMethods.cs
Labels: merge-when-branch-open

#8308 Sort paths descendingly by depth
  src/Shared/UnitTests/ObjectModelHelpers.cs
Labels: merge-when-branch-open

#8304 Backport opt-prof v2 vs17.4
  .opt-prof.yml
  .vsts-dotnet.yml
  eng/config/OptProf.runsettings
Labels: merge-when-branch-open

#8294 Add Retries, RetryDelayMilliseconds parameters to Delete task
  src/Tasks.UnitTests/Delete_Tests.cs
  src/Tasks/Delete.cs
  src/Tasks/Resources/Strings.resx
  src/Tasks/Resources/xlf/Strings.cs.xlf
  src/Tasks/Resources/xlf/Strings.de.xlf
  src/Tasks/Resources/xlf/Strings.es.xlf
  src/Tasks/Resources/xlf/Strings.fr.xlf
  src/Tasks/Resources/xlf/Strings.it.xlf
  src/Tasks/Resources/xlf/Strings.ja.xlf
  src/Tasks/Resources/xlf/Strings.ko.xlf
  src/Tasks/Resources/xlf/Strings.pl.xlf
  src/Tasks/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Resources/xlf/Strings.ru.xlf
  src/Tasks/Resources/xlf/Strings.tr.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open

#8292 [FancyLogger] Added support for line wrappings
  src/Build/Logging/FancyLogger/ANSIBuilder.cs
  src/Build/Logging/FancyLogger/FancyLogger.cs
  src/Build/Logging/FancyLogger/FancyLoggerBuffer.cs
  src/Build/Logging/FancyLogger/FancyLoggerMessageNode.cs
  src/Build/Logging/FancyLogger/FancyLoggerProjectNode.cs
Labels: merge-when-branch-open

#8238 Localize strings of link error messages on non-Windows
  src/Framework/NativeMethods.cs
  src/Tasks.UnitTests/Copy_Tests.cs
  src/Tasks/Copy.cs
  src/Tasks/NativeMethods.cs
  src/Tasks/Resources/Strings.resx
  src/Tasks/Resources/xlf/Strings.cs.xlf
  src/Tasks/Resources/xlf/Strings.de.xlf
  src/Tasks/Resources/xlf/Strings.es.xlf
  src/Tasks/Resources/xlf/Strings.fr.xlf
  src/Tasks/Resources/xlf/Strings.it.xlf
  src/Tasks/Resources/xlf/Strings.ja.xlf
  src/Tasks/Resources/xlf/Strings.ko.xlf
  src/Tasks/Resources/xlf/Strings.pl.xlf
  src/Tasks/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Resources/xlf/Strings.ru.xlf
  src/Tasks/Resources/xlf/Strings.tr.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Labels: merge-when-branch-open

#8337 Add AccelerateBuildsInVisualStudio to XSD
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Labels: merge-when-branch-open

#8331 [FancyLogger] Improve render performance
  src/Build/Logging/FancyLogger/ANSIBuilder.cs
  src/Build/Logging/FancyLogger/FancyLogger.cs
  src/Build/Logging/FancyLogger/FancyLoggerBuffer.cs
  src/Build/Logging/FancyLogger/FancyLoggerMessageNode.cs
  src/Build/Logging/FancyLogger/FancyLoggerProjectNode.cs
Labels: merge-when-branch-open

#8347 Update to .NET 7-era packages
  eng/Versions.props
  eng/dependabot/Packages.props
  src/MSBuild/app.amd64.config
  src/MSBuild/app.config
  src/Tasks/System.Resources.Extensions.pkgdef
Labels: merge-when-branch-open

#8353 Fix temp file filtering in FileTracker
  src/Utilities.UnitTests/TrackedDependencies/FileTrackerTests.cs
  src/Utilities/TrackedDependencies/FileTracker.cs
Labels: Servicing-approved

#8342 XSD: InternalsVisibleTo uses Key
  src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Labels: merge-when-branch-open, Area: IntelliSense

#8318 Build RequiresFramework35SP1Assembly task for net7
  src/Tasks/Microsoft.Build.Tasks.csproj
Labels: merge-when-branch-open

#8317 Central Package Management
  Directory.Build.props
  Directory.Build.targets
  eng/Packages.props
  eng/dependabot/Packages.props
  global.json
  src/Samples/Directory.Build.props
Labels: merge-when-branch-open

#8367 reordered import in Samples `Directory.Build.props`
  src/Samples/Directory.Build.props
Labels: merge-when-branch-open

#8321 Infer dotnet host to run integration scenarios
  src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj
  src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
  src/MSBuild.UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj
  src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
  src/UnitTests.Shared/EnvironmentProvider.cs
  src/UnitTests.Shared/RunnerUtilities.cs
Labels: merge-when-branch-open
