Repository dotnet/msbuild, pull requests merged in 2025-03, with the labels that each got.

#11145 Update .NET Framework references to 9.0.0
  eng/SourceBuildPrebuiltBaseline.xml
  eng/Versions.props
  src/MSBuild/app.amd64.config
  src/MSBuild/app.config
  src/Package/MSBuild.VSSetup/files.swr
  src/Tasks/System.Resources.Extensions.pkgdef
Labels: do-not-merge

#11544 Don't ngen StringTools.net35
  src/Package/MSBuild.VSSetup/files.swr
Labels: Area: Visual Studio

#11577 Switch to AwesomeAssertions
  eng/dependabot/Packages.props
  src/Build.UnitTests/BackEnd/NodePackets_Tests.cs
  src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
  src/Framework.UnitTests/Microsoft.Build.Framework.UnitTests.csproj
Labels: Area: Our Own Build, Area: Tests

#11457 Update maintenance-packages versions
  eng/Versions.props
Labels: blocked

#11038 Update assembly versions to latest for packages that recently shipped
  eng/Packages.props
  eng/Versions.props
  src/MSBuild/app.amd64.config
  src/MSBuild/app.config
Labels: do-not-merge
