Repository dotnet/msbuild, pull requests merged in 2025-08, with the labels that each got.

#12259 Update reasoning in a doc
  documentation/specs/build-nonexistent-projects-by-default.md
Labels: Area: Documentation

#12238 Align TL creation API with msbuild.exe forcing behavior
  src/Build.UnitTests/TerminalLogger_Tests.cs
  src/Build/Logging/TerminalLogger/TerminalLogger.cs
Labels: Area: Terminal Logger

#12296 Add overload for ProjectCollection constructor to prevent binary breaking change
  src/Build/CompatibilitySuppressions.xml
  src/Build/Definition/ProjectCollection.cs
Labels: Area: API

#12383 Don't leak SDK-resolver environment to global env
  src/Build/Instance/ProjectInstance.cs
Labels: Servicing-approved

#12354 [vs17.14]Move GlobExpansionFailed resource from Build to Shared
  eng/Versions.props
  src/Build/Resources/Strings.resx
  src/Build/Resources/xlf/Strings.cs.xlf
  src/Build/Resources/xlf/Strings.de.xlf
  src/Build/Resources/xlf/Strings.es.xlf
  src/Build/Resources/xlf/Strings.fr.xlf
  src/Build/Resources/xlf/Strings.it.xlf
  src/Build/Resources/xlf/Strings.ja.xlf
  src/Build/Resources/xlf/Strings.ko.xlf
  src/Build/Resources/xlf/Strings.pl.xlf
  src/Build/Resources/xlf/Strings.pt-BR.xlf
  src/Build/Resources/xlf/Strings.ru.xlf
  src/Build/Resources/xlf/Strings.tr.xlf
  src/Build/Resources/xlf/Strings.zh-Hans.xlf
  src/Build/Resources/xlf/Strings.zh-Hant.xlf
  src/Shared/FileMatcher.cs
  src/Shared/Resources/Strings.shared.resx
  src/Shared/Resources/xlf/Strings.shared.cs.xlf
  src/Shared/Resources/xlf/Strings.shared.de.xlf
  src/Shared/Resources/xlf/Strings.shared.es.xlf
  src/Shared/Resources/xlf/Strings.shared.fr.xlf
  src/Shared/Resources/xlf/Strings.shared.it.xlf
  src/Shared/Resources/xlf/Strings.shared.ja.xlf
  src/Shared/Resources/xlf/Strings.shared.ko.xlf
  src/Shared/Resources/xlf/Strings.shared.pl.xlf
  src/Shared/Resources/xlf/Strings.shared.pt-BR.xlf
  src/Shared/Resources/xlf/Strings.shared.ru.xlf
  src/Shared/Resources/xlf/Strings.shared.tr.xlf
  src/Shared/Resources/xlf/Strings.shared.zh-Hans.xlf
  src/Shared/Resources/xlf/Strings.shared.zh-Hant.xlf
Labels: Servicing-approved
